### ISSUE TITLE
Upgrading Ontology Tagging at WikiPathways

### ISSUE THREAD

**Issue by AlexanderPico** [nrnb/GoogleSummerOfCode#1]
### Background

[WikiPathways](http://www.wikipathways.org/) is a wiki, like Wikipedia, but for biological pathway diagrams. We ripped out the text editor of [Mediawiki](https://www.mediawiki.org/wiki/Manual:What_is_MediaWiki%3F) and put in a custom pathway drawing tool. In addition to capturing pathway models, we have a number of systems to annotate pathway using standardized identifiers and ontology terms.  Ontology terms help users classify, query and filter the content at WikiPathways.

For example, there is an ontology of biological pathways, i.e., a defined set of pathway names organized in a hierarchical list. Every pathway added to WikiPathways should have one or more of these pathway ontology terms associated with it. See the _Ontology Tags_ section on [this example pathway](http://wikipathways.org/index.php/Pathway:WP554).   This tagging system relies on web service calls to BioPortal and a Mediawiki extension (PHP) to call to the WikiPathways database (MySQL).
### Goal

This project will upgrade the current ontology tagging system at WikiPathways to take full advantage of the latest services from NCBO’s [BioPortal](http://bioportal.bioontology.org/). The upgrade work will include overhauling the current tagging system from the database table schema up to the user interface. Promising proposals will include an assessment of the current system, research in to the available web services at BioPortal, and a set of features to overhaul and add.
### Difficultly Level: 2

Some experience with [Mediawiki](https://www.mediawiki.org/wiki/Manual:What_is_MediaWiki%3F) and/or [BioPortal](http://bioportal.bioontology.org/) is preferred.

### Potential Mentors
- Alex Pico
- Martina Summer-Kutmon

#### Contact

[Alex Pico](mailto:alex.pico@gladstone.ucsf.edu), [Martina Summer-Kutmon](mailto:mkutmon@gmail.com)

**Comment by khanspers** [comment]
GSoC 2018
