### ISSUE TITLE
JSEDML: Java Library for Simulation Experiment Descriptions

### ISSUE THREAD

**Issue by matthiaskoenig** [nrnb/GoogleSummerOfCode#101]
<img title="tellurium logo" src="https://sed-ml.github.io/images/logoSEDML_H75.png" height="40" />

### Background
The [Simulation Experiment Description Markup Language (SED-ML)](
https://sed-ml.github.io/) is an XML-based format for the
description of simulation experiments. The number of computational models of biological systems is growing at an ever-increasing pace.  At the same time, their size and complexity are also increasing.  It is now generally accepted that one must be able to exchange the mathematical structure of such models, for instance, to build on existing studies by reusing models or for the reproduction of model results.  

SED-ML  describes  in  a  computer-readable  exchange  format  the  information  for  the  reproduction  of simulation  experiments. SED-ML  is  a  software-independent  format  encoded  in  XML  not  specific  to particular simulation tools and independent of the underlying model language. 

With the recent publication of [SED-ML L1V3](https://sed-ml.github.io/documents/sed-ml-L1V3.pdf), it is now possible to include and use data in simulation experiments, opening the door for better integration of data and models. 

A major bottleneck for the adoption of SED-ML is that currently no dedicated Java library supporting SED-ML L1V3 exists. Multiple Java-based tools have already support for computational models in the systems biology language, but lack support for [SED-ML L1V3](https://sed-ml.github.io/documents/sed-ml-L1V3.pdf). Open Source projects immediately profiting from this project would be among others
* [iBioSim](http://www.async.ece.utah.edu/ibiosim)
* [Systems Biology Simulation Core Library](http://simulation-core.sourceforge.net/)
* [celldesigner](http://www.celldesigner.org/)
* [cy3sbml](https://github.com/matthiaskoenig/cy3sbml)
* ...

Implementing a dedicated Java library supporting SED-ML L1V3 would be an important step for the exchange, reproducibility, reusability, and interoperability of models and their simulations.

https://sed-ml.github.io/
https://sed-ml.github.io/documents/sed-ml-L1V3.pdf

### Goal
The end result of the GSOC project should be a first version of a java based SED-ML library (JSEDML) supporting the SED-ML specification L1V3.

### Difficulty Level 2
The project requires Java programming skills, understanding of SED-ML and basic knowledge of SBML. The project can reuse components and build on [jlibsedml](https://sourceforge.net/projects/jlibsedml/).

### Skills
List skills/technologies that the student should be familiar with.  Also tag the issue with these.
- Java&trade; (essential)
- SED-ML (essential)
- SBML (nice to have)

### Public Repository
https://github.com/SED-ML/JSEDML
https://github.com/sed-ml/

### Potential Mentors
[Matthias König](mailto:konigmatt@googlemail.com)
[Chris Myers](mailto:myers@ece.utah.edu)

### Contact
[Matthias König](mailto:konigmatt@googlemail.com)

**Comment by draeger** [comment]
@matthiaskoenig, I think this could still be of interest. I'd suggest to reopen this.

**Comment by khanspers** [comment]
@matthiaskoenig @draeger : This issue was closed as part of our preparation for GSoC 2021. In fact, all NRNB GSoC issues are closed for now. Stay tuned for more information coming shortly on how to reformat closed issues that are still of interest.
