### ISSUE TITLE
Improvements for Newt, a Cytoscape.js based SBGN editor

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#102]
### Background

[Newt](http://newteditor.org) is a [Cytoscape.js](http://js.cytoscape.org/) based viewer and editor for biological maps in Systems Biology Graphical Notation (SBGN) notation [1] to create biological maps from scratch or edit existing ones. It's been built (with partial support from GSoC) around an editing library named [ChiSE](https://github.com/iVis-at-Bilkent/chise.js), which in turn was based on a viewer library named [SBGNViz](https://github.com/iVis-at-Bilkent/sbgnviz.js) [2]. The tool uses a number of new [Cytoscape.js extensions](http://js.cytoscape.org/#extensions) built for various editing capabilities such as grid-guidelines, context-menus, and expand-collapse.

[1] M. Sari, I. Bahceci, U. Dogrusoz, S.O. Sumer, B.A. Aksoy, O. Babur, E. Demir, "SBGNViz: a tool for visualization and complexity management of SBGN process description maps", PLoS ONE, 10(6), e0128985, 2015.
 
[2] N. Le Novère et al., "The Systems Biology Graphical Notation", Nature Biotechnology, 27, pp. 735-741, 2009.

### Goal
With this project, we aim to design and implement new features for the Newt editor, including:
- SBML support
- More query support to pathway databases like PathwayCommons
- CellDesigner import/export

### Difficulty Level 3
The project can be considered a fairly difficult one since it involves expertise in a number of libraries as specified above in addition to prior knowledge of web programming.

### Skills
HTML, JavaScript, Cytoscape.js and its extension structure (essential)
SBGNViz and ChiSE (nice to have)

### Public Repository
[Newt GitHub repository](https://github.com/iVis-at-Bilkent/newt)

### Potential Mentors
[Ugur Dogrusoz](https://github.com/ugurdogrusoz)

### Contact
[Ugur Dogrusoz](http://www.cs.bilkent.edu.tr/~ugur/)

**Comment by khanspers** [comment]
GSoC 2018
