### ISSUE TITLE
Develop cyTRON/JS: a backend and a cytoscape.js visualizer for cancer progression models

### ISSUE THREAD

**Issue by marcoxa** [nrnb/GoogleSummerOfCode#104]
### Background

The BIMIB group has constructed a series of algorithms that reconstruct cancer progression models starting from cross-sectional data. See http://troncopackage.org and https://www.bioconductor.org/packages/release/bioc/html/TRONCO.html. The progression models are reconstructed using a theory of "probabilistic causation" rooted in Suppes' work. At the time of this writing, the R TRONCO library produces a DAG data-structure encoded in an adjacency matrix that is statically visualized using the R graphviz interface.

### Goal

In order to improve the visualization of the progression models, we have developed cyTRON, a Cytoscape app to visualize the progression models just described. We would like to propose the development of a cytoscape.js based visualizer, named cyTRON/JS as a further development of our code base.  This could be a self contained GSoC project for a motivated programmer. The main goal will be to read in the progression model DAG data-structure with all its annotations from a small data store (or, possibly, over a new cyREST bridge) and to display it in the main cytoscape.js window. The cytoscape.js DAG display will also allow for the linking of web-based resources (e.g., gene annotations), in order to provide more information for the user.

### Difficulty level: 2

Prior experience with cytoscape.js app development or extensive Javascript and graph theory experience highly recommended.

### Skills

Cytoscape.js, Javascript, Node.js, RServe, R.

### Public Repository

Check http://troncopackage.org

### Potential Mentors

Marco Antoniotti

### Contact

Marco Antoniotti (mailto:marco.antoniotti@unimib.it)

**Comment by sakshamkukreja** [comment]
Hi guys,

I'm Saksham Kukreja, a freshman at the Indian Institute of Technology Roorkee. I am highly interested in contributing to this project. As mentioned in my email correspondences, I have reason to believe that I'll be very well suited to effectively contribute towards the development of this unique idea. This project particularly piqued my interest as it closely aligns with my research that I carried out before going to college. Moreover, I seem to understand that the project requires a clear understanding of the applications of machine learning in medical diagnosis along with proficiency in Javascript, both of which I believe I possess. Although I am new to Cytoscape.js, I assure you that I am putting in the best of my efforts to learn the requisite skills in minimal time. I request you to look through my paper, which has been published on SSRN on the link: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3081746#

I also have an experience of working with Node.js which can be seen in my Project, Baymax. Baymax is a personal healthcare assistant bot deployed on Facebook that helps in diagnosing the disease via a personalized conversation. The link to the demo video: https://www.youtube.com/watch?v=LIrUde-xdvA 

I therefore request to be formally engaged in the same. As this is a self-contained project, I request you to facilitate me with the pointers that are crucial for going ahead in this direction.

Regards,
Saksham Kukreja
sakshamkukreja15@gmail.com

**Comment by sakshamkukreja** [comment]
@marcoxa I'd be grateful if you could help me in the aforementioned regard.

**Comment by khanspers** [comment]
GSoC 2018
