### ISSUE TITLE
Implement SBML Array Support in libRoadRunner

### ISSUE THREAD

**Issue by hsauro** [nrnb/GoogleSummerOfCode#107]
### Background
LibRoadrunner is a high performance SBML based simulator that uses LLVM to generate very efficient runtime code. This enables libRoadrunner to simulate models on par with compiled C/C++ code. SBML supports, via a package (file:///C:/Users/hsauro/Downloads/sbml-arrays-r0.3a.pdf), the concept of arrays which allows a modeler to represent arrays of reactions, species, parameters, models etc. Arrays can be used to model otherwise difficult situtations, for example arrays of models could be used to model agent based systems or where a system has hundreds of states which would more easily be represented using arrays. 

### Goal
The goal is to implement array support in libRoadrunner. iBiosim is currently the only tool that supports arrays and as part of the project we would ensure that array support in both tools is compatible and that models can be correctly exchanged. 

### Difficulty Level 2
This project requires some understanding of systems biology and modeling. However the project offers the opportunity to learn new skills in the area of model representation, and SBML. 

### Skills
C/C++ (essential)
Python (some)
SBML (some)

### Public Repository
https://github.com/sys-bio/roadrunner

### Potential Mentors
Herbert M Sauro

### Contact
[Herbert M Sauro ](mailto:hsauro@uw.edu)

**Comment by khanspers** [comment]
GSoC 2018
