### ISSUE TITLE
Build an Web Interface for Natural-Language Processing Extracted Interaction Network 

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#109]
### Background

The Pathway Commons team has extracted a network of biological interactions from scientific literature (http://textmining.pathwaycommons.org/pc2/); this data needs a usable interface. 

### Goal
Build a web interface for the data present in:

http://textmining.pathwaycommons.org/pc2/

That looks like the interface below: 

<img width="424" alt="hop-tool-graphic-user-interface-text-mining-algorithms-allow-the-information-relevant-to" src="https://user-images.githubusercontent.com/790284/50797061-81e7d680-12a1-11e9-921d-3675d745551f.png">

Access to the data can be done using the Pathway Commons NPM package (or from a database built using JSON files (see below)) https://www.npmjs.com/package/pathway-commons). 

#### Additional Details 

The general idea is to use this Javascript code and RethinkDB (it is a template for other projects):

https://github.com/PathwayCommons/app-ui

and this data:

https://www.dropbox.com/sh/1jy1axjfw12cpq4/AAAIsx-CMQAADlskKCeGFgKba?dl=0

Each folder is a different research article. Within each folder are JSON files that with the content that should be searchable from the site.

A representative example is this file:

PMC2787798-UAZ-r1-1.json

```
{
  "submitter":"Reach",
  "model_relation":"extension",
  "extracted_information":{
    "interaction_type":"adds_modification",
    "modifications":[
      {
        "modification_type":"hydrolysis"
      }
    ],
    "negative_information":false,
    "participant_b":{
      "in_model":true,
      "identifier":"chebi:CHEBI:42197",
      "entity_text":"daidzin",
      "entity_type":"simple_chemical"
    },
    "hypothesis_information":false,
    "context":{
      "Species":[
        "uniprot:O89094"
      ]
    }
  },
  "reading_complete":"2016-01-11T01:13:46Z",
  "reader_type":"machine",
  "reading_started":"2016-01-11T01:13:03Z",
  "trigger":"hydrolyzed",
  "evidence":[
    "daidzin, genistin, and glycitin and their corresponding 6'-Oacetyl esters are hydrolyzed"
  ],
  "pmc_id":"2787798",
  "score":0
}
```

The main results page for queries should look like the interface above where the identifiers are shown at the top for the "participants", and the sentences ("evidence") have highlighted terms from "entity_text" and "trigger" from the JSON file. The search should be pretty flexible to the entity_text or the identifiers and retrieve all the relevant sentences.

### Difficulty Level
Level 2 for developers with Javascript experience 

### Skills
Javascript (essential) 
REST APIs 

### Public Repository
[Pathway Commons](https://github.com/PathwayCommons/app-ui)

### Potential Mentors
Augustin Luna 

### Contact
[Augustin Luna](mailto:aluna@jimmy.harvard.edu)

**Comment by flaredragon** [comment]
Hello @cannin  

I am Akashdeep Ramnaney from New Delhi,India. 

I am interested in taking up this project for GSoC.

I have been working on web technologies for quite some time now. I have worked extensively with Javascript ( including Node.js,React.js,Ember.js ), HTML, CSS, JQuery, SQL (PostgreSQL, MySQL). 

I had some queries about the project.

- Could you please clarify which data needs to be used?
(The Dropbox Data or the Data from Pathway Commons API)

- Also can you please elaborate about usage of https://github.com/PathwayCommons/app-ui

It would be extremely helpful if you could guide me on how to start working on this project.

Thank you so much for all your help.

**Comment by cannin** [comment]
The project description no longer refers to the API so that shouldn't be a concern. For app-ui, what specifically are you having issues with; the GitHub page provides information on how to get it set up on your machine.

**Comment by flaredragon** [comment]
Hi 
Thanks a lot for your time
I've set up the app-ui on my system. 
could you guide me on how to proceed further on this project(any issues Or contributions I could help with)

**Comment by cannin** [comment]
This is a new project, so there is not a current repository to contribute to. As far as how to proceed, the goal remains to build the ihop interface using the app-ui code given the Dropbox data stored in a RethinkDB database.

**Comment by flaredragon** [comment]
Thank you so much!
I'll start working on the proposal and get back to you for some feedback soon.

**Comment by RohitChattopadhyay** [comment]
Is this still open for GSoC19?

**Comment by cannin** [comment]
Yes, the project is still available this year.

**Comment by mahmodHammad** [comment]
what do you mean by Difficulty: 2 ?!

**Comment by niikhilghodke** [comment]
I am not a mentor but difficulty level is just to give the participants an idea about the level of difficulty of the project .

**Comment by khanspers** [comment]
Active GSoC 2019 project.
