### ISSUE TITLE
Implement a comment/discussion system in GraphSpace

### ISSUE THREAD

**Issue by adbharadwaj** [nrnb/GoogleSummerOfCode#111]
### Background
[GraphSpace](http://graphspace.org) is an easy-to-use web-based platform collaborating research groups can use for storing, interacting with, and sharing networks. A GraphSpace user can upload graphs through a REST API, import graphs created in Cytoscape, interact with graphs (view them, customize layouts, and save layouts), share graphs (create groups and add collaborators, share graphs among all members of a group or with the world), search graphs, and organize graphs using tags. GraphSpace has a comprehensive REST API that allows users to communicate programmatically with it. Overall, GraphSpace provides a rich set of user-friendly features designed to enhance network-based collaboration.

### Goal
The aim of this project is to implement a real-time system that will allow users to comment on graphs and discuss ideas with each other using the GraphSpace web interface. This project has three sub goals:

- **Design a user interface for creating comments**. When visualizing a graph, this interface should allow users to add comments as a means to discuss or share ideas with their collaborators for a given graph, analogous to the way "Comments" on Google Docs allow users to discuss ideas on text documents. Being applicable to graphs, the comment system on GraphSpace should apply to node, edges, groups of nodes, and subgraphs, or even the entire graph. Comments can be applicable only to a specific layout as well. There should be a way to mark comments as resolved.

- **Develop a web service for real time comments**. In GSoC 2017, one of the students working on GraphSpace implemented a real-time notification system. We would like to use the same architecture to implement real time storage, querying, and recovery of comments. This task will involve studying the code to understand how GraphSpace uses sockets to support real-time notifications.

- **Integrate the web service with the user interface**. Finally, integrate the web-service with the user interface to implement an end-to-end user flow.

### Difficulty Level
Level 2

### Skills
List skills/technologies that the student should be familiar with. 

- Python, Django, HTML, JS, Jquery, CSS, Databases (SQL), Kafka  (essential)
- Git, Cytoscape.js (nice to have)

### Public Repository

https://github.com/Murali-group/GraphSpace/

### Potential Mentors

[Daniyal Jahan Warsi](https://github.com/jahandaniyal)
[Aditya Bharadwaj](https://adbharadwaj.github.io/)
[T. M. Murali](http://bioinformatics.cs.vt.edu/~murali/)

### Contact

[jahanwarsi@campus.tu-berlin.de](jahanwarsi@campus.tu-berlin.de)
[adb@vt.edu](adb@vt.edu)
[murali@cs.vt.edu](murali@cs.vt.edu)

**Comment by ayushiaks** [comment]
Hey! If no one is solving this issue, can I take it up?

**Comment by adbharadwaj** [comment]
Hi, @ayushiaks 
Thanks for showing interest in this project. We are currently asking all potential students to fix an issue on GraphSpace in order to showcase their familiarity with the above-mentioned technologies. This will also ensure that you already know how to contribute to an open-source project by the time GSoC actually starts.

We have a list of issues labeled with [good first issue](https://github.com/Murali-group/GraphSpace/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) to help potential first-time contributors. Incase you like to fix an issue, you can comment on the given issue and let us know.

You can also refer to the following list of [instructions for Potential GSoC students](https://github.com/Murali-group/GraphSpace/wiki/Instructions-for-Potential-GSoC-Students) to get started.

**Comment by adbharadwaj** [comment]
To all prospective applicants,

Please refer to [instructions for potential GSoC students](https://github.com/Murali-group/GraphSpace/wiki/Instructions-for-Potential-GSoC-Students) to get started.

**Comment by bruce-wayne99** [comment]
Hi @tmmurali , @adbharadwaj  I am highly interested in this project. I am proficient in Python, Django, HTML, JS, Jquery, CSS, Databases (SQL). I have good idea on basic socket programming (implemented proxy server, client-server connections as a part of my course). I have been going through tutorials for kafka and Melvin's blog regarding the implementation of **Real Time Notification System for GraphSpace**. I would also like to send my resume.

**Comment by adbharadwaj** [comment]
This project is open for GSoC 2019.

Please refer to [instructions for potential GSoC students](https://github.com/Murali-group/GraphSpace/wiki/Instructions-for-Potential-GSoC-Students) to get started.

**Comment by yash170106065** [comment]
hi can i work on this??

**Comment by khanspers** [comment]
Hi. Please contact the potential mentors directly (contact info above). If there is interest, this could be run as an NRNB Academy project.

**Comment by yash170106065** [comment]
thanks for replying I will start working...

**Comment by jahandaniyal** [comment]
> Hi,
> Thanks for showing interest in this project. We are currently asking all potential students to fix an issue on GraphSpace in order to showcase their familiarity with the above-mentioned technologies. This will also ensure that you already know how to contribute to an open-source project by the time GSoC actually starts.
> 
> We have a list of issues labeled with [good first issue](https://github.com/Murali-group/GraphSpace/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) to help potential first-time contributors. Incase you like to fix an issue, you can comment on the given issue and let us know.
> 
> You can also refer to the following list of [instructions for Potential GSoC students](https://github.com/Murali-group/GraphSpace/wiki/Instructions-for-Potential-GSoC-Students) to get started.

**Comment by yash170106065** [comment]
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '<frozen importlib._bootstrap>'
I don't know why this error is coming while running graphspace locally I followed every steps in readme.md but while running server it showing error can anyone help me on this issue ??

**Comment by adbharadwaj** [comment]
@yash170106065 Can we move the discussion about this error here. https://github.com/Murali-group/GraphSpace/issues/337

We also have a page where document common installation problems faced by new contributors. It might be helpful for you. https://github.com/Murali-group/GraphSpace/wiki/Common-installation-roadblocks-faced-by-new-contributors

**Comment by Anirbanbhk88** [comment]
Hi @jahandaniyal @adbharadwaj @tmmurali 
I would also like to say that I am interested in python development and want to learn more about open source development. I went through the Google Summer of Code(GSOC) website and this project seemed to be interesting to me. I was going through the Django development tutorials(**https://docs.djangoproject.com/en/3.0/intro/tutorial01/**) and Kafka tutorial(**https://medium.com/@patelharshali136/apache-kafka-tutorial-kafka-for-beginners-a58140cef84f**) about real-time messaging system and commit log for distributed system. So I am very much interested to work on this project.

My Name is Anirban Bhowmick and I am from India. I am currently a master's student in Intelligent Adaptive Systems at the University of Hamburg, Germany. I have currently completed my first semester. In my master's, I am studying different areas of Artificial Intelligence like neural networks, Machine Learning, Computer Vision, etc. So I have to use python in my day to day life.

I did my Bachelor of Engineering in Computer Science from India and I was working as a software developer after that. I have worked in 3 software development organizations in India and have gained an ample amount of experience in iOS and cross-platform app development, front-end development using javascript. I had always wanted to work in an open-source project to improve my programming skills. I came to know that GSOC provides such an opportunity to work with open source projects as a student. So I want to contribute to this project.

**Comment by jahandaniyal** [comment]
> Hi @jahandaniyal @adbharadwaj @tmmurali
> I would also like to say that I am interested in python development and want to learn more about open source development. I went through the Google Summer of Code(GSOC) website and this project seemed to be interesting to me. I was going through the Django development tutorials(**https://docs.djangoproject.com/en/3.0/intro/tutorial01/**) and Kafka tutorial(**https://medium.com/@patelharshali136/apache-kafka-tutorial-kafka-for-beginners-a58140cef84f**) about real-time messaging system and commit log for distributed system. So I am very much interested to work on this project.
> 
> My Name is Anirban Bhowmick and I am from India. I am currently a master's student in Intelligent Adaptive Systems at the University of Hamburg, Germany. I have currently completed my first semester. In my master's, I am studying different areas of Artificial Intelligence like neural networks, Machine Learning, Computer Vision, etc. So I have to use python in my day to day life.
> 
> I did my Bachelor of Engineering in Computer Science from India and I was working as a software developer after that. I have worked in 3 software development organizations in India and have gained an ample amount of experience in iOS and cross-platform app development, front-end development using javascript. I had always wanted to work in an open-source project to improve my programming skills. I came to know that GSOC provides such an opportunity to work with open source projects as a student. So I want to contribute to this project. Please let me know if I need to send my resume.

Thank you for showing interest in this project.
Please start working on a draft proposal, in case you have any questions feel free to ask me at `jahandaniyal@gmail.com`. 

Cheers,

**Comment by Anirbanbhk88** [comment]
Hi @jahandaniyal is it possible to have a discussion over call? Maybe we can discuss further about the project and proposal

**Comment by jahandaniyal** [comment]
> Hi @jahandaniyal is it possible to have a discussion over call? Maybe we can discuss further about the project and proposal

Hi @Anirbanbhk88 - We can have a discussion this Saturday at 5 PM.

**Comment by khanspers** [comment]
Active project for GSoC 2020, closing here.
