### ISSUE TITLE
GraphSpace: "Diffs" for graphs

### ISSUE THREAD

**Issue by adbharadwaj** [nrnb/GoogleSummerOfCode#113]
### Background
[GraphSpace](http://graphspace.org) is an easy-to-use web-based platform collaborating research groups can use for storing, interacting with, and sharing networks. A GraphSpace user can upload graphs through a REST API, import graphs created in Cytoscape, interact with graphs (view them, customize layouts, and save layouts), share graphs (create groups and add collaborators, share graphs among all members of a group or with the world), search graphs, and organize graphs using tags. GraphSpace has a comprehensive REST API that allows users to communicate programmatically with it. Overall, GraphSpace provides a rich set of user-friendly features to store and access graphs online. 

Going forward we also want to allow our users to easily compare their graphs (or graphs they have access to) with each other. Here are some example scenarios where allowing for comparisons would be useful:

- A user runs some algorithm which generates a network, uploads the network to GraphSpace and visually analyses it for a bit. They then perform some small tweaks to the algorithm or input data, run the algorithm again and upload the new graph. How did the network change? Specifically, which nodes and edges are different? 

- A user generates 50 sub-networks based off of the same underlying network, but with a different input or algorithm each time. What do all of the 50 networks have in common with each other? Are there nodes and edges that appear in all the networks, or some percentage (such as 75%) of the networks? 

### Goal

The overall goal of this project is to implement a Compare View interface which will allow users to easily compare graphs they have created (or have access to) with each other. The Compare View should showcase all information needed to determine what changed over a series of changes onto a single graph or between two or more different graphs. The Compare View interface should support two types of comparisons. 
    - Intersection - The interface should reveal elements which are common in both graphs. 
    - Difference - The interface should reveal elements which are present in one graph but not in other graphs.

This project has three sub-tasks.

1. **Compare two graphs**. Facilitate comparing two graphs A and B using a graphical interface in following ways: i) A intersection B, ii) A minus B, and iii) B minus A. This task will require UI updates to choose/select graphs to compare, an implementation of graph intersection and difference and a GUI to visualize the comparisons. 

2. **Compare three graphs**. Facilitate comparing three graphs A, B, and C using a graphical interface. The interface should allow users to customize the comparison query. For example: A intersection (B minus C) or A minus (B intersection C). 

3. **Compare two or more graphs**. The aim of this task is to extend the view to more than two graphs in general.

### Difficulty Level
Level 2

### Skills
List skills/technologies that the student should be familiar with. 

- Python, Cytoscape.js, HTML, JS, Jquery, CSS  (essential)
- Django (nice to have)

### Public Repository

https://github.com/Murali-group/GraphSpace/

### Gitter chat room
https://gitter.im/graphspace/gsoc2019students

### Potential Mentors
[Aditya Bharadwaj](https://adbharadwaj.github.io/)
[T. M. Murali](http://bioinformatics.cs.vt.edu/~murali/)

### Contact

[adb@vt.edu](adb@vt.edu)
[murali@cs.vt.edu](murali@cs.vt.edu)

**Comment by adbharadwaj** [comment]
To all prospective applicants,

Please refer to [instructions for potential GSoC students](https://github.com/Murali-group/GraphSpace/wiki/Instructions-for-Potential-GSoC-Students) to get started.

**Comment by lohani2280** [comment]
Hello mentors,
The GSoC orgs have been announced and NRNB has been selected as a mentor organisation. I am highly interested to work on this project. I have experience on working with HTML, CSS, Jquery, Django and Python. I have also contributed to several open source projects based on Python. 

I have read the instructions for potential GSoC students and have already send you my resume. 
As per our discussions, I will very soon send you some wireframes to explain both UI/UX for the project.
Thank You

**Comment by HitRam** [comment]
Hello mentors,

I am Hitesh, a junior at IIT Mandi, currently pursuing my Bachelors in Computer Science.

I would like to work on "Diffs for Graph" project as a part of GSoC'18.
For now, I have successfully set up GraphSpace locally and I am working on some issues. 

I have experience in HTML, CSS, Javascript and Python. I have done some tutorials on Django. As per discussions, I will think about the various aspects of project and come up with possible solutions.

Thank you.

**Comment by adbharadwaj** [comment]
This project is open for GSoC 2019.

Please refer to [instructions for potential GSoC students](https://github.com/Murali-group/GraphSpace/wiki/Instructions-for-Potential-GSoC-Students) to get started.

**Comment by jahandaniyal** [comment]
> This project is open for GSoC 2019.
> 
> Please refer to [instructions for potential GSoC students](https://github.com/Murali-group/GraphSpace/wiki/Instructions-for-Potential-GSoC-Students) to get started.

I wanted to suggest few things which might be very helpful for GSoC 2019 projects -
1. It would be nice to have Unittests/Integrations tests (perhaps use - [pytest](https://docs.pytest.org/en/latest/)) with every patch that any student submits. It's considered a good coding practice and also allows tracking of any student's progress. Also, I believe it does not affect the workload considerably, given the time-frame of GSoC. 
2. I generally use [Pylint](https://www.pylint.org/) to check for PEP8 coding convention. Pylint takes care of most of the coding convention issues and is very easy to use as well.
3. Similarly for Docstrings, I would suggest running [pydocstyle](https://github.com/PyCQA/pydocstyle) to check for common issues on top of the existing convention followed by GraphSpace. 

I think some or all of these will be very helpful for GSoC 2019 projects.

**Comment by lohani2280** [comment]
Hello mentors
I am interested to work on this project for GSoC 2019. I have a considerable experience on working with web development technologies. I have contributed to several open source projects(mostly python and JavaScript based) before and thus have exposure on working with large codebase. I have successfully installed GraphSpace on my PC. I have also solved a couple of issues on Graphspace. Please guide me on how to proceed further. 
Thank You

**Comment by khanspers** [comment]
Active GSoC 2019 project.
