### ISSUE TITLE
Automate fundamental biology workflows using new Cytoscape Automation

### ISSUE THREAD

**Issue by bdemchak** [nrnb/GoogleSummerOfCode#115]
### Background

[Cytoscape](http://www.cytoscape.org) is a **highly popular open source** bioinformatics software platform for visualizing, analyzing, and publishing graphs or networks representing molecular interactions, gene expression, other biological data. As a desktop application, all Cytoscape operations are performed manually using a mouse and keyboard. The new Cytoscape Automation feature set enables Python or R programmers to call Cytoscape to chain together a number of previously manual steps. 

To date, protocols describing important biological analyses have been published in terms of mouse clicks and keyboard strikes. Cytoscape Automation has the potential of greatly improving the productivity of network biologists by automating these laborious, hard-to-repeat workflows and showing the way for network biologists to write novel, reliably repeatable workflows. 

To **bootstrap this revolution**, we must translate existing manual protocols into Cytoscape Automation workflows. For example, the network exploration process documented in http://europepmc.org/articles/PMC4174321 can be coded in Python or R and then re-published for easy adoption and improvement by network biologists. Top priorities for translation include existing manual Mass Spectrometry, Functional Enrichment Analysis, and Cluster Analysis workflows.

During the translation process, we expect to discover and implement ways in which Cytoscape Automation can be generalized, focused or better optimized to enable real world biological value. 

Skills acquired during this project will be useful for a future in **bioinformatics, computer science or network biology**.
### Goal

Automate a number of existing network biology workflows using new Cytoscape Automation services, and add or upgrade Cytoscape Automation services to support new workflows. 

### Technologies
Writing workflows and upgrading calling libraries will involve Python and/or R.

Upgrading Cytoscape Automation features may require Java.
### Difficulty level: 2

Demonstrated experience Python and/or R coding is required. Basic Java coding is also required. Familiarity with biology concepts, networks and graphs is a plus.
### Potential mentors

Ruth Isserlin
### Contact

Barry Demchak (idekerlab.bdemchak@gmail.com)

**Comment by anu0012** [comment]
Hey @bdemchak , I am interested in this project and want to understand it more. Any suggesions?

**Comment by bdemchak** [comment]
Great ... glad to hear from you. Can you tell me more about yourself? What biology or programming experience do you have, and why this project may appeal to you? Thanks.

**Comment by anu0012** [comment]
Hello, @bdemchak Thanks for the reply.

I am currently a pre-final year post-graduate student. I have experience in Java and Python both. I am interested in data science and machine learning. I studied biology in high school and one course on Bio-Systems engineering in my college. I chose this project because I have some experience with Cytoscape and it will be easy for me to understand.

**Comment by bdemchak** [comment]
Hi, Anurag –

 

Thanks for the speedy reply.

 

I’m not so sure this will be easy, but I think it’ll be a challenge you might enjoy.

 

While it’s true that Cytoscape is a very large part of the project. Equally true is reading biology protocol (process) papers, understanding the workflow, and translating that into Cytoscape Automation function calls. You would get a huge leg up because the papers are already written to use Cytoscape. And so the job would be to determine which Cytoscape Automation functions achieve what the mouse/keyboard user would already be doing.

 

The specific Cytoscape feature at the core of this is CyREST, which exposes Cytoscape functions as REST calls. They can be leveraged by Python, R and Javascript programs. At this time, we’re rapidly improving our (already developed) Python and R libraries to support all CyREST functions. 

 

If you find that there are no CyREST functions for some operation called for in the protocol, you would be involved in adding the function to CyREST and then upgrading the Python and R libraries to match.

 

Does this interest you?? 

 

It sounds like a plausible fit with your experience, while giving you the opportunity to grow in biology and programming.

**Comment by anu0012** [comment]
Hello, @bdemchak that sounds interesting. So, for now, should I take a look at CyRest and workflows?

**Comment by khanspers** [comment]
Still viable, but mentor not available for GSoC 2019. May complete this outside GSoC. Closing for now.
