### ISSUE TITLE
Web application for interactive network visualization of gene list data  

### ISSUE THREAD

**Issue by jvwong** [nrnb/GoogleSummerOfCode#118]
### Background
Researchers interested in understanding the basis of disease often use powerful experiments that can generate a long list of candidate genes. However, it is not often clear how such genes relate to one another or to the disease of interest. Thus, researchers are in need of intuitive tools that help summarize and interpret this type of data.  
The team behind [Pathway Commons](https://github.com/PathwayCommons) are researchers and software developers (University of Toronto; Harvard University; Oregon Health and Science University) who are creating tools and resources that help researchers understand biological networks. A key goal is to develop web applications that allow users to analyze large amounts of experimental data so that it can be more easily navigated and interpreted by researchers who will use this information to suggest novel follow-up investigations.  
The developer on this project will be involved in client- and server-side web development. All of our web development projects are open source and help solve important computational biology problems that directly help researchers studying diseases. The candidate will work among and learn from five highly-experienced software developers as part of an international-level research team of over 25 people.

### Goal
The developer will implement additional services on top of an existing web application that enable an input list of genes to be summarized as an interactive network visualization. You will have a chance to learn Javascript (ES6+), React.js and Cytoscape.js along with other cutting edge tools that power the web.  

### Skills
Communication skills, willingness to learn, Javascript  (essential)
Strong problem and organizational skills (nice to have)

### Public Repository
https://github.com/PathwayCommons/app-ui

### Potential Mentors
Jeffrey Wong and Dylan Fong

### Contact
[Jeffrey V Wong](ccbr.software.jobs@gmail.com)

**Comment by kunal-mohta** [comment]
I have knowledge of JavaScript and have taken a look over Cytoscape.js. Although I don't have any experience in React.js, I am very much willing to learn it.
What can be my initial steps towards contributing to this project?

**Comment by sanket0211** [comment]
Hello everyone, 
My name is Sanket Shah. I am interested in taking up this issue. I have been working on web technologies for quite some time now. I have sound knowledge of c++, Python, Javascript, HTML, CSS, JQuery, Mysql. Can someone please guide me on how to start? 
Also can someone please elaborate on https://github.com/PathwayCommons/app-ui? 
Thank you. 

Regards, 
Sanket Shah

**Comment by sanket0211** [comment]
@jvwong Sir, 
Is Something similar to Graphspace expected?

**Comment by hsiaoyi0504** [comment]
Hi @jvwong and everyone,

I would like to explore the possibility to work on this one.

My name is Yi Hsiao, and I have experience mostly on Python and Javascript (JQuery, React.js).
I have a similar project for visualizing network before based on cytoscape.js, but not in quite modern javascript way. https://github.com/hsiaoyi0504/network_visualization_cases

But I think I can do this since I have some project using

Webpack and babel:
https://github.com/hsiaoyi0504/phylocanvas_i5k

React.js:
https://github.com/hsiaoyi0504/todo
https://github.com/hsiaoyi0504/blog

**Comment by odmoreno** [comment]
Hello @jvwong ,
I would like to work on this, I find it very interesting.
My name is Oscar Moreno, I have experience in javascript (React, React native, Redux, Vuejs), also experience in web development projects on the client and server side.
Could you tell me how to start in this project?

**Comment by khanspers** [comment]
Closing for GSoC 2019
