### ISSUE TITLE
Clustering algorithms

### ISSUE THREAD

**Issue by maxkfranz** [nrnb/GoogleSummerOfCode#12]
### Background
[Cytoscape.js](http://js.cytoscape.org/) is a JavaScript library for graph theory analysis and visualisation.  It supports many different graph types, such as simple graphs, multigraphs, compound graphs, etc.  Cytoscape.js is used in several apps to provide an interactive graph visualisation, and it has also been used for analysis in the terminal and on the server.

### Goal
Implement several [clustering](https://en.wikipedia.org/wiki/Cluster_analysis) algorithms for Cytoscape.js.

### Description
There are many types of [clustering algorithms](https://en.wikipedia.org/wiki/Category:Data_clustering_algorithms) in graph theory.  You would be implementing [extensions](http://js.cytoscape.org/#extensions) for the following algorithms using the existing implementations provided by the linked external libraries, creating nice Cytoscape.js APIs:

* Hierarchical : [clusterfck](https://harthur.github.io/clusterfck/)
* K-means :  [clusterfck](https://harthur.github.io/clusterfck/) or maybe [kmeans-js](https://github.com/hDeraj/kmeans-js)
* Affinity propagation : [affinity-propagation](https://github.com/juhis/affinity-propagation)
* MCL: [js-mcl](https://github.com/gokercebeci/js-mcl)

Depending on time constraints, a number of other algorithms could be implemented:

* K-mediod
* AutoSOME
* Cluster “Fuzzifier"
* Community Clustering (GLay)
* Fuzzy C-Means Clustering (https://github.com/jfinken/fuzzy-cmeans https://github.com/shingt/FuzzyCMeans https://github.com/imrealashu/kmean_fcm)
* Transitivity clustering
* SCPS (Spectral Clustering of Protein Sequences)

### Potential Mentors
Max Franz

### Contact
maxkfranz@gmail.com

**Comment by devkhan** [comment]
I want to learn more about this project. I am familiar with graph theory and some JS graph libraries but not much with Cytoscape.js. Can you please guide me towards some links, resources, etc.?

**Comment by maxkfranz** [comment]
@devkhan Everything is linked in the post.  If you have specific questions, let us know.

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
