### ISSUE TITLE
Integrating PathwayMapper into cBioPortal

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#123]
### Background
While the network visualization module in cBioPortal is a powerful exploration tool, most biologists are more comfortable with the kind of simplified, curated pathway diagrams that are featured in many manuscripts from The Cancer Genome Atlas (TCGA) . With the motivation of creating a platform that provides more intuitive pathway diagrams, yet supports these with rich data ‘decoration’ and analysis with access to data in cBioPortal, with attractive visualization, a tool named [PathwayMapper](https://github.com/iVis-at-Bilkent/pathway-mapper) [1] based on  [Cytoscape.js](http://js.cytoscape.org) was developed.

### Goal
PathwayMapper is a valuable tool for constructing pathways from scratch. One can use it as a viewer to overlay cancer genomics data on existing "template" pathways like those that appeared in TCGA papers though. The goal of this project is to integrate PathwayMapper into cBioPortal as a viewer either to replace the current Network view in the portal or as an alternative to it.

One needs to tie the genes of interest specified by the user to the available pathway templates using some kind of a ranking scheme and let the user make a decision from available pathways to show (along with the genomics data).

[1] I. Bahceci, U. Dogrusoz, K.C. La, Ö. Babur, J. Gao, N. Schultz, "PathwayMapper: a collaborative visual web editor for cancer pathways and genomic data", Bioinformatics, 33(14), pp. 2238-2240, 2017.

### Difficulty Level 3
The project requires strong programming skills both in front and back end.

### Skills
Good programming skills (essential)
Experience in web technologies (JavaScript, html, css), Java and visualization software (PathwayMapper is based on [Cytoscape.js](http://js.cytoscape.org)) (nice to have)

### Public Repository
https://github.com/iVis-at-Bilkent/pathway-mapper
https://github.com/cBioPortal/cbioportal

### Potential Mentors
S. Onur Sumer
J. Gao
U. Dogrusoz

### Contact
[S. Onur Sumer](mailto:onur@cbio.mskcc.org)

**Comment by khanspers** [comment]
GSoC 2018
