### ISSUE TITLE
Fast layout algorithm with compound support

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#124]
### Background
Both [desktop](https://cytoscape.org/) and [web](http://js.cytoscape.org/) versions of Cytoscape are highly popular and widely used graph libraries / tools for visualizing relational data in various domains including biology. Drawing of nested / compound structures is crucial in representing grouping or clustering structures inherent in an application for enabling more effective analysis and better complexity management of large graphs. 

### Goal
Currently existing layout algorithm [1] that supports such nesting relations, however, is not suitable for large networks. A new version of this algorithm will be implemented based on spectral graph drawing techniques. Another idea to speed up the algorithm might be computation in GPU.

[1] U. Dogrusoz et al., [A layout algorithm for undirected compound graphs](https://doi.org/10.1016/j.ins.2008.11.017), 2019

### Difficulty Level 3

The algorithm to be implemented involves linear algebra and parallelization.

### Skills
Solid background in data structures and algorithms
Excellent programming skills

Java, JavaScript (essential)
Knowledge of graph visualization and graph layout (nice to have)

### Public Repository
https://github.com/cytoscape/cytoscape.js
https://github.com/cytoscape/cytoscape

### Potential Mentors
Ugur Dogrusoz

### Contact
[Ugur Dogrusoz](mailto:ugurdogrusoz@gmail.com)

**Comment by bhaveshsunny** [comment]
@ugurdogrusoz Hi, I am Bhavesh a 4th-year student and GSoC 17 student. I am really excited to work on this project. Could you please list a couple of tasks for any of us prospective participants to work on? Thanks!

**Comment by ugurdogrusoz** [comment]
This was done independent of GSoC. So this should be closed.
