### ISSUE TITLE
Improved rendering of genetic designs using VisBOL

### ISSUE THREAD

**Issue by cjmyers** [nrnb/GoogleSummerOfCode#125]
### Background
VisBOL is a genetic design visualization tool written in Javascript that runs in the browser.  VisBOL can create this visualization by reading genetic design information encoding using the [Synthetic Biology Open Language (SBOL) data standard.](http://sbolstandard.org/data)  The rendering created utilizes glyphs and visualization conventions that are described in the [SBOL Visual standard](http://sbolstandard.org/visual).  VisBOL can be deployed as a standalone browser application such as at [VisBOL.org](http://visbol.org).  It can also be deployed as a frontend component within a larger project, such as [SynBioHub](https://synbiohub.org).

While the original version of VisBOL focused only on rendering DNA-level designs, recent updates have begun to add non-DNA components, such as small molecules, RNAs, and proteins, as well as the interactions between these components, in order to support SBOL Visual 2.  However, VisBOL suffers from some limitations.  For example, its linear display list based renderer cannot be used to render nested hierarchies of components, and its dependence on a browser environment means it cannot be used offline outside of the Web browser or as a RESTful API.

### Goal
The limitations present in VisBOL have already been addressed in the derivative [SynBioCAD](http://github.com/SynBioCAD/biocad) project.  However, SynBioCAD lacks recent updates to VisBOL such as the addition of SBOL Visual 2 glyphs.  The goals of this project would be (a) to integrate the latest updates to VisBOL into SynBioCAD, and (b) to update the VisBOL website to use SynBioCAD as its backend ("VisBOL 2.0"). A stretch goal will be to update the [SynBioHub](https://github.com/synbiohub) repository to use VisBOL 2.0 as its design renderer.

### Difficulty Level 2
This project has a medium level of difficulty due to the challenge of working with complex codebases and Web technology.

### Skills
Students need not have any experience with biology, but it would help to be proficient in any of JavaScript, TypeScript, or Node.js with some experience developing browser applications. Students will have some flexibility in choosing which aspects of the project they want to work on. Students will be required to familiarize themselves with core aspects of the [SBOL data specification](http://sbolstandard.org/wp-content/uploads/2016/06/SBOL-data-model-2.2.1.pdf) and [SBOL Visual specification](http://sbolstandard.org/wp-content/uploads/2017/04/SBOL-Visual-2.1.pdf).

### Public Repository
[visbol-js](https://github.com/VisBOL/visbol-js)
[SynBioCAD](https://github.com/SynBioCAD/biocad)

### Potential Mentors
Chris Myers, University of Utah, US ([myers@ece.utah.edu](myers@ece.utah.edu))
James McLaughlin, Newcastle University, UK ([james@mclgh.net](james@mclgh.net))

### Contact
For more information, please comment on this issue or contact [James McLaughlin](james@mclgh.net).

**Comment by 7vikpeculiar** [comment]
Hi
@cjmyers @zachzundel  @udp 
I am interested in working on this project, I am a **computational biology** student at IIIT Hyderabad, with 
good experience in building **JavaScript**-based browser applications

**Comment by cjmyers** [comment]
@7vikpeculiar that's great.  Please see if you clone the software and get it up and running.  Let us know if you have any questions.

**Comment by 7vikpeculiar** [comment]
@cjmyers 
I have been able to successfully setup the software and get it up

**Comment by cjmyers** [comment]
Great.  Please let us know if you have any questions as you begin to explore the codebase.

**Comment by gaurlakshya** [comment]
Hello @cjmyers 
i want to work on this project . i have good knowledge in the field of web development . I an a B.tech student of 2nd year (C.S.E. department). Can i work on this project ??

**Comment by cjmyers** [comment]
Sorry but GSoC has concluded for this year.  We will hopefully be doing this project or a similar one next year.  Please check back later.
