### ISSUE TITLE
Extending ModelPolisher to a universal model annotation tool

### ISSUE THREAD

**Issue by draeger** [nrnb/GoogleSummerOfCode#126]
### Background
The process of building models of biological systems continues to be a demanding effort. According to [Thiele and Palsson (2010)](https://dx.doi.org/10.1038/nprot.2009.203) the workflow leading to a functional model comprises almost 100 steps, many of which need to be manually executed and that are often highly error-prone. Any software that automates parts of this workflow therefore greatly speeds up the model building process and simultaneously contributes to increased model accuracy. In particular, model annotation plays a central role in model reuse and makes models comprehensible to third-parties, but often does not receive the necessary attention.

### Goal
In this project, a general model annotation tool should be created based on the [ModelPolisher](https://github.com/draeger-lab/ModelPolisher/) project. ModelPolisher was first created as an in-house model annotation tool for the [BiGG Models Knowledgebase](http://bigg.ucsd.edu), but it is potentially useful to update and automatically improve any model in [SBML](http://sbml.org) format. To this end, its algorithm needs to be changed and the project itself needs to be updated to be compliant with software development standards. Furthermore, [Neal et al. (2018)](
https://doi.org/10.1093/bib/bby087) recently suggested separating models from annotation by creating a glossary file that can then be embedded within a [COMBINE archive](https://combinearchive.org) file. ModelPolisher should support this as an optional feature.
Finally, ModelPolisher should be containerized to simplify the installation of its database backend.

### Difficulty Level 1
The described work does neither require designing complex algorithms nor is the underlying software difficult to understand. The aspects of systems biology covered in this project remain rather technical and are therefore well suited for interested computer science students as well as enthusiasts with joy in programming, database queries, and software design.

#### Essential
* Understanding of the concepts of object-oriented programing and Java&trade; (versions 8 or later)
* Knowledge about the foundations of SQL databases

#### Nice to have
* Experience with PostgreSQL
* Some understanding of XML
* Experience with Docker containerization
* Experience with Maven

### Public Repository
ModelPolisher: https://github.com/draeger-lab/ModelPolisher/

### Potential Mentors
Andreas Dräger (@draeger)
Thomas J. Zajac (@mephenor)

### Contact
[Andreas Dräger](mailto:draeger@informatik.uni-tuebingen.de)

**Comment by codekaust** [comment]
Hi @draeger 
I find this issue interesting, is it open for GSOC 2019?
Thank you.

**Comment by draeger** [comment]
Yes, it is. The best way of moving forward with your application would be to create a shared Google Document and to contact me via e-mail. I'll be happy to assist you in putting the proposal together.

**Comment by Fenil3510** [comment]
Hello, @draeger I find this project interesting and aligned with my skill set. I have working knowledge of Object Oriented Programming in Java and I'm comfortable with SQL, XML. I can pick up docker, maven before/during the project. I kindly request you to please provide me with some additional material so that I can get started with the project.

**Comment by draeger** [comment]
@Fenil3510: Absolutely, just contact me via e-mail (see my profile) and I'll be happy to share information material with you and to help you put a competitive proposal together.

**Comment by khanspers** [comment]
Active GSoC 2019 project.
