### ISSUE TITLE
Circular layout in Cytoscape.js

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#127]
### Background
[Cytoscape.js](http://js.cytoscape.org/) is a highly popular and widely used graph library for visualizing relational data in various domains including biology. Drawing of clustering structures is crucial in representing grouping structures inherent in an application (e.g. a biological network clustered using functionality or a social network grouped by geographical location) for enabling more effective analysis and better complexity management of graphs. 

### Goal
There is an existing layout algorithm [1] that supports such clustering or grouping structures but a JavaScript implementation packaged as a Cytoscape.js extension would be great to have. [Here](https://www.youtube.com/watch?v=SMDAQajK-E8) is how it works.

[1] U. Dogrusoz et al., "CiSE: A Circular Spring Embedder Layout Algorithm", IEEE Transactions on Visualization and Computer Graphics, 19(6), pp. 953-66, 2013. 

### Difficulty Level 2

An implementation of the algorithm is available in Java but automatic porting of the code seems impossible.

### Skills
Solid background in data structures and algorithms
Excellent programming skills

Java, JavaScript (essential)
Knowledge of graph visualization and graph layout (nice to have)

### Public Repository
https://github.com/cytoscape/cytoscape.js

### Potential Mentors
Ugur Dogrusoz

### Contact
[Ugur Dogrusoz](mailto:ugurdogrusoz@gmail.com)

**Comment by knightwayne** [comment]
Hello Sir,

I am Arnav Ishaan , a Computer Science undergraduate , competitive programmer and web developer from BIT Mesra, India. I love open source and web development, and am fairly comfortable with both front end and back end programming.
 
I have fair amount of experience in coding with C/C++ , Java and Python.
And I have made several front-end projects using HTML/CSS/Javascript. I have also created few data visualization projects using D3.js.
I have also taken a Biology course at college level, and received 'EX' (90+ out of 100) in it.

I am interested in looking up and solving this issue and #Issue 133, which are related closely to my area of interest. As I have been a competitive programmer and algorithm enthusiast, I am more than familiar with graphs and trees, mainly in language C/C++ and Java. Hence, I find myself suitable in solving this issue/issues, and would like to submit a proposal regarding it under the GSoC program.

I have already installed Cytoscape on my local machine(Ubuntu) and am going through the well written documentation of Cytoscape.js. I however have few questions.
 
1-> How can I contact you (over email or any other medium) to pitch in my ideas regarding this ?
2-> How can I access the journal/research paper mentioned in the sources ? The link mentioned in the YouTube video link goes to IEEE CS Digital Library. I have logged into it, but I can only access the Abstract and References of the article, but not the main contents. Please help, @ugurdogrusoz .
Meanwhile, I am going through the other article.

Thank you & have a nice day !

**Comment by ugurdogrusoz** [comment]
Please see my reply as email.

**Comment by knightwayne** [comment]
Yes sir, I am seeing the current algorithm written in Java cited in email, and am also reviewing the JavaScript implementation. Will get in touch soon.

**Comment by knightwayne** [comment]
@ugurdogrusoz Sir I have emailed you a few queries regarding this. Please see it.

**Comment by khanspers** [comment]
Active GSoC 2019 project.
