### ISSUE TITLE
Integrate CoSE layout into Cytoscape

### ISSUE THREAD

**Issue by maxkfranz** [nrnb/GoogleSummerOfCode#13]
### Background

[Cytoscape](http://cytoscape.org/) is an open source software platform for visualizing complex networks and integrating these with any type of attribute data. A lot of [Apps are available](http://apps.cytoscape.org/) for various kinds of problem domains, including bioinformatics, social network analysis, and semantic web.
### Goal

Implement the [CoSE layout](http://www.cs.bilkent.edu.tr/~ivis/cose.html) as a Cytoscape app.
### Description

Cytoscape provides compound node support, which means that nodes can be put inside other (i.e. parent) nodes.  However, Cytoscape does not yet have a layout that takes into account compound nodes.  The CoSE algorithm [1] is already supported by Cytoscape.js with [multiple](http://js.cytoscape.org/#layouts/cose) [implementations](https://github.com/cytoscape/cytoscape.js-cose-bilkent), and there is an implementation of the CoSE algorithm in Java.  This project would use the existing CoSE implementation in Java to provide a layout app for Cytoscape.

ChiLay project includes a Java implementation of CoSE:
                http://www.cs.bilkent.edu.tr/~ivis/chilay.html

The sources are in a Github project (master branch has the latest CoSE):
                https://github.com/iVis-at-Bilkent/chilay

Section titled “Local Usage” under Chapter 3 of the the Programmer’s Guide has sample code to make use of CoSE in a Java application:
http://www.cs.bilkent.edu.tr/~ivis/chilay/ChiLay-2.0-PG.pdf

[1] U. Dogrusoz, E. Giral, A. Cetintas, A. Civril, and E. Demir, "A Layout Algorithm For Undirected Compound Graphs", [Information Sciences, 179, pp. 980-994, 2009](http://www.sciencedirect.com/science/article/pii/S0020025508004799).
### Potential Mentors

[Ugur Dogrusoz](mailto:ugurdogrusoz@gmail.com), Christian Lopes, Mike Kucera
### Contact

ugurdogrusoz@gmail.com

**Comment by ugurdogrusoz** [comment]
Looks like this has already been done with Cytoscape 3.5
