### ISSUE TITLE
Integration of hierarchical molecular networks into the NDEx platform

### ISSUE THREAD

**Issue by ikuperst** [nrnb/GoogleSummerOfCode#130]
### Background
Pathways resources often contain comprehensive large-scale molecular networks with predefined layout and hierarchical structure, as in the case of the Atlas of Cancer Signalling Network, ACSN (https://acsn.curie.fr) a web-based resource of multi-scale biological maps depicting molecular processes in cancer cell and tumor microenvironment. The core of the Atlas is a set of interconnected cancer-related signaling and metabolic network maps. Molecular mechanisms are depicted on the maps at the level of biochemical interactions, forming a large seamless network. The maps of ACSN are organized in a hierarchical manner using semantic zooming feature and decomposed into functional modules with meaningful network layout. These features allow the user to visualize the seamless Atlas and individual maps from the collection at different levels of details description. 
Exposure and usage of such pathway resources highly dependent on navigation/analytical platforms. Currently ACSN is represented on NaviCell web-based platform, however in order to allow wider applications of the ACSN resource, it is essential to integrate it into various popular platforms and ensure correct representation using commonly-accepted formats and compatibility with the associated analytical tools.
NDEx is a public database of networks, a data repository in which networks can be published for broad dissemination as computable data, stored privately for use in collaboration, or used as a data source and integration hub in analysis pipelines. NDEx is also tightly integrated with Cytoscape, a widely used network analysis and visualization application. It is the core of the emerging “Cytoscape Cloud” ecosystem. NDEx has already been used to store hierarchies and to support applications using those networks, so collaboration with ACSN is well aligned with NDEx priorities.

With the aim of ACSN integration into the NDEx platform we suggest a collaborative project between the bioinformatics department in Institut Curie, Paris, France (https://sysbio.curie.fr) and the Ideker lab in UCSD, San Diego, USA (https://medschool.ucsd.edu/som/medicine/research/labs/ideker/Pages/default.aspx).

### Goal
The student will create software utilities to express the ACSN hierarchical networks in a form compatible with the emerging applications and datastructures in the Cytoscape Cyberinfrastructure. In particular, the ASCN hierarchical networks will be stored in NDEx and will use a schema compatible with the HiView hierarchical viewer. HiView is currently a mature prototype application in use within the Ideker lab at UCSD, the home of Cytoscape and NDEx. HiView scheduled for public release as an application tightly integrated with NDEx and Cytoscape in early summer of 2019, so the student’s work will have immediate application.

### Difficulty Level 2
The project is level 2 difficulty. It is challenging in that it will require an understanding of the hierarchical structure of ACSN networks and their schema and also the network schema required by the HiView application. However, the programming required to create the utility will use existing libraries for NDEx access by scripts and the student will have access to relevant tutorials and example code.

### Skills
Python or R programming at a scripting level (essential). 
Understanding of JSON data formats and their manipulation. Use of REST API access to web services. (nice to have).
Understanding of notion ‘Molecular network’, ‘Interaction network’, Pathways resource’, ‘Semantic zooming’, ‘Hierarchical networks’ (nice to have).

### Public Repository
https://acsn.curie.fr/
http://www.home.ndexbio.org/

### Potential Mentors
Dexter Pratt depratt@ucsd.edu
Rudolf  Pillich rpillich@ucsd.edu
Sompairac Nicolas Nicolas.Sompairac@curie.fr
Zinovyev Andrei Andrei.Zinovyev@curie.fr

### Contact
Inna Kuperstein inna.kuperstein@curie.fr
Dexter Pratt depratt@ucsd.edu

**Comment by vaniisgh** [comment]
Hi! 
I'm Vani  an Information Technology and Math major with a minor in Biology . I read though this issue as well as looked though the documentation for NDEx client , NiceCX as well as saw a few ACSN maps , I would love to work on this issue . How can I streamline my efforts for the same ? 

Regards ,
Vani 

I am comfortable using python and have a basic understanding of the JSON data format . 
I am familiar with biological networks too .

**Comment by lohani2280** [comment]
Hello Mentors,
I am Ayush Ranjan Lohani, from India, currently pursuing my Bachelors in the Department of Information Technology. I would like to work on this project as a part of GSoC'19. I have considerable experience on working with web development technologies. I have also contributed to several open source projects based on Python. Can you please guide me how to proceed with this project?

**Comment by ikuperst** [comment]
Hi Ayush, Thanks for your interest.
Please send your CV to the project contact persons:
Inna Kuperstein inna.kuperstein@curie.fr
Dexter Pratt depratt@ucsd.edu
Regards, Inna.
