### ISSUE TITLE
A new BridgeDb major release

### ISSUE THREAD

**Issue by egonw** [nrnb/GoogleSummerOfCode#132]
### Background
[BridgeDb](https://www.bridgedb.org/) is a platform used for identifier mapping in both WikiPathways as well as PathVisio (see also #27), and there is also a Cytoscape plugin, R package, etc. It provides the platform to link out to other databases, such as Ensembl, NCBI Gene, ChEBI, PubChem, ChemSpider, Uniprot, and Rhea. Because of its importance, it has been earmarked as [ELIXIR Recommended Interoperability Resources](https://www.elixir-europe.org/platforms/interoperability/rirs).

BridgeDb is written and Java and is urgently in need of both maintenance and extensions. Libraries it depends on need updating, or possible even replacement, when more performing solutions are available. BridgeDb also needs extension of its functionality, support for the concept of secondary identifiers in particular, but better output of metadata to meet [FAIR standards](https://www.nature.com/articles/sdata201618) is most welcome too. Importantly, it also needs to support Java releases more recent than Java 8, ideally all the way up to the current Java 11 release.

### Goal
The end results of this project is a new major release of BridgeDb, which new functionality and using the latest releases of used libraries and supporting Java 9 or later.

### Difficulty Level X
The difficulty level is a bit hard to guess, but assumed to be level 1 or 2. Easier parts are updates to the AP. The harder parts are updating the versions of libraries BridgeDb depends on, like Apache Derby.

### Skills
List skills/technologies that the student should be familiar with.  Also tag the issue with these.

* Programming Language: Java (required)
* Version control: Git (required)
* Maven (required)
* Resource Description Framework (welcome)
* OSGi (welcome)

### Public Repository
* Source code: https://github.com/bridgedb/BridgeDb
* Mailing list: https://groups.google.com/forum/#!forum/bridgedb-discuss

### Potential Mentors
Egon Willighagen

### Contact
[Egon Willighagen](https://github.com/egonw) (via this forum)

**Comment by The-Marvex** [comment]
@egonw I would like to work on this project. After going through the required resources, how should I proceed with the task?

**Comment by egonw** [comment]
A lot of information is given on this page: https://nrnb.org/gsoc.html That would be a good start.

**Comment by The-Marvex** [comment]
@egonw 
Hello Sir,
I did go through the required resources and the one you mentioned in the previous comment, how can I start contributing to the project and some good first issues' to start with.
Regards,
Manas

I am comfortable with Java and have an understanding of Git and Maven.

**Comment by egonw** [comment]
Dear @The-Marvex, my suggestion would to start compiling the software with Maven with Java8 and run the test suite (JUnit). Once you have that set up, and confirm that no tests are failing on your machine, the next step would be to compile with Java9 and see if that shows up any compile problems, or test fails.

You can report all issues you encounter in the issue tracker here: https://github.com/bridgedb/BridgeDb/issues

(BTW, I would also recommend start drafting a application proposal! The experience you build up with the above will help you write this application)

**Comment by The-Marvex** [comment]
Hello Sir, @egonw  
I was able to successfully compile the software with Maven and Java8 and the test suite ran without any issue. Whereas the software did not compile with Java11 and failed at ‘BridgeDB Webserver Core’. Changing the POM.xml file by adding some dependencies fixed that compilation issue with Java11 and it succesfully compiled with it as well.

**Comment by egonw** [comment]
Can you convert the changes you made into a clean pull request against the master branch, please?

**Comment by The-Marvex** [comment]
@egonw I have created the pull request for the same.

**Comment by The-Marvex** [comment]
@egonw Anything else I should work on in the meantime?

**Comment by egonw** [comment]
@The-Marvex, I would suggest start writing a proposal of what you like to do (based on the above idea) in a GSoC so that we can discuss that. See https://google.github.io/gsocguides/student/ for that and more.

**Comment by The-Marvex** [comment]
@egonw for communication, how should I contact you? By this forum, or your personal email? (I cannot find the email anywhere).

**Comment by egonw** [comment]
The BridgeDb mailing list will be our main communication channel. Later, practical work will go via issues and pull requests, I reckon.

**Comment by The-Marvex** [comment]
@egonw I having given my introduction in the BridgeDb Google Group (as given in the mailing list above) as you asked for and I have started working on the proposal as well.

**Comment by egonw** [comment]
I'm travelling this week, and can reply next week. Please continue working on your proposal and don't forget to figure out which downstream projects are using BridgeDb and what their needs are (the community).

BTW, it was announced yesterday that NRNB was selected this year for GSoC again :)

**Comment by The-Marvex** [comment]
@egonw Congratulations on getting selected again. I'll start working on that ASAP.

**Comment by The-Marvex** [comment]
@egonw I had some doubts regarding the project I have posted in the Google Group.

**Comment by khanspers** [comment]
Active GSoC 2019 project.
