### ISSUE TITLE
Update JSON scheme and implementation for SBML

### ISSUE THREAD

**Issue by matthiaskoenig** [nrnb/GoogleSummerOfCode#137]
### Background
The Systems Biology Markup Language (SBML) is the main language for representation and exchange of computational models in biology. JSON is the main data format of the web. Currently, many issues exist with the JSON representation of SBML used by tools like cobrapy, escher, ModelPolisher or the BiGG database. E.g.

https://github.com/opencobra/cobrapy/issues/706
https://github.com/opencobra/cobrapy/issues/720
https://github.com/opencobra/cobrapy/issues/736
https://github.com/opencobra/cobrapy/issues/856

The idea of this project is to update the JSON scheme to have a full coverage of features important for constraint-based methods, i.e. SBML core and the additional SBML packages fbc and groups. In addition existing issues should be solved (see above). The project will be implemented as part of cobrapy. 

* Annotation and meta-data support should be implemented
* Validation of JSON-SBML files should be performed
* Roundtripping SBML-JSON-SBML without information loss should be implemented
* JSON (SBML) scheme and scheme validation should be implemented

Having a full-featured JSON exchange format for SBML will improve the web-integration and exchange of SBML models. 

### Goal
Update the cobra(py) JSON scheme and implementation. Existing issues should be fixed and a complete coverage of SBML core and the SBML fbc and SBML groups package should be implemented. 

### Difficulty Level X
The level is a basic bioinformatic project focusing on easy-to-medium skills, i.e., python and JSON.

### Skills

JSON, Python (essential)
SBML (nice to have)

### Public Repository
https://github.com/opencobra/cobrapy
https://escher.readthedocs.io/en/latest/index.html
http://bigg.ucsd.edu/models

### Potential Mentors
Matthias König

### Contact
[Matthias König](mailto:konigmatt@googlemail.com)

**Comment by Hemant27031999** [comment]
Hi @matthiaskoenig , I'm Hemant from the Indian Institute of Technology, Roorkee, India. I find this issue quite interesting. I have gone through the listed issues of cobrapy and have got an insight of them. I have dig some of them quite deeper also, understanding where the issue actually points by discussing them with the members of cobrapy. If NRNB made it possible to GSoC this time, I would like to work on it. 

But as there is some time left until the final GSoC list, I was thinking to have an understanding of SBML core and SBML packages which are a part of this project. Can you help me a little about where should I start with and what else can I do before that?
Thanks.

**Comment by Hemant27031999** [comment]
@matthiaskoenig , is this issue open for GSoC 2020?

**Comment by matthiaskoenig** [comment]
@Hemant27031999 Yes, I answered you via email.

**Comment by dukkee** [comment]
@matthiaskoenig Hello. Is this issue still open and without any interns?

**Comment by matthiaskoenig** [comment]
@dukkee We already have a student who is working on this issue and wrote a very good proposal. I would look for another issue

**Comment by khanspers** [comment]
Active project for GSoC 2020, closing here.
