### ISSUE TITLE
Experiment data overlay in Newt

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#138]
[Newt](http://newteditor.org) is a [Cytoscape.js](http://js.cytoscape.org/) based viewer and editor for biological maps in Systems Biology Graphical Notation (SBGN) notation [1] to create biological maps from scratch or edit existing ones. It's been built (with partial support from GSoC) around an editing library named [ChiSE](https://github.com/iVis-at-Bilkent/chise.js), which in turn was based on a viewer library named [SBGNViz](https://github.com/iVis-at-Bilkent/sbgnviz.js) [2]. The tool uses a number of new [Cytoscape.js extensions](http://js.cytoscape.org/#extensions) built for various editing capabilities such as grid-guidelines, context-menus, and expand-collapse.

[1] M. Sari, I. Bahceci, U. Dogrusoz, S.O. Sumer, B.A. Aksoy, O. Babur, E. Demir, "SBGNViz: a tool for visualization and complexity management of SBGN process description maps", PLoS ONE, 10(6), e0128985, 2015.
 
[2] N. Le Novère et al., "The Systems Biology Graphical Notation", Nature Biotechnology, 27, pp. 735-741, 2009.

### Goal
With this project, we aim to design and implement experiment data overlay support for the Newt editor. We will probably use a simple tab-delimited text format to upload experiment data from. Multiple data sets should be supported as well. The user should be able to customize what is to be shown and how.

### Difficulty Level 2
The project can be considered a fairly difficult one since it involves work in back end and front end programming.

### Skills
HTML, JavaScript, Cytoscape.js and its extension structure (essential)
SBGNViz and ChiSE (nice to have)

### Public Repository
[Newt GitHub repository](https://github.com/iVis-at-Bilkent/newt)

### Potential Mentors
[Ugur Dogrusoz](https://github.com/ugurdogrusoz)

### Contact
[Ugur Dogrusoz](http://www.cs.bilkent.edu.tr/~ugur/)

**Comment by adad20** [comment]
Hello, I am interested in this project. Can I take this project?

**Comment by ugurdogrusoz** [comment]
@adad20 if you qualify (and NRNB is selected as an organization to participate this yera), you may write a proposal on this or other project ideas. Procedure is detailed [here](https://nrnb.org/gsoc.html) and in GSoC web pages.

**Comment by adad20** [comment]
okay

**Comment by adad20** [comment]
@ugurdogrusoz Is there anything to get started before the proposal period. I want to know more about the organisation and project.

**Comment by ugurdogrusoz** [comment]
@adad20 Looks like we will remove this from project ideas since there's been a lot of progress on this module already, sorry.

**Comment by adad20** [comment]
@ugurdogrusoz No problem I will look at the other projects.
