### ISSUE TITLE
Implement more graph algorithms for Cytoscape.js

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#139]
### Background
[Cytoscape.js](https://js.cytoscape.org/) is a popular graph analysis and visualization library with many useful [extension](https://js.cytoscape.org/#extensions).

### Goal
The goal of this project is to implement additional graph algorithms to construct a graph of interest from a set of nodes of interest. These is especially useful for a focused analysis of large graphs.

Among the algorithms to be implemented [1]:
- common targets (downstream) / regulators (upstream)
- shortest plus k distance paths
- paths between specified nodes with length no more than k

[1] U. Dogrusoz, A. Cetintas, E. Demir, and O. Babur, "Algorithms for Effective Querying of Compound Graph-Based Pathway Databases", BMC Bioinformatics, 10:376, 2009.

### Difficulty Level 3
This is a rather difficult project as it not only requires a good knowledge of Cytoscape.js and its extensions but also understanding graph algorithms and their implementations.

### Skills
JavaScript, Cytoscape.js and its extension structure (essential)
Experience with graph algorithms (nice to have)

### Public Repository
[Cytoscape.js](https://github.com/cytoscape/cytoscape.js)

### Potential Mentors
[Ugur Dogrusoz](https://github.com/ugurdogrusoz)

### Contact
[Ugur Dogrusoz](http://www.cs.bilkent.edu.tr/~ugur/)

**Comment by Harshrai3112** [comment]
Hello @ugurdogrusoz 
I would like to on this project as i have good knowledge of graph algorithms and also implement many graph algorithms.But i have just started learning cytoscape.js.
So can you guide me how can i move forward.

**Comment by ugurdogrusoz** [comment]
@Harshrai3112 You could start by doing the Cytsocape.js tutorials. Then looking into the implementation of graph algorithms such as centrality measures in Cytocape.js core. Finally read the mentioned paper in this issue.

**Comment by Harshrai3112** [comment]
> @Harshrai3112 You could start by doing the Cytsocape.js tutorials. Then looking into the implementation of graph algorithms such as centrality measures in Cytocape.js core. Finally read the mentioned paper in this issue.
Thank you for information.

**Comment by mnv936** [comment]
Hi @ugurdogrusoz 
I have shared my proposal with you via email, can you please review it.
