### ISSUE TITLE
Adjacency Matrix Renderer

### ISSUE THREAD

**Issue by maxkfranz** [nrnb/GoogleSummerOfCode#14]
### Background

[Cytoscape](http://cytoscape.org/) is an open source software platform for visualizing complex networks and integrating these with any type of attribute data. A lot of [Apps are available](http://apps.cytoscape.org/) for various kinds of problem domains, including bioinformatics, social network analysis, and semantic web.
### Goal

Implement an adjacency matrix renderer as a Cytoscape app.
### Description

Cytoscape has a modular architecture, and so different renderers can be used to show the graph.  For example, the [Cy3D app](http://apps.cytoscape.org/apps/cy3d) is a 3D renderer.  This project would involve the implementation of an [adjacency matrix](https://en.wikipedia.org/wiki/Adjacency_matrix) renderer for Cytoscape as an app.  It would be responsible for drawing the nodes and edges in the graph and for handling events and gestures, such as zoom, pan, click.
### Potential Mentors

Christian Lopes, Mike Kucera
### Contact

chrtannus@gmail.com

**Comment by floraliu1011** [comment]
Hi mentors,

I'm a second year computer science student at university of Toronto and I'm really interested in this project. I have prior experience in Java, Python and R. Could you kindly refer me to some resources that can help me get started? 

thanks,
Flora

**Comment by maxkfranz** [comment]
@AlexanderPico Would you please re-assign this to @chrtannus or @mikekucera.  I think Christian and I wrote up this project on my machine using my account, but this isn't something I would be able to contribute to as effectively as Christian or Mike.

**Comment by AlexanderPico** [comment]
Sure. Will assign to @chrtannus... once he accepts invitation this NRNB team list. If he's not available, then we'll close the issue for this summer.

**Comment by khanspers** [comment]
Closing for GSoC 2019
