### ISSUE TITLE
Simulation of systems biology models in Java: support for new features

### ISSUE THREAD

**Issue by draeger** [nrnb/GoogleSummerOfCode#141]
### Background
The [Systems Biology Simulation Core Library (SBSCL)](https://github.com/cogsys-tuebingen/SBSCL) is a collection of classes for simulating computational systems biology models in a Java&trade; program. SBSCL already ships solvers for both, a constraint-based simulation framework (steady-state flux balance analysis) as well as numerical solvers for systems biology models that are interpreted as ordinary differential equation systems.

Its modular design makes SBSCL very flexible so that it can work with many standard file formats for model encoding. Until now, its primary focus is on the format [SBML](http://sbml.org). In addition, SBSCL interprets files in the simulation experiment description format [SED-ML](https://sed-ml.github.io) that describe how models are to be simulated. The typical workflow starts with reading a SED-ML file. This file gives the information, which SBML model to load using the library [JSBML](https://github.com/sbmlteam/jsbml). The simulation library will then initialize the model and start the solver. Afterwards, the results will be post-processed and be plotted using the library [JFreeChard](http://www.jfree.org/jfreechart/). Hence, all steps will follow the instructions in the SED-ML file. Recently, support for [COMBINE Archive](https://combinearchive.org/index/) files has been added to bundle SED-ML and SBML files in a ZIP archive.

### Goals
* Implement new features of [SBML Level 3 Version 2](https://www.degruyter.com/downloadpdf/j/jib.2019.16.issue-2/jib-2019-0021/jib-2019-0021.pdf)
* Improve support for hierarchically structured models (i.e., SBML models with [comp](http://co.mbine.org/specifications/sbml.level-3.version-1.comp.version-1.release-3.pdf) extension)
* Test SBSCL against the [Systems Biology Test Suite](https://github.com/sbmlteam/sbml-test-suite)
* Migrate the project's backend for [SED-ML](https://sed-ml.github.io) from the Java library [jLibSEDML](http://jlibsedml.sourceforge.net/jlibsedml/index.html) to the newer implementation [JSEDML](https://github.com/SED-ML/JSEDML) (see related project https://github.com/nrnb/GoogleSummerOfCode/issues/101).

### Difficulty Level 2
This project will require gaining an understanding of the two standards SED-ML and SBML with most focus on SBML Level 3 Version 2.

### Skills
Java&trade; programming skills are required. It can be helpful to have Python knowledge for comparing SBSCL to the related third-party software of similar scope.

Java&trade; (essential)
Python (nice to have)

### Public Repository
https://github.com/draeger-lab/SBSCL

### Potential Mentors
[Andreas Dräger](https://github.com/draeger)

### Contact
[Andreas Dräger](draeger@informatik.uni-tuebingen.de)

**Comment by hemilpanchiwala** [comment]
Hi @draeger, 
I find this issue interesting and would like to work on it. After going through the required resources, how should I proceed with the task?
Also, what is the preferred method of contact?
Thank You.

**Comment by draeger** [comment]
Dear @hemilpanchiwala! Thanks for your interest in this topic! Right now you can already look at the documentation of the project at https://draeger-lab.github.io/SBSCL/, the [API specification](https://draeger-lab.github.io/SBSCL/apidocs/overview-summary.html) in particular. When Google announces the funded organizations on February 20, we should get in touch again - if NRNB is successful, we should soon start drafting a proposal. Please contact me then again and I will explain next steps to you.

**Comment by hemilpanchiwala** [comment]
Hi @draeger,
I had a little doubt regarding the tasks to be done through this project. In the goals, it is mentioned to change the project's backend for SED-ML from jLibSEDML to JSEDML. But I didn't find the implementation of JSEDML as it is one of the undone projects. So, do this project targets the implementation of JSEDML also?

And, I have also sent you the mail regarding my current status for this project. Please review it and guide me for further steps.

Thank You.

**Comment by draeger** [comment]
@hemilpanchiwala I am answering you via e-mail direct.

**Comment by khanspers** [comment]
Active project for GSoC 2020, closing here.
