### ISSUE TITLE
Develop/Update R Shiny Interface for SBGN Diagrams using the Javascript SBGNViz Library

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#143]
### Background
The Systems Biology Graphical Notation (SBGN) is a widely used notation for visualizing biological networks (https://dx.doi.org/10.1038/nbt.1558). The reach of SBGN could be increased by making it easier to use from commonly used bioinformatics programming languages such as R. A basic interface has been developed: https://github.com/cannin/sbgnvizShiny but needs improvement.  

### Goal
The goal to improve the sbgnvizShiny package. The package has issues with rendering some SBGN components that the base https://github.com/iVis-at-Bilkent/sbgnviz.js has no issue with, for example SBGN units of information The goal of the project is to fix the issues and expand the capabilities of the R package allowing users more facility to interact with the Javascript rendered diagrams. 

### Difficulty Level 2
Difficulty level 2 since it requires knowledge of multiple programming languages. 

### Skills
* R 
* Javascript 

### Public Repository
* https://github.com/cannin/sbgnvizShiny
* https://github.com/iVis-at-Bilkent/sbgnviz.js

### Potential Mentors
Augustin Luna

### Contact
[Augustin Luna](aluna@jimmy.harvard.edu)

**Comment by aniket328** [comment]
Hello @cannin, I will like to work on this project. I think that my current skills meet the project's requirements. Please help me getting forward to this.

**Comment by Adarshsinghparihar** [comment]
Hello @cannin,
I am really interested in the project and would like to work on it as I have good knowledge of Javascript and R.It would be great if you could help me proceed with this.

**Comment by cannin** [comment]
@aniket328 @Adarshsinghparihar if still interested please send me an email with a list of your skills and pointers to past experiences. Thanks.

**Comment by Adarshsinghparihar** [comment]
@cannin I have mailed you the same. Please have a look.

**Comment by romilsiddhapura** [comment]
Is this issue still open..? Sorry for late but I am interested in this project. Can @cannin help me proceed with this?

**Comment by cannin** [comment]
@romilsiddhapura the issue is still open please submit a proposal if interested; the deadline is tomorrow.

**Comment by 12VISHESH** [comment]
hey @cannin 
I hope you are doing well and safe!
I wanted to know this issue is still open? this project meets my skills.
