### ISSUE TITLE
Develop a Web Service for Rendering SBGN Diagrams 

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#144]
### Background
The Systems Biology Graphical Notation (SBGN) is a widely used notation for visualizing biological networks (https://dx.doi.org/10.1038/nbt.1558). The reach of SBGN could be increased by making it easier if SBGN diagrams can be quickly be rendered through a web service. 

### Goal
The goal to develop a web service that can generate SBGN diagrams given SBGNML (https://www.ncbi.nlm.nih.gov/pubmed/22581176) content. The web service would be a Javascript-based service using https://github.com/iVis-at-Bilkent/sbgnviz.js for rendering. This basic web service would be extended to support the rendering of user-provided colors for SBGN glyphs and the multiple output graphical formats from sbgnviz.js. 

### Difficulty Level 1
Difficulty level 1 because the goal is to use existing components and only Javascript. Difficulties could arise if the rendering requires components not typically a part of web services that simply produce text outputs. 

### Skills
* Javascript 

### Public Repository
* https://github.com/iVis-at-Bilkent/sbgnviz.js

### Potential Mentors
Augustin Luna
Ugur Dogrusoz

### Contact
[Augustin Luna (aluna AT jimmy.harvard.edu)](mailto:aluna@jimmy.harvard.edu)

**Comment by adad20** [comment]
Hello @cannin,
I found this project interesting and want to work on it. I have previous experience with web development this project suits me and will improve my skills in various aspects. 
Can you guide what should I do next in order to be on the same page?

**Comment by cannin** [comment]
Thanks for the interest. @adad20 send information on your coding skills/prior experiences to the email address in the project description.

**Comment by Harshrai3112** [comment]
Hello @cannin 
I would like to work on this project as i have good knowledge of Javascript  and its framework nodejs and Angular. I had made web service in  my previous projects also.

**Comment by adad20** [comment]
@cannin  I have sent the mail kindly check.
Regards!!

**Comment by onsah** [comment]
Hi @cannin 
I am interested in this project and would like to work on it. I have previous web experiences with html+javascript including ES6 standard. I think this project would help me to improve my skills. Can you show me some pointers to start working on this project?

**Comment by Harshrai3112** [comment]
> @cannin I have sent the mail kindly check.
> Regards!!

I didn't received any mail.
my  email id :- harshrai3112@gmail.com
Thank you.

**Comment by mehumaija** [comment]
hello! I'm a little bit familiar with JavaScript, have done one project using it for data processing on a web page. What should I learn more about JavaScript to be able to do rendering?

Thanks!

**Comment by cannin** [comment]
@Harshrai3112, @onsah, @mehumaija if still interested and need feedback related to your proposal send me an email, I'll try to respond Monday

**Comment by Jain-Sanchit** [comment]
Sir , I am familiar with javascript and would like to work on this project for gsoc , can you tell me how should i proceed ?

**Comment by cannin** [comment]
@Jain-Sanchit send me an email and i'll try to give you feedback on your proposal.

**Comment by onsah** [comment]
@cannin Hi I have sent an email in the last Sunday. I would like to get a response if possible. Thanks!

**Comment by cannin** [comment]
@onsah resent, check spam in case

**Comment by TheCelestial25** [comment]
@cannin I know I am very late but would still like to send a proposal if you permit me.

**Comment by cannin** [comment]
@TheCelestial25 go ahead and submit; deadline tomorrow

**Comment by TheCelestial25** [comment]
@cannin Thank you so much. Submitted :)

**Comment by aniket328** [comment]
@cannin  I would love to contribute to this project now. Is it still available after GSoC?
