### ISSUE TITLE
Develop a Slack Bot to Improve the Results of Text Extraction of Biomedical Interactions

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#145]
### Background
Natural language processing of the scientific literature and the automated assembly of this information by the INDRA system (http://github.com/sorgerlab/indra.git) is prone to errors. The improvement of the algorithms and models responsible for these tasks can greatly benefit from expert feedback.

### Goal
The goal is to implement a bot plugin for the Slack workspace
of the Harvard Program in Therapeutic Sciences. The bot will access a list of questions on which expert feedback is required and send these questions to designated channels or users on Slack. It then handles answers (typically simple multiple choice) and stores them in a database for further analysis.

### Difficulty Level 1 
Skills necessary for this project are widely applicable to many other projects.

### Skills
* Python
* SQL

### Public Repository
http://github.com/sorgerlab/indra.git

### Potential Mentors
* Benjamin Gyori (@bgyori)
* John Bachman (@johnbachman)
* Augustin Luna (@cannin)

### Contact
[Augustin Luna](mailto:aluna@jimmy.harvard.edu)
[Benjamin Gyori](mailto:benjamin_gyori@hms.harvard.edu)

**Comment by rahul799** [comment]
@cannin, I will like to work on this project. I have a query like, who will provide the questions? Do I need to contact Augustin or Benjamin for that?

**Comment by YashKK2198** [comment]
@cannin I am Yash Kulkarni. I am a final year computer engineering undergraduate student fro VIT Pune, India. I am interested in working on this project.

**Comment by johnbachman** [comment]
@rahul799 @YashKK2198 Thank you both for your interest! The questions will actually be computer-generated--that is, a back-end system that we have developed will make (possibly uncertain or incorrect) inferences and then submit these questions to the Slack interface for expert human curation and validation. Feel free to ask any other questions in this thread and @bgyori and I will do our best to address them.

**Comment by rahul799** [comment]
@johnbachman @bgyori I got the answer, What could be my next step? Should I start drafting my GSOC proposal?

**Comment by YashKK2198** [comment]
@johnbachman Thank you for your response. I have downloaded the git files. Can you please let me know what are the next steps to be followed?

**Comment by bgyori** [comment]
Hi All, thank you for your interest! We have decided not to pursue this project for this round of GSOC. However, we would like to point you to https://github.com/nrnb/GoogleSummerOfCode/issues/142 which relies on some of the same technologies, as an exciting alternative.
