### ISSUE TITLE
Adding Network Analysis and Visualisation Features to ABoiTrans

### ISSUE THREAD

**Issue by MoHelmy** [nrnb/GoogleSummerOfCode#146]
### Background
[ABioTrans](https://www.frontiersin.org/articles/10.3389/fgene.2019.00499/full) is a bio-statistical/informatics tool, ABioTrans, developed in R for gene expression analysis. The tool allows the user to directly read RNA-Seq data files deposited in the Gene Expression Omnibus or GEO database. provides easy options for multiple statistical distribution fitting, Pearson and Spearman rank correlations, PCA, k-means and hierarchical clustering, differential expression (DE) analysis, Shannon entropy and noise (square of the coefficient of variation) analyses, as well as Gene ontology classifications.

### Focus
This project aims to develop the 2nd version of ABioTrans. ABioTrans v2 will be web-based and will provide extensive analysis options to the gene expression analysis results such as pathway enrichment analysis, gene function analysis as well as publication-ready visualization options including network visualization using Cytoscape.JS

### Goals
1- Create a web-based version of ABioTrans by transforming the current R/Shiny program to operate on the web. 
2- Adding several network data analysis and visualization functions by integrating existing R packages into the web version of ABioTrans, such as [UniProtR](https://cran.r-project.org/web/packages/UniprotR/index.html).
3- Integrating [Cytoscape.JS](Cytoscape.JS) for network visualization. 

### Coding Skills
R programming,  Shiny, JavaScript, HTML/CSS

### Acceptance Criteria
Students interested in working in this project will be asked to do an evaluation task that will be used for assessing their fitness to the project. Please email your CV and a letter of motivation to the mentors' email addresses (bellow).

### Mentors
Mohamed Helmy [mohamed_helmy@biotrans.a-star.edu.sg]
Kumar Selvarajoo [kumar_selvarajoo@biotrans.a-star.edu.sg]
 
### About BioTrans Bioinformatics and Systems Biology Group
We are part of The Biotransformation Innovation Platform ([BioTrans](https://www.a-star.edu.sg/biotrans)), Agency for Science, Technology and Research ([A*STAR](https://www.a-star.edu.sg/)), Singapore. Our group is strongly engaged in biological network research and its applications in metabolic engineering. Feel free to have a look at [our home page](https://www.a-star.edu.sg/biotrans) for more details on the lab research areas.

### References
1- ABioTrans: https://doi.org/10.3389/fgene.2019.00499
2- UniProtR: https://doi:10.1016/j.jprot.2019.103613

**Comment by rahul799** [comment]
@MoHelmy I found this project very interesting & will like to do this. Can you please tell me about the evaluation task?

**Comment by MoHelmy** [comment]
Hi @rahul799 Thanks for being interested in our project. Please send your CV to the 2 email addresses provided above and I will respond to you ASAP.

**Comment by rahul799** [comment]
Hello @MoHelmy, I just wanted to inform you that I have sent the mail.

**Comment by MoHelmy** [comment]
@rahul799 Thanks but please resend. There was a typo in the email address. I fixed it and sorry about that. Please send to mohamed_helmy@biotrans.a-star.edu.sg and kumar_selvarajoo@biotrans.a-star.edu.sg

**Comment by rahul799** [comment]
@MoHelmy no issues, I have sent the mail again. Please check it & let me know if you won't get it.

**Comment by MoHelmy** [comment]
Thanks again @rahul799, got it and will come back to you.

**Comment by 12VISHESH** [comment]
Hey, @MoHelmy, I found this project is very interesting in data visualization and analysis. I have worked on R shiny app for my project. and also I have worked on data analysis and visualization. 
currently, I am looking forward to contributing to open source.
So suggest to me, what I can do further in this project!

**Comment by MoHelmy** [comment]
@12VISHESH Thanks for your interest in our project, please send your CV and a motivation letter to mohamed_helmy@biotrans.a-star.edu.sg and kumar_selvarajoo@biotrans.a-star.edu.sg and we will come back to you ASAP.

**Comment by 12VISHESH** [comment]
hello, @MoHelmy I have sent the mail, kindly check the mail .
thanks, 
happy coding

**Comment by 12VISHESH** [comment]
Hey @MoHelmy I have sent you all documents , kindly have a look 
thanks,
happy coding

**Comment by MoHelmy** [comment]
Thanks @12VISHESH, I got them and I will be in touch soon.

**Comment by rahul799** [comment]
@MoHelmy I have sent a mail regarding the completion of task. Please have a look.

**Comment by 12VISHESH** [comment]
sure @MoHelmy, I am waiting for your further instruction.
Is there is any task till yet in this project?
thanks and regards 
happy coding

**Comment by khanspers** [comment]
Hi @rahul799 and @12VISHESH , thanks for your interest in this project and NRNB. Please note that we don't know yet if NRNB will be in GSoC 2020, as Google has not announced accepted organizations for this year yet. If we are accepted, you will get further information on the full application process.

**Comment by 12VISHESH** [comment]
@khanspers  thanks for informing me. I hope this year also NRNB comes and completes its projects and through that, I can learn lots of things in open source.
thanks and regards 
happy coding

**Comment by khanspers** [comment]
Active project for GSoC 2020, closing here.
