### ISSUE TITLE
Develop GUI for ImageJ groovy script calling VCell API

### ISSUE THREAD

**Issue by vcellmike** [nrnb/GoogleSummerOfCode#148]
### Background
VCell (http://vcell.org) is an open source software platform that can model and simulate reaction-diffusion systems in geometries derived from 3D experimental microscopy images; it can also utilize experimentally derived molecular concentrations and cellular localizations. It is used by scientists around the world to create quantitative hypotheses of cellular functions whose predictions can be directly compared to experimental results. Fiji/ImageJ (https://imagej.net/) is arguably the most widely used software tool for the analysis of microscope images of cells. Both software environments will gain enhanced functionality by creating an architecture to couple these tools.  Bridging these software tools will:
1. Enable VCell users to analyze and visualize their dynamic multidimensional, multivariable simulation results.
2. Enable ImageJ users to analyze live cell microscopy experiments to quantitatively assess their fit to mechanistic reaction-diffusion models and to extract quantitative parameters such as rate constants and in vivo concentrations.
https://imagej.net/Plugins
https://imagej.net/Writing_plugins
https://imagej.net/Development

### Goal
We have created a service for VCell users that allows Fiji/ImageJ scripting to directly access the VCell client.  We have to expand this service into a series of user-friendly plugins for ImageJ that will automate processing and analyzing cell imaging simulation experiments, including 1) entering the appropriate images to create a geometry; 2) setting initial conditions for the simulation, 3) running multiple simulations with varying parameter sets, 4) visualizing and comparing simulation results to the original experimental image set. 

### Difficulty Level 2 (1 easiest and 3 hardest).

Prior experience with ImageJ, image processing and modeling app could be useful. There is a lot of help on how to create ImageJ plugins, less about interaction with VCell.

### Skills
Java, Groovy (essential)
ImageJ, modeling (nice to have)

### Public Repository
https://github.com/virtualcell/vcell/tree/master/vcell-imagej-helper

### Potential Mentors
Michael Blinov
Frank Morgan
Ann Cowan

### Contact
Michael Blinov(mailto:blinov@uchc.edu)

**Comment by JuanLeee** [comment]
Hello @vcellmike, I mailed you recently and I am interested in this project. I was wondering if this would be feasible for someone with not much experience with open source coding or coding outside of small projects and classwork.

**Comment by godslayer201** [comment]
Hey @vcellmike 

I'm interested to work on this. I've worked on GUI apps prior(in Python),but I can pick Groovy up. 

Looking over the repo and I'm looking at the issues. I would communicate over email if I have any questions.
Thank you!

**Comment by vcellmike** [comment]
Hi @godslayer201, nice to hear from you. Feel free to ask questions regarding the project.

**Comment by khanspers** [comment]
This is an active GSoC 2021 project. The issue will be closed for the duration of GSoC since it is no longer available to other students.
