### ISSUE TITLE
Tutorials with demos

### ISSUE THREAD

**Issue by maxkfranz** [nrnb/GoogleSummerOfCode#15]
### Background
[Cytoscape.js](http://js.cytoscape.org/) is a JavaScript library for graph theory analysis and visualisation.  It supports many different graph types, such as simple graphs, multigraphs, compound graphs, etc.  Cytoscape.js is used in several apps to provide an interactive graph visualisation, and it has also been used for analysis in the terminal and on the server.

### Goal
Implement step-by-step tutorials that use Cytoscape.js to illustrate the functionality and common use cases supported by the library.

### Description
When a developer follows a tutorial, by the end they should have a working, interactive demo.  Cytoscape.js already provides some [simple demos](http://js.cytoscape.org/#demos), so the purpose of these tutorials is to give a more gradual introduction to coding with Cytoscape.js.  Tutorials should have richer feature sets than the simple, existing demos.  The tutorials should be on the order of complexity as the examples that follow:

* Create your first Cytoscape.js-based webapp
* Create a visualisation of your friends on a social network (Facebook or Twitter) and do some simple analysis (e.g. find the friends who have the highest centrality)
* Create a desktop app using Cytoscape.js and [Electron](http://electron.atom.io/)
* Create a mobile app using Cytoscape.js and [Cordova](https://cordova.apache.org/)

### Potential Mentors
Max Franz

### Contact
maxkfranz@gmail.com

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
