### ISSUE TITLE
Generating detailed genetic logic circuit models using GeneTech

### ISSUE THREAD

**Issue by hasanbaig** [nrnb/GoogleSummerOfCode#150]
### Background
GeneTech (extracted from **Gene**tic **Tech**nology mapping) is a tool which allows a user to generate genetic logic circuits only by specifying the logical function desired to be achieved in a living cell. It does not require a user (either biologist or a computer scientist) to learn any programming language. All what it requires a user to specify a desired logical function in the form of simple Boolean Algebra. 

The tool first performs logic optimization, followed by synthesis and technology mapping using a library of genetic logic gates. In the end, GeneTech performs technology mapping to generate all the feasible circuits, with different genetic gates, to achieve the desired logical behavior.  

GeneTech generates the circuits in the form of [SBOL data](https://sbolstandard.org/data/), [SBOL visual](https://sbolstandard.org/visual/) and Logic circuit schematic. 

Though GeneTech generates the possible solutions in the form of SBOL files, the one thing where it lags is that it does not generate the corresponding stream of DNA basepairs.  

### Goal
Depending on the number of students work on this project, it would be required that GeneTech should be able to generate the corresponding DNA code of an entire circuit as well as each individual component of a circuit. Another aspect the student may choose to work on is the inclusion of [SBOL-SBML ](https://pubs.acs.org/doi/10.1021/sb5003289) conversion tool in GeneTech. There are also possibilities for other proposals related to GeneTech development. For more information, contact directly to the assigned mentor. 

### Difficulty Level 2
The project has a medium level of difficulty due to challenge of extracting DNA code of circuits' component from online repository.  

### Skills
Students need not have any prior experience of biology. They must have a good development skills using Python. A knowledge about SBOL, and JAVA is a plus. Students will be required to familiarize themselves with core aspects of the [SBOL data specification](https://sbolstandard.org/wp-content/uploads/2016/06/SBOL-data-model-2.2.1.pdf) and [SBOL Visual specification](https://sbolstandard.org/wp-content/uploads/2017/04/SBOL-Visual-2.1.pdf).

Python (essential)
Java, SBOL (nice to have)

### Public Repository
[GeneTech](https://github.com/hasanbaig/GeneTech.git)

### Potential Mentors
Hasan Baig (hbaig@uchc.edu)
Ritwik Aggarwal (rtwkaggarwal@gmail.com)

### Contact
For more information, you may send an email to [Hasan Baig](mailto:hbaig@uchc.edu)

**Comment by Aoun-Hussain** [comment]
I am a student from Karachi, Pakistan. I have previously worked on research projects related to Wireless Communications and IoT and simulated them on Python using various libraries. I have never worked on an open source project before. This project is interesting and I would want to work on it!

**Comment by hasanbaig** [comment]
Thanks for your interest @Aoun-Hussain . Please share your CV. We will talk further about it.

**Comment by Aoun-Hussain** [comment]
> Thanks for your interest @Aoun-Hussain . Please share your CV. We will talk further about it.

Sure, I have emailed you my CV @hasanbaig .

**Comment by booleanautocrat** [comment]
Hello!
I am Sarita Singh, a 2nd year undergrad student in electronics and communication engineering from NIT Hamirpur,India. Being from electronics field and interested in coding this project seems very interesting to me. I have not worked with open source before. I know python.I'll like to contribute to this project.

**Comment by ashadhaz** [comment]
Hey my name is Asad Hazariwala and I am a third year undergraduate student. I would like to contribute to this project. I have mailed you my resume.

**Comment by hasanbaig** [comment]
Hi Asad,
Thanks for your interest. I have received it already. Please check my response and get back to me when you are done with the instructions. 
regards
HB

**Comment by ShreyanshTripathi** [comment]
Hi @hasanbaig I am a third year undergraduate student. I have worked on several projects and internships and have a good experience in Python and Java. I am interested in taking this project up for GSoC. I have mailed you my CV. Please have a look and let me know of further process.

**Comment by hasanbaig** [comment]
> Hi @hasanbaig I am a third year undergraduate student. I have worked on several projects and internships and have a good experience in Python and Java. I am interested in taking this project up for GSoC. I have mailed you my CV. Please have a look and let me know of further process.

Hi @ShreyanshTripathi 
I have received your email. I will check your CV and get back to you.

**Comment by ms03831** [comment]
Dear @hasanbaig, 
I have been reading up on this project for the past 3 weeks and am interested in working on this project. I have emailed you my CV. I have about 3 years of extensive experience in Python programming as it is my language of choice. I'm also extremely comfortable with object-oriented programming and familiar with Java as well. I look forward to hearing back from you.

**Comment by hasanbaig** [comment]
Dear @ms03831, 
Thanks for reaching out to me. I have received your CV. Kindly proceed ahead with proposal preparation. We can be in touch over the email.

**Comment by cjmyers** [comment]
Why did you close this issue?  Are you no longer planning to have anyone work on this?

**Comment by hasanbaig** [comment]
Hi Chris, 
I have closed it because I have couple of students applying for this project now. I am not sure if I can take out time to review more proposals if anyone comes forward.

**Comment by cjmyers** [comment]
Has to be open to get a student 

Chris

**Comment by hasanbaig** [comment]
I see. I have reopened it again.

**Comment by khanspers** [comment]
Active project for GSoC 2020, closing here.
