### ISSUE TITLE
Enhance http://compmodelmatch.org/

### ISSUE THREAD

**Issue by vcellmike** [nrnb/GoogleSummerOfCode#153]
### Background
http://compmodelmatch.org/ is the project to match researchers with different expertise.  The set of capabilities we need is best approximated by online data management system.  There exist a few such systems, we have selected SEEK platform (Wolstencroft et al., 2015) that provides the integration and interlinking of heterogeneous data sets in systems biology. The SEEK platform is used in the FAIRDOMHub public service (Wolstencroft et al., 2017) to upload and publish research assets.  The SEEK platform is open-source and built using Ruby on rails.  SEEK platform has well-developed data sharing policies that are upheld through assigned roles. Researchers remain in control of their own assets and can decide who to share them with, and when to publish them. External resources (such as PubMed) can be searched via the SEEK interface through available RESTful Application Programming Interfaces (APIs). Thus, users can easily create libraries of publications related to their projects. The main web user interface of SEEK allowed users to browse projects, institutions, people, publications and many other assets available.  Documents can be made public or be restricted through a comprehensive permissions system that controls visibility to projects and individuals. Content is indexed on upload and available through a Solr search. 

### Goals
1. Better page design and navigation among pages.
2. Customization to serve as NRNB hub for providing expertise and requesting help.
3. Registering/Logging using Google/Facebook/GitHub/Bitbucket credentials.
4. Filling in the registration information using ORCID information, see https://orcid.org/0000-0002-9363-9705

### Difficulty Level: Hard
For someone with Ruby experience this project does not present much difficulty.  

### Size and Length of Project
-**175 hours**
-12 weeks

### Skills
Ruby, mysql, Ruby on Rails (essential)
HTML, CSS (essential)
Docker (essential)

### Public Repository
https://github.com/pepe454/CompModelMatch

### Potential Mentors
Michael Blinov

### Contact
[Michael Blinov](mailto:blinov@uchc.edu)

**Comment by sjha2048** [comment]
Hi @vcellmike , I am interested in this project, I have mailed the mentor assigned.
Are there any additional steps/tasks regarding this, as I was browsing the codebase but there are no issues opened.

**Comment by khanspers** [comment]
Active project for GSoC 2020, closing here.

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by khanspers** [comment]
Closing in preparation for GSoC 2023.
