### ISSUE TITLE
Integration of sequence visualization into SynBioHub

### ISSUE THREAD

**Issue by cjmyers** [nrnb/GoogleSummerOfCode#155]
### Background
SynBioHub is a design repository for Synthetic Biology. It enables genetic components and designs to be uploaded and shared. As such it facilitates the sharing and searching for information, combining data from a variety of sources. SynBioHub uses the Synthetic Biology Open Language (SBOL) an open source data standard that enables an information rich encoding of genetic information. As a genetic repository it is intended to be a key node in a digital workflow for Synthetic Biology. 

To enable greater utility of the SynBioHub platform we aim to extend its capability in a manner that will enhance its usability to genetic wet-lab workers, creating a better synergy between the digital and physical workflows. When creating or using genetic designs in the laboratory, experimentalists frequently want to interrogate the information for specific DNA ‘parts’ prior to using them. The annotation of a DNA sequence will define which strings of the DNA nucleotide sequence encode specific function. Being able to visualise the correlation of sequence to function is critical for experimentalists. Currently SynBioHub lacks a visualization tool that would enable this visualization. Addressing this will greatly enhance the usability of the platform by experimentalists and this will facilitate the integration of digital and physical workflows.

### Goal
SeqViz (https://tools.latticeautomation.com/seqviz/?backbone=pSB1C3&biobrick=) is an open source DNA sequence viewer that would address many of the requirements for correlating the functional annotation with the physical sequence of DNA parts. The key goal of this project would be to integrate SeqViz as a plugin to SynBioHub. Further enhancements to the capabilities of SeqViz, such as the improved rendering of functional annotations to be coordinated with the SBOL Visual standard, would be a stretch-goal for the project.

### Difficulty Level 2

This project has a medium level of difficulty due to the challenge of working with complex codebases and Web technology.

### Skills
Students need not have any experience with biology, but it would help to be proficient in any of JavaScript, TypeScript, or Node.js with some experience developing browser applications. Students will have some flexibility in choosing which aspects of the project they want to work on. Students will be required to familiarize themselves with core aspects of the SBOL data specification and SBOL Visual specification.

### Public Repository
[synbiohub](https://github.com/SynBioHub/synbiohub)
[SeqViz](https://github.com/Lattice-Automation/seqviz/tree/develop/src/SeqViz)

### Potential Mentors
Geoff Baldwin, Imperial College London, UK ([g.baldwin@imperial.ac.uk](g.baldwin@imperial.ac.uk))
Chris Myers, University of Utah, US ([myers@ece.utah.edu](myers@ece.utah.edu))

### Contact
[Geoff Baldwin](mailto:g.baldwin@imperial.ac.uk)

**Comment by darkdebo** [comment]
Hello ,I am Debojyoti Chakraborty from India very much interested to do this project as I have experience with node.js and react creating some small crud app and static website.Only need to learn SBOL.I assure that i can learn the essential technology if rerquired.
@cjmyers 

Thank you

**Comment by cjmyers** [comment]
Thanks for your interest.  Please let us know if you have any questions as you prepare your proposal.

**Comment by darkdebo** [comment]
Ok I will tell you.

**Comment by olive004** [comment]
Hi Dr. Myers,
my name is Olivia and I am part of this year's Imperial iGEM team, Dr. Baldwin pointed us to this project. Our project this year, with the pandemic largely cutting off wet lab access, will be focused on integrating digital and physical workflows, as well as developing digital tools. We would be interested in participating in this as part of our project, but realize that only individual students are able to officially partake in the Google program. We plan to have our software-oriented team members apply with the same proposal, though the nature of our iGEM project would mean more than one of us would be working on tools valuable to the SBOL Designer initiative. Do you recommend for us to apply in this way or suggest something more appropriate? 
If you prefer, you can contact us via our email 
imperialigem2020@gmail.com

Best, Olivia

**Comment by khanspers** [comment]
Active project for GSoC 2020, closing here.
