### ISSUE TITLE
SynBioHub Plugin to Convert Spreadsheets to SBOL

### ISSUE THREAD

**Issue by cjmyers** [nrnb/GoogleSummerOfCode#156]
### Background
[SynBioHub](https://synbiohub.org) is a design repository for Synthetic Biology. It enables genetic components and designs to be uploaded and shared. As such it facilitates the sharing and searching for information, combining data from a variety of sources. SynBioHub uses the [Synthetic Biology Open Language](http://sbolstandard.org) (SBOL) an open source data standard that enables an information rich encoding of genetic information. As a genetic repository it is intended to be a key node in a digital workflow for Synthetic Biology. 

SynBioHub includes a plugin capability that easily allows the extension of SynBioHub with new features.  In order to create a plugin, a developer creates a new web service that accepts instructions from SynBioHub and returns results via an established protocol.  Since these plugins are developed externally to SynBioHub, they can be developed in any language desired.

A key challenge in synthetic biology is the wet lab experimentalists tend to prefer the use of spreadsheets over other software tools that use prescribed data standards, such as SBOL.  Therefore, this creates a disconnect from those performing the experiments and those capturing and sharing the results of these experiments.

### Goal
The goal of this project will be to develop a SynBioHub submission plugin that can transform information provided in spreadsheet form into SBOL that is then transferred into the SynBioHub repository.  These spreadsheets will be organized around a variety of template types.  Some examples might be to describe libraries of parts, combinatorial designs, assembly build plans, or experimental tests. 

### Difficulty Level 2

This project has a medium level of difficulty due to the challenge of learning the SBOL standard and working with Web technology.

### Skills
Students need not have any experience with biology, but it would help to be proficient in any of Python or JavaScript with some experience developing browser applications. Students will be required to familiarize themselves with core aspects of the SBOL data specification.

### Public Repository
[synbiohub](https://github.com/SynBioHub/synbiohub)

### Potential Mentors
Chris Myers, University of Utah, US ([myers@ece.utah.edu](myers@ece.utah.edu))
Jeanet Mante, University of Utah, US ([jv@mante.net](jv@mante.net))

### Contact
[Chris Myers](mailto:myers@ece.utah.edu)

**Comment by dukkee** [comment]
@cjmyers Hello. Is this issue still open and without any interns? I would like to apply to this project

**Comment by cjmyers** [comment]
The issue is still open, though there is one other person who is planning to write a proposal on this topic.

**Comment by dukkee** [comment]
@cjmyers Got it, but I want to fight for this project. Is it possible? Can I send you a draft in the next 6-8 hours for an initial review? What is the best way to contact you and at what time?

**Comment by dukkee** [comment]
@cjmyers I just want to say you, that I won't just "plan to write a proposal", I want to write a good proposal with your help, even despite the small amount of time before the end!!

**Comment by cjmyers** [comment]
Email is best.  It is always good to have a backup project, since there is only one student selected per project idea.

**Comment by dukkee** [comment]
fine, thank you very much for the feedback. Then I will write you an email with a draft proposal link. Will you be online after 5-8 hours?

**Comment by cjmyers** [comment]
Probably

**Comment by dukkee** [comment]
great, so I will ping you via email. Thank you very much again :+1:

**Comment by khanspers** [comment]
Active project for GSoC 2020, closing here.
