### ISSUE TITLE
PD to AF conversion service and its support in Newt

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#157]
### Background
[Newt](http://newteditor.org) [1] is a [Cytoscape.js](http://js.cytoscape.org/) based viewer and editor for biological maps in Systems Biology Graphical Notation (SBGN) notation [2] to create biological maps from scratch or edit existing ones. It's been built (with partial support from GSoC) around an editing library named [ChiSE](https://github.com/iVis-at-Bilkent/chise.js), which in turn was based on a viewer library named [SBGNViz](https://github.com/iVis-at-Bilkent/sbgnviz.js) [3]. The tool uses a number of new [Cytoscape.js extensions](http://js.cytoscape.org/#extensions) built for various editing capabilities such as grid-guidelines, context-menus, and expand-collapse.

[1] H. Balci et al., "[Newt: a comprehensive web-based tool for viewing, constructing, and analyzing biological maps](https://doi.org/10.1093/bioinformatics/btaa850)", Bioinformatics, to appear.

[2] M. Sari et al., "[SBGNViz: a tool for visualization and complexity management of SBGN process description maps](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0128985)", PLoS ONE, 10(6), e0128985, 2015.
 
[3] N. Le Novère et al., "[The Systems Biology Graphical Notation](http://www.nature.com/nbt/journal/v27/n8/abs/nbt.1558.html)", Nature Biotechnology, 27, pp. 735-741, 2009.

### Goal
Newt supports both Process Description (PD) and Activity Flow (AF) languages of SBGN. However, currently there is no automatic conversion between the two languages. Going from AF to PD would not be quite possible since PD is a more detailed type of description but there is already a library for doing this from PD to AF based on [4].

The goal of this project is to put together and host a service for this converter and then integrate it into Newt.

[4] Vogt et al., "[Translation of SBGN maps: Process Description to Activity Flow](https://bmcsystbiol.biomedcentral.com/articles/10.1186/1752-0509-7-115)" , BMC Systems Biology, 7, 115, 2013.

### Difficulty Level 2
The project can be considered a fairly difficult one since it involves work in back end and front end programming.

### Skills
HTML, JavaScript, Cytoscape.js and its extension structure (essential)
SBGNViz and ChiSE (nice to have)

### Public Repository
[Newt GitHub repository](https://github.com/iVis-at-Bilkent/newt)
[ChiSE GitHub repository](https://github.com/iVis-at-Bilkent/chise.js)
[SBGNViz.js GitHub repository](https://github.com/iVis-at-Bilkent/sbgnviz.js)

### Potential Mentors
[Ugur Dogrusoz](https://github.com/ugurdogrusoz)
[Alexander Mazein](https://github.com/amazein)

### Contact
[Ugur Dogrusoz](http://www.cs.bilkent.edu.tr/~ugur/)

**Comment by RATED-R-SUNDRAM** [comment]
hello, I am Shivam Sundram undergraduate in computational biology. I have knowledge of HTML, CSS, JS, and its various frameworks including node and Cytoscape. I would like to work on this project so any guidance on how to get started would be very helpful.

**Comment by RATED-R-SUNDRAM** [comment]
@ugurdogrusoz if you could guide me on how to get started and what skills I should learn it would be very helpful for me

**Comment by ugurdogrusoz** [comment]
Here is a conversion facility that could be of use: https://www.pd2af.org/

**Comment by RATED-R-SUNDRAM** [comment]
Im willing to work please let me know how to get started

**Comment by patelaryan7751** [comment]
hello @ugurdogrusoz i found this project really interesting i want to work on it can you give some more info on this?/

**Comment by RATED-R-SUNDRAM** [comment]
@ugurdogrusoz please update us so we can start our contributions to the project at the earliest.

**Comment by ugurdogrusoz** [comment]
I think you need all the information here. I would first study Newt and then see how one can implement a GUI for facilitating such conversion. The actual converter needs to be put together probably as a service. I already provided a link to a conversion facility.

**Comment by khanspers** [comment]
This is an active GSoC 2021 project. The issue will be closed for the duration of GSoC since it is no longer available to other students.
