### ISSUE TITLE
Local DB support for SBGN maps in Newt

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#158]
### Background
[Newt](http://newteditor.org) [1] is a [Cytoscape.js](http://js.cytoscape.org/) based viewer and editor for biological maps in Systems Biology Graphical Notation (SBGN) notation [2] to create biological maps from scratch or edit existing ones. It's been built (with partial support from GSoC) around an editing library named [ChiSE](https://github.com/iVis-at-Bilkent/chise.js), which in turn was based on a viewer library named [SBGNViz](https://github.com/iVis-at-Bilkent/sbgnviz.js) [3]. The tool uses a number of new [Cytoscape.js extensions](http://js.cytoscape.org/#extensions) built for various editing capabilities such as grid-guidelines, context-menus, and expand-collapse.

[1] H. Balci et al., "[Newt: a comprehensive web-based tool for viewing, constructing, and analyzing biological maps](https://doi.org/10.1093/bioinformatics/btaa850)", Bioinformatics, to appear.

[2] M. Sari et al., "[SBGNViz: a tool for visualization and complexity management of SBGN process description maps](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0128985)", PLoS ONE, 10(6), e0128985, 2015.
 
[3] N. Le Novère et al., "[The Systems Biology Graphical Notation](http://www.nature.com/nbt/journal/v27/n8/abs/nbt.1558.html)", Nature Biotechnology, 27, pp. 735-741, 2009.

### Goal
The goal of this project is to integrate local database support for Newt to store SBGN maps on a shared server. We would like these maps to be integrated as they are deposited into the database. We would also like to see a rich set of queries to properly access the maps of interest based a genes of interest of the user using graph based queries such as those provided in [4].

A graph database [Neo4j](https://neo4j.com/) would probably be a good choice of technology for this purpose.

[4] U. Dogrusoz et al., "[Algorithms for Effective Querying of Compound Graph-Based Pathway Databases](https://doi.org/10.1186/1471-2105-10-376)", BMC Bioinformatics, 10:376, 2009.

### Difficulty Level 3
The project can be considered a fairly difficult one since it involves work in back end and front end programming.

### Skills
HTML, JavaScript, Cytoscape.js and its extension structure, and Neo4j (essential)
SBGNViz and ChiSE (nice to have)

### Public Repository
[Newt GitHub repository](https://github.com/iVis-at-Bilkent/newt)
[ChiSE GitHub repository](https://github.com/iVis-at-Bilkent/chise.js)
[SBGNViz.js GitHub repository](https://github.com/iVis-at-Bilkent/sbgnviz.js)

### Potential Mentors
[Ugur Dogrusoz](https://github.com/ugurdogrusoz)

### Contact
[Ugur Dogrusoz](http://www.cs.bilkent.edu.tr/~ugur/)

**Comment by y-pankaj** [comment]
Hi @ugurdogrusoz, Pankaj here, a senior undergraduate from India. I found this project interesting and it aligns with my tech stack as well, so I would like to work on this project. I have mailed you my resume and certain queries that I had. Hoping to hear back from you soon!

**Comment by ugurdogrusoz** [comment]
Responded through email.

**Comment by khanspers** [comment]
This is an active GSoC 2021 project. The issue will be closed for the duration of GSoC since it is no longer available to other students.
