### ISSUE TITLE
Building a simulation execution environment using Github Action

### ISSUE THREAD

**Issue by funasoul** [nrnb/GoogleSummerOfCode#159]
### Background
In recent years, the importance of reproducibility has been reaffirmed in the field of research. This refers to the ability of a third party to reproduce the work done by an experimenter (researcher). The field of simulation using mathematical models is no exception, and it is said to be important to ensure reproducibility. For example, according to [1], it is reported that about half of the systems biology models fail to directly reproduce simulation results.
Therefore, the goal of this project is to build a simulation environment that can ensure reproducibility. Specifically, we will build a framework to simulate mathematical models pushed to github and return the execution results.

[1] Tiwari, Krishna, et al. [“Reproducibility in systems biology modelling.”](https://doi.org/10.1101/2020.08.07.239855) bioRxiv (2020).

### Goal
When a user pushes a mathematical model (SBML) and simulation conditions (SED-ML) to github, the framework will execute the specified simulation and returns the execution result using github action.

### Difficulty Level 1
Since the existing SBML compatible simulator SimulationCore Library supports SBML and SED-ML, the difficulty of this project is relatively low. The simulation environment will be more robust if SBML verification is performed before running the simulation.

### Skills
XML, Java, git (essential)
SBML, SED-ML, docker (nice to have)

### Public Repository
- [JSBML](https://github.com/sbmlteam/jsbml)
- [SBSCL](https://github.com/draeger-lab/SBSCL) (The SBML Simulation Core Library)

### Potential Mentors
[Kaito Ii](https://github.com/kaitoii11)
[Akira Funahashi](https://github.com/funasoul)
[Akito Tabira](https://github.com/mythosil)
[Takahiro Yamada](https://github.com/TakahiroYamada)
[Yuta Tokuoka](https://github.com/tokkuman)

### Contact
[Kaito Ii](mailto:kaitoii1111@gmail.com)
[Akira Funahashi](mailto:funasoul@gmail.com)
[Akito Tabira](mailto:mythosil2008@gmail.com)
[Takahiro Yamada](mailto:yamataka.genetics@gmail.com)
[Yuta Tokuoka](mailto:bowbrand1227@gmail.com)

**Comment by TakahiroYamada** [comment]
@khanspers 

Hi, I'm Takahiro Yamada planning to be a potential mentor of this project.
Could it be possible to add me an assignees to this issue?
With best regards.

Takahiro Yamada

**Comment by yash170106065** [comment]
Hi @kaitoii11 @tokkuman @mythosil @funasoul @TakahiroYamada can we discuss this, I would like to take up this issue.

**Comment by TakahiroYamada** [comment]
Hi @yash170106065 !
Could you please inform us of your skills related to this project?
Then, it could be smoother to discuss this project.

Best.

Takahiro

**Comment by yash170106065** [comment]
@TakahiroYamada Actually I am contributing to NRNB for the last 1 year and familiar with Git, Github, Java.

**Comment by TakahiroYamada** [comment]
@yash170106065 
I'm so sorry for responding late!!
Great! I guess you are very familiar not only with computational side but also a series of GSoC flow!!

Do you have experience to use GitHub Action?

Takahiro

**Comment by avinal** [comment]
Hello @TakahiroYamada, @funasoul, and everyone, I am Avinal, pursuing Bachelors in CS from NIT Hamirpur, India, I am willing to contribute to this project. I would like to inform you about my skills as asked above :
- C++(done lots of projects) and Java(done a few projects + Spring Boot + core programming)
- Had a course in Modelling and Simulation and experienced with CPN tools, R and Matlab simulation techniques
- I am familiar with the GSoC workflow too, (I did GSoD last year, and had been contributing to many orgs since 2019)
- I have successfully migrated/created CI to GitHub Actions for many projects (Boost.GIL, VideoLAN, Fossology and many little ones)
- Never contributed to NRNB, but I am in progress to understand the projects/working and will be on track soon

I hope we are good to discuss this project further :)

**Comment by avinal** [comment]
I tried running included examples, I am though a bit unsure about what is the proper command to run simulations. These are the results. 
![image](https://user-images.githubusercontent.com/74113200/111111744-e808cc00-8584-11eb-8836-0a04b4a72d34.png)
![image](https://user-images.githubusercontent.com/74113200/111111789-f820ab80-8584-11eb-8acb-8143dc66a434.png)

Please let me know if there is a proper doc on how to run, I saw all the readme, and docs but might have missed it. 
if this is the correct place for discussions, I would like to add more observations

**Comment by khanspers** [comment]
Cleanup in preparation for GSoC 2022.
