### ISSUE TITLE
Bipartite layout for Cytoscape

### ISSUE THREAD

**Issue by risserlin** [nrnb/GoogleSummerOfCode#16]
### Background

The nodes within a network can sometimes belong to distinct types or classes.  For instance a protein interaction network can contain receptors, and ligands or proteins originating from two different cell types. Current layout algorithms in [Cytoscape](http://www.cytoscape.org), however, typically ignore these distinctions and primarily focus on connectivity and topology when laying out a network.
### Goal

Create a bipartite layout for Cytoscape that would allow one to see how two (or more) distinct groups of nodes interact with each other. The layout needs to work both globally and locally.  You might want to layout the entire network based on two different cell types but also layout out each cell type separately by a different attribute.  The bipartite layout needs to be able to layout an entire network or just a subset potentially using different attributes for each. 
### Difficulty level: 1

No prior experience with Cytoscape is required. The student should be adept at math and have an affinity for layout algorithms, where graph theory and visualization intersect.
### Language and Skills

Cytoscape, Java
### Potential Mentors

Mike Kucera, Ruth Isserlin, Gary Bader, Max Franz
### Contact

[Mike Kucera](mailto:mikekucera@gmail.com), [Ruth Isserlin](mailto:ruth.isserlin@utoronto.ca), [Gary Bader](mailto:gary.bader@utoronto.ca), [Max Franz](mailto:maxkfranz@gmail.com)

**Comment by khanspers** [comment]
closing for now since there is an active NRNB academy project being evaluated

**Comment by khanspers** [comment]
Closing for GSoC 2019

**Comment by scootermorris** [comment]
I believe boundaryLayout accomplishes this.
