### ISSUE TITLE
Adding analysis report and Direct import from GEO databases  to ABioTrans Plus

### ISSUE THREAD

**Issue by MoHelmy** [nrnb/GoogleSummerOfCode#162]
### OVERVIEW
[ABioTrans](https://www.frontiersin.org/articles/10.3389/fgene.2019.00499/full) is a bio-statistical/informatics tool that was developed in R to analyze RNASeq gene expression data. [ABioTrans Plus](http://combio-sifbi.org/ABioTrans/) is the webserver of ABioTrans that analyzes RNASeq or Microarray gene expression data and performs multiple gene set and protein set analyses including gene ontology (GO), pathways enrichment and co-expression analysis. ABioTrans Plus is developed to be a one-stop server for transcriptomic data analysis, including the downstream analysis of the set of resultant differentially expressed genes (DEGs).

### Focus
This project aims to add new features to ABioTrans Plus that includes the direct import of gene expression data from [Gene Expression Omnibus (GEO) databases](https://www.ncbi.nlm.nih.gov/geo/), creating a detailed report with the performed analysis with figures and data ready to be included in the publications, add more gene expression analysis methods e.g. Gene Set Enrichment Analysis (GSEA) and adding more sample comparison analysis and plots.

### Goals
1- Create the analysis report generator that generates the report at the end of the analysis. 
2- Direct import from GEO databases 
3- Sample overlap (Venn diagram)
4- - Density plot
5 - Gene Set Enrichment Analysis (GSEA)

### Coding Skills
R programming,  Shiny, JavaScript, HTML/CSS

### Acceptance Criteria
Students interested in working on this project will be asked to provide their CV and school transcript then the short-listed students will be asked to do an evaluation task that will be used for assessing their fitness for the project.

### Public Repository
[ABioTrans at GitHub](https://github.com/buithuytien/ABioTrans)

### Mentors
[Thuy Tien Bui](mailto:Bui_Thuy_Tien@sifbi.a-star.edu.sg), [Mohamed Helmy](mailto:mohamed_helmy@sifbi.a-star.edu.sg)

### Our Lab website
[The COMPUTATIONAL BIOLOGY AND OMICS GROUP](http://combio-sifbi.org)
Singapore Institute of Food and Biotechnology Innovation (SIFBI), A*STAR]

**Comment by Anjani-225** [comment]
Hi! This issue looks very interesting to me.
Could someone guide me on how to get started?

**Comment by tasbihaasim** [comment]
Hello, I am interested in contributing to this project. How can I get started?

**Comment by AhwiniMirajkar** [comment]
I want to work on this

**Comment by MoHelmy** [comment]
For everyone interested in the project, please send your CV and school report to the mentors. 
Also, please check the repo of the project and take a deeper look at the code.

**Comment by VimukthiRandika1997** [comment]
Hey! I  am very interested  about this project as this give me the ability to find the newest technological aspects in the bioinformatics. Hence I would like to take this project for the GSOC 2021. I am really ego to get the answers from the mentors. Thanks.

**Comment by khanspers** [comment]
This is an active GSoC 2021 project. The issue will be closed for the duration of GSoC since it is no longer available to other students.
