### ISSUE TITLE
Enhancing the admin panel of openPIP 

### ISSUE THREAD

**Issue by MoHelmy** [nrnb/GoogleSummerOfCode#163]
### OVERVIEW
The [Open Source Protein Interaction Platform (openPIP)](http://baderlab.org/Software/openPIP) is an open-source software package for hosting protein-protein interaction (PPI) data based on the [PSI-MI-TAB format](https://code.google.com/archive/p/psimi/wikis/PsimiTab27Format.wiki). openPIP provides a PPI database and a customizable web interface that enables searching and visualizing the interactions as well as downloading the search results in different formats. The whole system is a ready-to-use virtual machine that can be imported to VMware. openPIP was used to build the portals f two major PPI project, [The Human Reference Protein Interactome Mapping (HuRI) Project](http://www.interactome-atlas.org/) ([Luck at el, Nature, 2020](https://www.nature.com/articles/s41586-020-2188-x)) and [The Yeast Protein Interactome Mapping (YeRI) Project](http://yeast.interactome-atlas.org/) (Under review).

### Focus
This project aims to add improve the admin panel of openPIP that is used to upload data and files, post announcements and change global settings of installed instance. The student also will be working on the creation of an installation package and installation guide for the new users to follow.

### Goals
1- Enhance the admin panel of openPIP. 
2- Create an installation package for the software. 
3- Create an installation guide. 
4- Help in creating and updating the content of the website of openPIP.

### Coding Skills
PHP, JavaScript, HTML/CSS, Symfony

### Acceptance Criteria
Students interested in working on this project will be asked to provide their CV and school transcript then the short-listed students will be asked to do an evaluation task that will be used for assessing their fitness for the project.

### Public Repository
[openPIP at GitHub](https://github.com/BaderLab/openPIP)

### Mentors
[Gary Bader](mailto:Gary.Bader@utoronto.ca), [Mohamed Helmy](mailto:mohamed_helmy@sifbi.a-star.edu.sg)

**Comment by yash170106065** [comment]
@MoHelmy I would like to contribute to this project since I am contributing to NRNB at Graphspace for the last 1 year and successfully completed gsoc2020, so I am familiar with these skills.

**Comment by ShubhamChaudharyy** [comment]
@MoHelmy i am open for this role and would love to contribute to NRNB.
https://drive.google.com/file/d/1jZZSQv_ctX-omPZOTdPqvXXzuZIohhdh/view?usp=sharing

**Comment by ayan-biswas0412** [comment]
Hi @gbader and @MoHelmy I am interested to collaborate in this project and I am working in the domain of the mentioned skillsets for about 2 year and this project is aligned with my knowledge and I am an active open source collaborator , here is my GitHub profile https://github.com/ayan-biswas0412 .
[Here](https://drive.google.com/file/d/1JFyk92n0XcA2LukcH6nroPloY7l0XyVP/view) is the link of my resume and find more info at my [website](https://ayanbiswas.in) . 
Actively looking for some initial issues to work on this project

**Comment by khanspers** [comment]
This is an active GSoC 2021 project. The issue will be closed for the duration of GSoC since it is no longer available to other students.
