### ISSUE TITLE
Interactive SBML report for Humans (SBML4Humans)

### ISSUE THREAD

**Issue by matthiaskoenig** [nrnb/GoogleSummerOfCode#164]
<h1><img alt="SBML" src="https://avatars2.githubusercontent.com/u/1799692?s=280&v=4" height="40"/> SBML4Humans <img alt="Humans" src="https://user-images.githubusercontent.com/900538/102484966-45b17900-4067-11eb-955b-3392c107ad46.png" height="40"/> </h1>

### Background
The Systems Biology Markup Language ([SBML](http://sbml.org)) is the de facto standard for encoding computational models in systems biology. SBML is a XML based markup language and used for a wide range of models, e.g., metabolic models, signalling models, physiological models. 
SBML is a standard format for the exchange of models between computers and not intended to be looked at by Humans. Currently, a Human readable interactive report which conveys the SBML information and content of a model is urgently needed.

### Goal
The objective is to build an interactive (reactive) web based SBML report for Humans.

The report will build on top of a non-interactive HTML report established in [sbmlutils](https://sbmlutils.readthedocs.io/en/latest/notebooks/sbml_report.html). The report will be made available as a standalone web service which allows to upload an SBML file and get access to the interactive report.

Important features are:
- navigation between SBML objects
- filtering/searching of information
- support for annotation (and display of annotation information)
- support of units
- support of hierarchical models

The project will use vue.js and python to build the report.

An SBML report for Humans would be an important asset to communicate and disseminate computational models and allow easily to understand computational models created by others.
 
### Difficulty Level 2

The project requires skills in javascript with an understanding of reactive components,  python and an understanding of SBML.

### Skills
- python
- javascript (vue.js)
- SBML

### Public Repository
https://github.com/matthiaskoenig/sbmlutils

### Potential Mentors
Matthias König

### Contact
[Matthias König](mailto:konigmatt@googlemail.com)

**Comment by sankha555** [comment]
Hello @matthiaskoenig , 
I would like to work on this project as a part of GSoC 2021 and further in the future. I have extensive experience in developing web-apps using Python and JavaScript and believe that I will be able to contribute to this project. Could you please guide me on how to start working on it? Also, shall I convey my resume/CV to you through email for your reference? 

I am attaching a link to my [personal website](https://sankha555.github.io/index/) here which contains information about my background, past projects and link to my resume. In case you require any other details, I would be happy to mail them to you. Looking forward to a response from you, thanks!

**Comment by matthiaskoenig** [comment]
@sankha555 This is amazing. Thanks for the interest. I am catching up with the applicants until the weekend, so please stay tuned.

**Comment by sankha555** [comment]
Sure @matthiaskoenig , thanks a lot for the response!

**Comment by matthiaskoenig** [comment]
@draeger Would you be interested in co-mentoring this project?

**Comment by SantamRC** [comment]
Hello @matthiaskoenig ,
This is Santam. I am doing my major in computational biology. I am profient in python, Rust and javascript. I have a basic understanding of SBML and I am interested to work on this project.

**Comment by matthiaskoenig** [comment]
@all We have now 2 very interested students in the project which I will support in their proposals. If you are interested in NRNB GSOC this year please consider one of the other available projects without students (https://github.com/nrnb/GoogleSummerOfCode/issues). Unfortunately, I can only help 2 students writing a proposal and both have been in contact with me already for some time. 

Of course everybody can feel free to write a proposal. The evaluation process is by all mentors, but only a single student per project can be funded. Early contact with mentors and feedback on proposals is an important part for a good proposal. So to increase your changes consider an issue with no students and get in contact with mentors as soon as possible ;)

**Comment by draeger** [comment]
@matthiaskoenig and all! I think this is a vital and exciting topic, and I wish you lots of success and fun during GSoC! Unfortunately, I have to pass this time and can't act as a mentor this summer.

**Comment by matthiaskoenig** [comment]
@draeger Thanks for all the support.

**Comment by khanspers** [comment]
This is an active GSoC 2021 project. The issue will be closed for the duration of GSoC since it is no longer available to other students.
