### ISSUE TITLE
MasterMap - advanced Network merge

### ISSUE THREAD

**Issue by risserlin** [nrnb/GoogleSummerOfCode#17]
### Background

Currently within [Cytoscape](http://www.cytoscape.org) it is possible to merge networks using union, intersection and difference between any two networks.  After merging two networks you can switch between the visual style of network 1 and network 2 to see how the two networks differ.  Sometimes it is difficult to highlight what is common and what is unique to each network. 
### Goal

To develop an advanced network merge app that creates a collated view of multiple networks but also retains properties from original networks. We would like to implement an advanced network merge that:
- Build on current network merge.  Create mastermap options.
- Add user interface that intuitively makes it easy to view the mastermap or individual network views.
- When networks share common attributes track which network the attribute originates from but also create a collated attribute containing values from each network. Collated attributes can be visualized as charts in the network collated view.
- Easily highlight each individual network, unique to network A, unique to network B.,.., common to all networks within the master network in UI as well as in the collated visual style.(for example - dotted edge line for unique edges).
- Ability to use template network for merge.  For example, network A has interactions between proteins {A-B, D-F}, Network B has interactions between protein {B-C}.  The resulting network union merge would contain {A-B,B-C, D-F} but in the set of interactions used to create network A and network B there is also the interaction C-D but C only exists in network A and D only exists in network B. Ideally in the merged view we would like to add the interaction between C-D.
### Difficulty Level: 1

No prior experience with Cytoscape or Cytoscape apps is required.
### Language and Skills

Cytoscape, Java
### Potential Mentors

Ruth Isserlin, Gary Bader
### Contact

[Ruth Isserlin](mailto:ruth.isserlin@utoronto.ca), [Gary Bader](mailto:gary.bader@utoronto.ca)

**Comment by amil101** [comment]
Hi,
I'm a 3rd year under graduate in the department of Computer Science and Engineering at University of Moratuwa, Sri Lanka
well i don't have much knowledge about Cytoscape but i think i can do this project.
So I want to know more details regarding this Project which i can proceed through. 
Hope you will help me with this.
Thanks,

**Comment by AlexanderPico** [comment]
Hi amil101,

Try contacting the mentors directly by the email links provided above. Include more information about your relevant background and which particular concepts or resources you are stuck on.

**Comment by amil101** [comment]
hey!!! i think the link of mentors are not working ?

**Comment by AlexanderPico** [comment]
Here you go: ruth.isserlin@utoronto.ca
