### ISSUE TITLE
Develop an Exporter of CellBox Models to SBML

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#170]
### Background
CellBox (https://www.biorxiv.org/content/10.1101/746842v3) is a machine learning algorithm (built using Tensorflow) for generating network models for large scale perturbation biology experiments. The output is executable models capable of predicting the effects of cancer therapies. 

### Goal
The goal is to export the resulting executable models from CellBox into formats with wider usage in the systems biology community (namely SBML: http://sbml.org/Main_Page). This will allow models produced by CellBox to reach a larger audience. A student would need to be able to run CellBox then reproduce this model in SBML. The BioModels database has many SBML models available (https://www.ebi.ac.uk/biomodels/) as examples. 

##### Learning about SBML 
* SBML Description: https://www.embopress.org/doi/full/10.15252/msb.20199110
* Running SBML Model: https://tellurium.readthedocs.io/en/latest/notebooks.html
* Example SBML Model: https://www.ebi.ac.uk/biomodels/BIOMD0000000012

##### Learning About CellBox
Learn to run CellBox (https://github.com/sanderlab/CellBox) such that you are able to produce the time-series simulation results similar to those in the publication (https://www.sciencedirect.com/science/article/pii/S2405471220304646) for from a example datasets. The key to this question is mapping CellBox results to an SBML representation via the equation in the "Model Configuration" of the publication; this may or may not be possible, a good proposal would demonstrate its feasibility. 

##### Asking For Help 
Any question about unclear documentation or running CellBox should be directed to: https://github.com/sanderlab/CellBox/issues

### Difficulty Level 2
The student will need to learn how to interpret CellBox output (as well as the underlying kinetic model) and translate this to SBML. 

### Skills
* Essential skills: Python, XML, SBML 
* Nice to have skills: COPASI (or another SBML executing tool)

### Public Repository
* https://github.com/dfci/CellBox

### Preferred Communication
* Project questions: Ask here on this issue.
* Encountered bugs: Ask on the main project issue tracker. 

### Potential Mentors
[Augustin Luna](mailto:aluna@jimmy.harvard.edu)
Judy Shen
Desmond Yuan

**Comment by palashgarg0109** [comment]
Hi @cannin 
I find this issue interesting and would like to work on it. Could you please help me how should I proceed to the task?
Also, what is the preferred method of contact?
Thank You :)

**Comment by shaliniiit** [comment]
@cannin I have gone through the code and the issue and feel like its a good fit for me having worked on similar projects in other universities like Penn State and CMU. I'd be happy to start working. Please look up my resume: https://drive.google.com/file/d/1pcqymg8_DTuCQTTV8cUyEfISpvD63Jlq/view?usp=sharing

**Comment by cannin** [comment]
@palashgarg0109 @shaliniiit thank you for your interest. I have added additional content to the description to help you get started and better define the problem to be addressed.

**Comment by abhinavgudipati** [comment]
@cannin @DesmondYuan @judyueshen Hey there! 

I found this project idea interesting! I would love to know how to get in touch with the preferred mode of contact with the mentors assigned to this project. 

I am versatile with Python and Java at a high proficiency. Would love to convert this into meaningful contributions to this organization.

**Comment by cannin** [comment]
@abhinavgudipati thanks. see updated project description above.

**Comment by DesmondYuan** [comment]
@abhinavgudipati Thanks please feel free to go ahead and checkout the current CellBox codes and do some minimal test runs. If you find anything you want to contribute to the repo, you are also welcomed to develop your own branch and create a PR.

**Comment by abhinavgudipati** [comment]
I am interested in working on Drafting my proposal simultaneosly. I am excited to know what are the judging parameters the mentors keep into account at the time of selecting a prospective student for a project knowing that there is competetion in this project already. 

Bearing that in mind, I also would like to know how many students are y'all planning to commit to for this project. ( How many are going to be selected for this project ) 

Thanking you in anticipation. :)

**Comment by DesmondYuan** [comment]
@abhinavgudipati  Please see https://nrnb.org/gsoc.html for how to apply; your proposal needs to reflect the goals (above) of the project.

In terms of head counts, I'm not the final judge but it should not go beyond 2 students. Thanks and good luck for your application.

**Comment by abhinavgudipati** [comment]
Hey! My Mid-sem exams are finally done, I would like to know if you are free to contact for advise concerning the Proposal of the project.

**Comment by abhinavgudipati** [comment]
Also, regarding pull requests, how much of a compulsion is it to attempt pull requests? Pull Requests specific to this project is taken into account?

**Comment by cannin** [comment]
@abhinavgudipati there is no requirement. check here for application requirements: https://nrnb.org/gsoc.html 

You will need to do a proposal and the proposal must demonstrate you have plan that is more clear that other applicants for finishing the project. We, of course, do appreciate any pull requests that solve any issues you might encounter that prevent you from running/exploring the code as you write your proposal.

**Comment by khanspers** [comment]
Cleanup in preparation for GSoC 2022.
