### ISSUE TITLE
Develop a Galaxy Platform Entry for NetBoxR and a Pipeline for Processing cBioPortal Data via the NetBoxR

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#172]
### Background
netboxr (https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0234669) is an R package for the automated discovery of biological process modules by network analysis. 

### Goal
With the netboxr R package available, the goal is to make netboxr more widely available. The Galaxy platform (https://galaxyproject.org/) is a platform to make tools more widely available. The goal would be to make netboxr available on Galaxy (https://galaxyproject.org/admin/tools/add-tool-tutorial/). 

Additionally, time permitting, a secondary goal would be to process datasets from cBioPortal with netboxr (https://github.com/cBioPortal/datahub/tree/master/public) following the package vignette (https://bioconductor.org/packages/release/bioc/vignettes/netboxr/inst/doc/netboxrTutorial.html). 

#### Getting Started
Eventually, you'll need to write a proposal. Elements of this proposal should include:

1. Demonstrated understanding (code samples help) of what steps are involved in making a Galaxy tool 
2. Try out netboxr on different sets of data from cBioPortal given the instructions in the tutorial

##### Getting Help
Post issues if you encounter bugs in the tutorial here: https://github.com/mil2041/netboxr/issues

### Difficulty Level 1
Navigating the documentation for the Galaxy platform may have some difficulty. 

### Skills
* Essential skills: R, XML 

### Public Repository
* https://github.com/mil2041/netboxr

### Potential Mentors
[Augustin Luna](mailto:aluna@jimmy.harvard.edu)

**Comment by HarshKhilawala** [comment]
@cannin I find myself interested for this project. Let me know about further steps.

**Comment by cannin** [comment]
@HarshKhilawala I posted more details to get you started in the description

**Comment by Aditya-Kumar-Jha** [comment]
Hi!! Aditya here; I would like to work on this project for GSOC 2021. I am a 2nd-year Computational Biology student from IIIT Delhi.
I have experience working with R & XML. I'm basically new to open source, so even a bit of help will be really appreciated! Thanks.

**Comment by cannin** [comment]
@3adityajha Read the project description "Getting Started" for initial steps, then learn about Galaxy, then you need to create a proposal for intended work; see application instructions: https://nrnb.org/gsoc.html.
