### ISSUE TITLE
Make SBGN-Formatted Diagram Collections Accessible in R

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#173]
### Background
Systems Biology Graphical Notation (SBGN; http://sbgn.org/) provides standard graphical languages for representing cellular processes, interactions, and biological networks. SBGN diagrams are encoded in the SBGNML format (https://pubmed.ncbi.nlm.nih.gov/32568733/). SBGN diagrams are available from a number of sources including Reactome (https://reactome.org/download-data). 

#### Existing Work 
* A small R package (sbgnvizShiny) was created to work with SBGNML files in R including coloring them. 
* A Python package to render SBGNML to images 

#### Getting Started
* Try out the Python render code; does it work or not? 
* Try out the R sbgnvizShiny package; what works or not? 
* Make sure you can run Python from R
* Try out services to map node labels to gene symbols: https://extract.jensenlab.org/ how can it be used to address the project goals (other solutions welcomed)?

### Goal
This project would address following goals: 

* Currently, sbgnvizShiny has no easy way of downloading SBGN diagrams as raster images (e.g., PNG) from R 
* There is no available repository of SBGNML files accessible within sbgnvizShiny
* Diagram labels are not always approved gene symbols (https://www.genenames.org/); an attempt to map these would be made to map these to approved symbols to simplify mapping datasets to SBGNML files 

### Skills
* Essential skills: R, Javascript, XML
* Nice to have skills: Python

### Public Repository
* https://github.com/cannin/sbgnvizShiny
* https://github.com/iVis-at-Bilkent/sbgnviz.js/
* https://github.com/vincent-noel/SBGNRenderAPI

### Potential Mentors
[Augustin Luna](mailto:aluna@jimmy.harvard.edu)
Ugur Dogrusoz

**Comment by spursbyte** [comment]
Hello @cannin can i work on this?@ugurdogrusoz  do you need any help?

**Comment by cannin** [comment]
@spursbyte Feel free to submit a GSOC proposal if interested.

**Comment by spursbyte** [comment]
ok sure

**Comment by khanspers** [comment]
Cleanup in preparation for GSoC 2022.

**Comment by khanspers** [comment]
NRNB has officially been accepted as a mentoring organization for GSoC 2022! Here are some useful links:

- [Project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
- [GSoC contributor guide](https://google.github.io/gsocguides/student/)
- [Program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by khanspers** [comment]
Closing in preparation for GSoC 2023.
