### ISSUE TITLE
Develop a Pipeline for Processing CPPA Proteomics Portal via the TargetScore Algorithm

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#174]
### Background
TargetScore (https://www.biorxiv.org/content/10.1101/711895v2.full) is an algorithm for selecting drug combinations to treat cancer. 

### Goal
The goal is to develop a pipeline to process data from the Cancer Perturbed Proteomics Atlas (CPPA; https://bioinformatics.mdanderson.org/public-software/cppa/) through the algorithm (as described in the vignette: https://github.com/korkutlab/targetscore/blob/master/targetscore/vignettes/target_score_tutorial.Rmd)

### Difficulty Level: Medium
This will require learning how to use the TargetScore package and reformatting data from the CPPA to the proper input file format. 

### Skills
* Essential skills: R
* Nice to have skills: Previous -omics analysis experience 

### Public Repository
* https://github.com/korkutlab/targetscore/

### Potential Mentors
[Augustin Luna](mailto:augustin_luna@hms.harvard.edu)
Anil Korkut

**Comment by shreshtha48** [comment]
Hello, this project sounds interesting! I tried reading through the Target score package documentation, but I am having a hard time grasping it, i would love to know more about this. Do you have any alternative blogs/tutorials i can refer to?

**Comment by cannin** [comment]
@shreshtha48 This is a new tool so additional information is limited. Another place for documentation is here: https://github.com/korkutlab/targetscore/blob/master/targetscore/vignettes/target_score_tutorial.Rmd

If something is unclear on the usage, please post an issue with a question and we can further address it: https://github.com/korkutlab/targetscore/issues

**Comment by Dharna5599** [comment]
Hey @cannin 
This project seems very interesting & I am very comfortable in R. Should I start drafting my GSoC proposal for the same?

**Comment by cannin** [comment]
@Dharna5599 you certainly can. The projects are competitive where only one student will be selected. Students are judged on 1) who is most capable of completing the work, 2) clear proposal of work, 3) community interest of the project. You have the most control f over 1 and 2.

**Comment by banerjeeshayantan** [comment]
@cannin This project seems interesting. Have you already selected an applicant? And do you have any tests or evaluation mechanisms that an applicant needs to perform before submitting the proposal?

**Comment by cannin** [comment]
@banerjeeshayantan no one has been selected. See how to apply here: https://nrnb.org/gsoc.html You will need to do a proposal and the proposal must demonstrate you have plan that is more clear than other applicants for finishing the project.

**Comment by shreshtha48** [comment]
Hello @cannin , i have started working on my proposal. Is there any way i can reach you to get your feedback on the same?

**Comment by cannin** [comment]
@shreshtha48 once you have a good draft. Make it available in Google Docs and share the link with me by email. I expect many requests for this type of review from other students and my time will be limited. Best to try to send as complete a draft as possible.

**Comment by khanspers** [comment]
Cleanup in preparation for GSoC 2022.

**Comment by cannin** [comment]
Re-open for 2023

**Comment by RishithaR-388** [comment]
Hello @cannin I am Rishitha Reddy from India.I am a 3rd year UG student at IIT Bhilai in DSAI discipline, India. I am proficient at python,machine learning,tensorflow,numpy, pandas and other deep learning frameworks.I have a some experience with R.I would like to contribute for this project in the GSoc 2023.I have gone through the issues and could not understand where to start,could you please guide me.
