### ISSUE TITLE
Create Google Colab Notebook(s) Showcasing COMBINE Standards

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#178]
### Background
The "Computational Modeling in Biology" Network (COMBINE, http://co.mbine.org/standards) is an initiative to coordinate the development of the various community standards and formats in systems biology and related fields.

### Goal
The goal is to produce a Python Google Colab (https://colab.research.google.com/) notebook (or several) that showcases these standards and their libraries around a common theme; the repressilator (https://pubmed.ncbi.nlm.nih.gov/10659856/). A number of the standards SED-ML, SBML, SBOL, SBGN, both have Python libraries and existing models based on the repressilator. The idea is to build a notebook utilizing these different representations of a repressilator. 

#### Additional Goals
* Any usage issues with the use of respective libraries will be addressed (or reported) to developers for later follow-up.
* As time permits, other COMBINE standards may be added. 

### Difficulty Level 1
The project will require learning a number of tools quickly. 

### Skills
* Essential skills: Python
* Nice to have skills: Java

### Public Repository
* SBML: http://sbml.org/, https://tellurium.readthedocs.io
* SBGN (Python): https://github.com/matthiaskoenig/libsbgn-python
* SED-ML: https://sed-ml.org/

#### Repressilator
* SBML: https://www.ebi.ac.uk/biomodels/BIOMD0000000012
* SED-ML: https://tellurium.readthedocs.io/en/latest/_notebooks/core/tesedmlExample.html, https://sed-ml.org/examples.html
* SBGN: http://web.newteditor.org/# (see File -> Samples)

### Potential Mentors
[Augustin Luna](mailto:aluna@jimmy.harvard.edu)
[Matthias Koenig](https://github.com/matthiaskoenig)

**Comment by matthiaskoenig** [comment]
@cannin 
I would like to co-mentor this project if possible

**Comment by cannin** [comment]
@matthiaskoenig thanks! I added you in the text.

**Comment by HarshKhilawala** [comment]
@cannin I would like to get work on this. 

@matthiaskoenig Would you mind helping me out working on this ?

**Comment by dipanshug124** [comment]
@cannin @matthiaskoenig, Could you please guide me on how to get started with this project as a GSOC participant.

**Comment by RATED-R-SUNDRAM** [comment]
@matthiaskoenig I Would like to work on this project . It would be very helpful if you guide me how to start on this project.

**Comment by matthiaskoenig** [comment]
Hi @dipanshug124 and @RATED-R-SUNDRAM,
could you send me a email with a bit of background information (short CV and some information about you)?

**Comment by matthiaskoenig** [comment]
@HarshKhilawala
Could you send me a email with a bit of background information (short CV and some information about you)?

**Comment by Jarvis-BITS** [comment]
@matthiaskoenig @cannin 
I have mailed you my resume. Would contribute and start working.

**Comment by pgleeson** [comment]
@matthiaskoenig FYI This model can be mapped into NeuroML2/LEMS format too from SBML with https://github.com/NeuroML/jNeuroML:

jnml -sbml-import BIOMD0000000012_url.xml 1000 0.1
jnml BIOMD0000000012_url_LEMS.xml  

<img width="586" alt="Screenshot 2021-01-21 at 10 55 22" src="https://user-images.githubusercontent.com/1556687/105341587-30d08400-5bd7-11eb-9ad9-ab8ceb4678ed.png">

**Comment by dipanshug124** [comment]
@matthiaskoenig I mailed you my CV. Please have a look at my background work and skills. I'll be waiting for your reply for further process and guidance.

**Comment by HarshKhilawala** [comment]
@matthiaskoenig Please update me on this. Mail has been sent out to you.

**Comment by RATED-R-SUNDRAM** [comment]
@matthiaskoenig I have also mailed you it would be very nice if you could update me

**Comment by matthiaskoenig** [comment]
@all It is great to see so much interest in the issue. In the end only 1 person can be funded per project! So on this project the competition will be likely be hard whereas other issues here have no candidates yet. If you have a second project you are interested in I recommend to get in contact with the mentors.
I don't want to discourage you, but we cannot help writing 10 proposals but at most 2. So there has to be some pre-selection on this issue. 

Sorry for the slow reply, I am creating a google form to collect the information from you and then @cannin have to make some pre-selection. Of course everybody is free to submit a proposal, but at least me cannot support all of you writing proposals. So please have a look at other issues in here ;)

**Comment by matthiaskoenig** [comment]
@all A good starting point to get a feeling for the project would be to create a python virtual environment and install the required libraries. I would then recommend to play a bit with the example files and libraries, i.e. reading and printing the information.

The following pip packages can be used:
- SBML: `python-libsbml` https://pypi.org/project/python-libsbml/
- SBGN: `libsbgnpy` https://pypi.org/project/libsbgnpy/
- SED-ML: `python-libsedml` https://pypi.org/project/python-libsedml/
- Combine Archive: `python-libcombine` https://pypi.org/project/python-libcombine/
- NeuroML: `libNeuroML` https://pypi.org/project/libNeuroML/ and pyNeuroML `https://pypi.org/project/pyNeuroML/
Use python 3.8.

Example files are linked here in the issue (above).

@nickerso Could you post a link to the repressilator in CellML (physiome repository) and the pip package for CellML?

**Comment by shaliniiit** [comment]
@matthiaskoenig  I have gone through the code and the issue and feel like its a good fit for me having worked on similar projects in other universities like Penn State and CMU. I'd be happy to start working. Please look up my resume: https://drive.google.com/file/d/1pcqymg8_DTuCQTTV8cUyEfISpvD63Jlq/view?usp=sharing

**Comment by avinash14022002** [comment]
@matthiaskoenig and @cannin Sir.

Wanted to work for the issue can guide me how to start working??

**Comment by cannin** [comment]
@avinash14022002 see the comment by matthiaskoenig

**Comment by khanspers** [comment]
Cleanup in preparation for GSoC 2022.
