### ISSUE TITLE
Java support for Deviser, a code generation system for SBML libraries

### ISSUE THREAD

**Issue by niko-rodrigue** [nrnb/GoogleSummerOfCode#18]
### Background

[SBML](http://sbml.org) belongs to the most frequently used modeling formats in systems biology. [SBML Level 3](http://sbml.org/Documents/Specifications#SBML_Level_3_Version_1_Core) is being developed as a modular format with optional [SBML Level 3 packages] (http://sbml.org/Documents/Specifications#SBML_Level_3_Packages) being available to extend the focus of the core SBML representation. Both API libraries for working with SBML, [libSBML](http://sbml.org/Software/libSBML) and [JSBML](http://sbml.org/Software/JSBML), provide code that facilitates the use of the various Level 3 packages. [Deviser] (https://github.com/sbmlteam/deviser) is a new code generation system being developed to facilitate the development of SBML L3 packages by helping to automate the generation of specifications, [UML](https://en.wikipedia.org/wiki/Unified_Modeling_Language) diagrams and library code. The code generator currently targets  [libSBML] (http://sbml.org/Software/libSBML) only.  Deviser uses an [XML](https://en.wikipedia.org/wiki/XML) description of an SBML L3 package to provide the information necessary to generate the output it does. 

### Goal

Extend Deviser's code generator to produce Java code that can be integreated into JSBML, the pure Java API library for SBML. This will allow Deviser to target both libSBML and JSBML.

### Technologies

Deviser is written in [Python](https://en.m.wikipedia.org/wiki/Python_(programming_language)) and can be invoked via command-line or a purpose built graphical user interface. A different language could be used to write the JSBML code generator, as long as the starting point was the same XML description file and the resulting code generator can still be easily incorporated into Deviser.

### Potential Mentors

Sarah Keating, Frank Bergmann, Nicolas Rodriguez, Andreas Dräger

### Contact

[SBML Team](mailto:sbml-team@caltech.edu)

Useful pointers to documentation related to GSOC for student on the main NRNB web site :
* [Resources](http://nrnb.org/gsoc.html)
* [How to apply](http://nrnb.org/gsoc.html#apply-tab)

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
