### ISSUE TITLE
Transform Xconnector python package to shiny web app 

### ISSUE THREAD

**Issue by Proteomicslab57357** [nrnb/GoogleSummerOfCode#181]
### Background

Xconnector is a software package designed to easily retrieve, and visualize metabolomics data from different database sources. The goal of Xconnector is to connect different metabolomics databases in one place. The first five databases implemented in Xconnector are:

1. The Human Metabolome Database [HMDB](http://www.hmdb.ca/).
2. The Livestock Metabolome Database [LMDB](http://lmdb.ca/).
3. The Yeast Metabolome Database [YMDB](http://www.ymdb.ca/).
4. The Toxin and Toxin Target Database [T3DB](http://www.t3db.ca/).
5. ReSpect for Phytochemicals DataBase [ReSpect](http://spectra.psc.riken.jp/).
6. KEGG: Kyoto Encyclopedia of Genes and Genomes [KEGG](https://www.genome.jp/kegg/).
7. The Small Molecule Pathway Database [SMPDB](http://smpdb.ca/).

### Workflow 

![](https://raw.githubusercontent.com/Proteomicslab57357/Xconnector/master/image/Untitled%20Diagram%20(1).png)

* This workflow summarizes how Xconnector works. Using a graphical user interface (GUI), the user could import different type of input as database IDs or keyword from a CSV file or text file. Then send it to the application programming interface (API), the API connect one or all databases to retrieve and parse the information that made hits with the user input. Finally, the API send it back to the GUI to be displayed for the user.
### Goals

1 - Convert Xconnector python package to the R script
2 - Run Xconnector as a shiny web application 
3 - Include small databases in Xconnector

### Skills
Essential skills: Python, R, Shiny ,CSS, HTML, JavaScript

### Public Repository
[Xconnector at GitHub](https://github.com/Proteomicslab57357/Xconnector).

### Potential Mentors

[Sameh Magdeldin](https://github.com/samehmgd) 
Email: Sameh.Magdeldin@57357.org
[Proteomics lab](https://github.com/Proteomicslab57357) 
Email: Proteomicslab2017@gmail.com

**Comment by patelaryan7751** [comment]
Hello @Proteomicslab57357 great project! Can you give more info on this project?

**Comment by spursbyte** [comment]
Hello @Proteomicslab57357 can i work on this issue?

**Comment by Proteomicslab57357** [comment]
Yes Sure, it's an application of bioinformatics in metabolomics that will
facilitate data retrieving and visualization from multiple sources.

**Comment by Proteomicslab57357** [comment]
For everyone interested in the project, please send your CV and school report to the mentors.
Also, please check the repo of the project and take a deeper look at the code.

**Comment by spursbyte** [comment]
What do you mean by school report can you elaborate?

**Comment by Proteomicslab57357** [comment]
@spursbyte college transcript

**Comment by spursbyte** [comment]
@Proteomicslab57357 will a college id card help? Since i am currently pursuing my btech (2nd year) my college provides transcript only after 4 years of study or byech completion.

**Comment by Proteomicslab57357** [comment]
@spursbyte yes it will

**Comment by Proteomicslab57357** [comment]
Sure, will do that.

**Comment by khanspers** [comment]
Closing this because of unclear connection to NRNB.
