### ISSUE TITLE
Implement pySBOL3 validation rules

### ISSUE THREAD

**Issue by jakebeal** [nrnb/GoogleSummerOfCode#182]
### Background
[pySBOL3](https://github.com/SynBioDex/pySBOL3) is one of the main libraries implementing the SBOL3 standard. The [SBOL3](https://sbolstandard.org/) standard has a set of rules for checking the validity of documents, but these are currently only partially implemented. The rule implementation is spread between pySBOL3 itself and the SHACL rules contained in [sbol-shacl](https://github.com/SynBioDex/sbol-shacl)

### Goal
The result of this project would be to implement most or all of the validation rules that have not yet been implemented.

### Difficulty Level: Easy
The rules are very well defined and can be implemented incrementally.

### Size and Length of Project
- **350 hours**
- timeline is flexible; 12 weeks preferred, 22 weeks acceptable.

### Skills
Essential skills: Python
Will be learned if not known: RDF, SBOL, SHACL

### Public Repository
[pySBOL3](https://github.com/SynBioDex/pySBOL3)

### Potential Mentors
jakebeal@ieee.org, @tcmitchell, Bryan.A.Bartley@raytheon.com

**Comment by Omarelsherif010** [comment]
Hi @jakebeal, @tcmitchell,
I am Omar Elsherif and I am a medical informatics third-year undergraduate student. I have good experience using python for two years. I learned data analysis from Udacity and built some projects which you can find [here](https://github.com/Omarelsherif010/loans_data_visualization). I am interested in machine learning, and deep learning so I learned them during the last two years from DataCamp and joined Neuromatch Academy as an interactive student in which we used python so much. I am working as a research assistant on a research paper in computational neuroscience and we are about to publish our work soon.

I think I am good with python and I feel easy going through different python libraries to do specific tasks, but I have no experience with RDF, SBOL, and SHACL. So please if you can, recommend some resources to start with in order to start working on this project for GSOC 22.
Thanks for your time

**Comment by jakebeal** [comment]
@Omarelsherif010 A good starting point for familiarization with this material is [the SBOL tutorial material on the data model and Python library that was presented at IWBDA 2021](https://github.com/SynBioDex/Community-Media/tree/master/2021/IWBDA21).

**Comment by Omarelsherif010** [comment]
Thanks for sharing this @jakebea, I am working on the tutorials

**Comment by Omarelsherif010** [comment]
Hi @jakebeal, I have read [SBOL tutorials](https://github.com/SynBioDex/Community-Media/tree/master/2021/IWBDA21) you recommended and successfully build components and add them to a document as the tutorial asked.
Also, I have watched these lectures on YouTube: [Programming biology – controlling the flow of molecular machines empowering life (IWBDA 2021)](https://www.youtube.com/watch?v=gyOI7FmXflg), [SBOL Visual: Diagrams for Synthetic Biology (COMBINE 2020)](https://www.youtube.com/watch?v=88V9xXVNo3Y) and [Webinar for SBOL Developers
](https://www.youtube.com/watch?v=GtDttQX4_z4) .
Now I have a good understanding of SBOL and the development of its data model from SBOL to SBOL2 and finally SBOL3. Besides that I have read this paper: [The Synthetic Biology Open Language (SBOL) Version 3: Simplified Data Exchange for Bioengineering](https://www.frontiersin.org/articles/10.3389/fbioe.2020.01009/full). 

I have found this workshop playlist: [IWBDA 2021](https://www.youtube.com/watch?v=8xPPPAKfNc4&list=PLCz_DtgdrrHWFNegmA72p3thDrl0oMrkb). Do you recommend starting watching it or do you have other suggestions that will help me improve faster and be ready for our project? 

Thanks for your time and help. I am looking forward to hearing from you.

**Comment by jakebeal** [comment]
@Omarelsherif010 If you would like to become fluent with the code base, I suggest jumping in and starting to use the code. One great way to do that would be to take a look at some of the [issues on pySBOL3 that are marked as "good first issue"](https://github.com/SynBioDex/pySBOL3/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) and see if you can make contributions to resolve them.

**Comment by Omarelsherif010** [comment]
Thanks a lot. I will definitely do that.

**Comment by khanspers** [comment]
NRNB has officially been accepted as a mentoring organization for GSoC 2022! Here are some useful links:

- [Project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
- [GSoC contributor guide](https://google.github.io/gsocguides/student/)
- [Program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by Omarelsherif010** [comment]
That is great news. I will start working on my proposal for this project as soon as possible. I am really excited to start the process.

**Comment by tcmitchell** [comment]
@Omarelsherif010 please let us know if you need additional info for your proposal.

**Comment by tcmitchell** [comment]
Here are some links from the GSoC Mentors mailing list that might be generally helpful to all who are interested in this project:
* [Naman Gera's Quora post](https://www.quora.com/How-can-I-apply-and-prepare-for-Google-Summer-of-Code/answer/Naman-Gera-11?ch=15&oid=238449657&share=ec4f0e17&srid=54exj&target_type=answer)
* [Sayak Paul's blog post](https://sayak.dev/gsoc-faqs/)

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.

**Comment by khanspers** [comment]
Closing in preparation for GSoC 2023.

**Comment by jakebeal** [comment]
Project is still valid and needed: reopening for 2023

**Comment by Omarelsherif010** [comment]
Hi @jakebeal 

I hope you are doing well. I am still interested to participate in this project and implement validation rules for SBOL documents. I have good experience in python and unit testing. I also used pySBOL3 during the last few months to create SBOL3 files in order to test the DNAplotlib version 2 data structure and visualize its components.

Kindly let me the current project state so I can go ahead and create a good draft plan that we can edit together.
I am so excited that this project is still available to participate and I want to start contributing as soon as possible.

**Comment by jakebeal** [comment]
Glad to hear that you are interested, @Omarelsherif010 . The project is still in much the same state it was a year ago: all of the rules exist in the specification, the framework for adding them to the library is in place, and we just need somebody to do the translation from specification to python.

**Comment by Omarelsherif010** [comment]
Great so I need to read the 'Validation Rules' section on [SBOL3 Specifications](https://sbolstandard.org/docs/SBOL3.0.1.pdf) as a first step.

Where can I find the already implemented rules in pySBOL3?
And what do you mean by framework for adding them to the library (_tool to use?_)

If it is a tool I should use, kindly share a link with me.

I am ready to start implementing the rules in early Feb, so for now I need to understand more where to look and what is expected as a result so I can show an example of my implementation and edit based on your recommendation

**Comment by jakebeal** [comment]
@Omarelsherif010 Yes, that section of the specification is what needs to be fully implemented. We want to be able to handle all of the "check-box", "circle", and "star" rules.

The first set (sbol3-101*) are mostly implemented via special case code of various sorts: they are not the primary focus of this project, and might all be done already.

The others are to be implemented via the "validate" function on the appropriate class. Here are two examples:
* https://github.com/SynBioDex/pySBOL3/blob/f3bd880db085ff285bbaa7c6500c9dcc6409c3fe/sbol3/location.py#L29
* https://github.com/SynBioDex/pySBOL3/blob/1353ccb07b57561a566a69486bff6c95cc8be172/sbol3/feature.py#L29

We will also want to create tests that make sure that all of the rules will correctly catch failures. 

A good starting point would be to start working through some of the current tests to make sure that they are actually exercising all of the validation rules that we think they should be. For example, [we test detection of invalid sequences](https://github.com/SynBioDex/pySBOL3/blob/f3bd880db085ff285bbaa7c6500c9dcc6409c3fe/test/test_sequence.py#L23), but don't check if it gives an error for both of the cases.

**Comment by khanspers** [comment]
@Omarelsherif010 : Please note that we (NRNB) are still in the process of applying as a mentoring organization; mentoring organizations will be announced on Feb 22. Check back after that date for more information.

**Comment by Omarelsherif010** [comment]
Thanks @khanspers 
I know the process and timeline of GSoC and I am very excited to work on this project so I will start contributing in early Feb

**Comment by Omarelsherif010** [comment]
@jakebeal I have checked the links you provided and yeah it is clear now to me.
I will start playing with existing tests and then create a test case for one rule and finally implement the validation rule to make the test pass.
I will let you know once I create the test case

**Comment by tcmitchell** [comment]
@Omarelsherif010 if you have any questions, please open an issue on the pySBOL3 repository.

**Comment by Vikash-8090-Yadav** [comment]
@tcmitchell @jakebeal Vikash here , junior at Chandigarh University.  I found this org interesting as this matches with my skill . Looking forward to work with this org . please guide me with the initial steps to be followed while contributing !

**Comment by tcmitchell** [comment]
@Vikash-8090-Yadav : Please note that we (NRNB) are still in the process of applying as a GSoC mentoring organization; mentoring organizations will be announced on Feb 22. Check back after that date for more information.

Please read the comments above for initial steps to be followed while contributing. This GitHub issue is the medium to contact us with any questions about this GSoC project.

**Comment by Omarelsherif010** [comment]
Hi @tcmitchell  and @jakebeal 

I have gone through some of the implemented tests and noticed the feature class validation function doesn't have a unit test, so I [opened this issue](https://github.com/SynBioDex/pySBOL3/issues/420) and am willing to create that one.

If you recommend something else to do, I will be happy to follow your suggestion.

**Comment by khanspers** [comment]
NRNB has been accepted as a mentoring organization for GSoC 2023! Contributor applications open on March 20. Here are some useful links:

[GSoC contributor guide](https://google.github.io/gsocguides/student/)
[NRNB project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
[Eligibility requirements](https://developers.google.com/open-source/gsoc/faq#what_are_the_eligibility_requirements_for_participation)
[Full program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by Omarelsherif010** [comment]
What awesome news, I have finished the code of the first unit test of the rules and will open a PR soon.
I think I will implement couples and see Tom and Jake's reviews, then start the proposal.

**Comment by sumit-158** [comment]
Hi, I have submitted a proposal for GSoC it would be great if you can check this out and give me some feedback.

[NRNB GSoC Contributor Proposal Template.pdf](https://github.com/nrnb/GoogleSummerOfCode/files/11028951/NRNB.GSoC.Contributor.Proposal.Template.pdf)

**Comment by sumit-158** [comment]
Hi, I have submitted the GSoC proposal for this issue. Please provide some feedback.
Thank you!

[Proposal google Doc link](https://docs.google.com/document/d/1yCQYu9uzWnCgrTd1BdO-j--1bVtkRZOViigKRSjCz_w/edit?usp=sharing)
Also added potential mentors as commenters in the doc so you can provide feedback directly in the doc.

**Comment by Omarelsherif010** [comment]
Hi @tcmitchell @jakebeal @bbartley 

I have finished my [Proposal ](https://docs.google.com/document/d/1ouIC_VvA_2c8hDks_URL4vg-VLejnRWGyEpaMdMmSM0/edit?usp=sharing)and added my PRs and detailed timeline plan. Could you please give a final review before submitting?
Also, I need your review on this [PR ](https://github.com/SynBioDex/pySBOL3/pull/426)and this [issue ](https://github.com/SynBioDex/pySBOL3/issues/177)in order to get more into details of pySBOL3 code.

Thanks in advance

I am enjoying the process of getting more in depth with SBOL world step by step, You are really great mentors❤️

**Comment by Omarelsherif010** [comment]
What do you recommend I do until GSoC 23 results?
Should I try to collect validation rules that have not been implemented yet or try to solve more issues inside the library?

Or do you have better suggestions?

**Comment by jakebeal** [comment]
@Omarelsherif010 It is up to you what you choose to do, but the GSoC process is already in motion at this point.

**Comment by princyym** [comment]
Hello, I am Princy Mangla wants to contribute to this project, I have a very good command in Python and eager to learn sbol library and another necessary lib further, could you please assign this issue and explain its technical issues.

**Comment by jakebeal** [comment]
While this project still needs to be done, we have decided that we are not in a good position to supervise a GSoC student on it in summer 2024.
