### ISSUE TITLE
High level abstraction components for pySBOL3

### ISSUE THREAD

**Issue by Gonza10V** [nrnb/GoogleSummerOfCode#184]
### Background
[pySBOL3](https://github.com/SynBioDex/pySBOL3) is one of the main libraries implementing the SBOL3 standard. But  it has not been widely used due to the slow learning curve of SBOL. [SBOL-utilities](https://github.com/SynBioDex/SBOL-utilities) is a collection of scripts and functions for manipulating SBOL 3 data that can be run from the command line or as functions in Python. This set of functions provides a high level abstraction for manipulating SBOL files and can provide a more user friendly environment for developers that would want to use pySBOL3 to write SBOL documents.

A starting point for familiarization with this material is [the SBOL tutorial material on the data model and Python library that was presented at IWBDA 2021](https://github.com/SynBioDex/Community-Media/tree/master/2021/IWBDA21)

### Goal
The result of this project would be to implement most or all the examples on the SBOL 3.0.1 specification that has not been implemented yet.

### Difficulty Level: Easy
The examples are very well defined and can be implemented incrementally.

### Size and Length of Project
- **350 hours**
- timeline is flexible; 12 weeks preferred, 22 weeks acceptable.

### Skills
Essential skills: Python
Will be learned if not known: SBOL

### Public Repository
https://github.com/SynBioDex/SBOL-utilities

### Potential Mentors
jakebeal@ieee.org, tom.mitchell@raytheon.com, Bryan.A.Bartley@raytheon.com

**Comment by RATED-R-SUNDRAM** [comment]
Hi @jakebeal @Gonza10V , I am shivam sundram a 3rd year Undergraduate,  I have 3 years of learning experience and one year of work experience in python, I am willing to contribute to this project for GSoC 2022, any guidance on where to begin and what all to learn would be really encouraging and helpful.

**Comment by Gonza10V** [comment]
Hi @khanspers I have a question here. I dont know if I should be considered a mentor on this project. I am a heavy user of pySBOL3 and SBOL-utilities. I looked for GSoC projects that add the functions that I feel useful to the package and I ended proposing the ones that I want to see implemented and I could contribute to. I have no problems if another participant wants to develop it, I can participate on other needed features but I'm a bit confused because I want to participate as developer on GSoC and not as mentor yet. Is this ok? what should I do?

**Comment by jakebeal** [comment]
@RATED-R-SUNDRAM Glad to hear of your interest - can you please link to something that you consider a good example of your work in Python?

@Gonza10V I believe that you are right able you fitting in well as a contributor and not a mentor at this time. I've got it from here.

**Comment by RATED-R-SUNDRAM** [comment]
@jakebeal I am [liking](https://github.com/RATED-R-SUNDRAM/COLLEGE_BOT.git) to one of my projects here. Please guide me on ways and learning to get started for the project

**Comment by jakebeal** [comment]
@RATED-R-SUNDRAM That does not appear to be your own work, but rather the work of another student.

**Comment by khanspers** [comment]
Hi @Gonza10V, thanks for letting me know, it wasn't clear to me if you were a contributor or mentor, since you opened the issue I assumed mentor. I've removed you from the mentors list.

**Comment by RATED-R-SUNDRAM** [comment]
@jakebeal This was a collaboration of other people on other components, For me individually I've contributed in adding all the python functions and classes as well coded for the preprocessing and training of the data.


In any case, if you want a test of my abilities I am open to any of your test tasks on this or any other repositories

**Comment by pengbingyin** [comment]
Sounds amazing.

**Comment by jakebeal** [comment]
@pengbingyin Glad to hear of your interest - can you please link to something that you consider a good example of your work in Python?

**Comment by Akshat-Kumar-0610** [comment]
Hi, @jakebeal; I am Akshat Kumar looking forward to contributing to this project through GSOC 2022, any suggestions from where to begin and what to learn before contributing to it. Here is my [Github Profile](https://github.com/Akshat-Kumar-0610) and one of my work in python which I would like to [show](https://github.com/Akshat-Kumar-0610/HostelAllotmentBITSDVM)

**Comment by jakebeal** [comment]
@Akshat-Kumar-0610 The link that you provided is giving a "page not found" error for me: is it one of your private repositories?

**Comment by Akshat-Kumar-0610** [comment]
@jakebeal  I am really sorry, I can't make it public. I have given you contributor access to check it out.

**Comment by pengbingyin** [comment]
> @pengbingyin Glad to hear of your interest - can you please link to something that you consider a good example of your work in Python?

We would like to extract promoters and terminators from S. cerevisiae and Y. lipolytica genome sequence basing on genome annotation, RNA seq, and Chip seq data. Also, we would like to test the promoters to verify their activities for a part library. I am wondering as well that whether we can develop a mySQL database on AWS.

**Comment by jakebeal** [comment]
@Akshat-Kumar-0610 Thank you; I have had a chance to look at your work, and it seems you are in a reasonable starting point for this project in terms of your Python knowledge.

If you would like to familiarize yourself with the material for the project, I would suggest going through the [SBOL tutorial material on the data model and Python library that was presented at IWBDA 2021](https://github.com/SynBioDex/Community-Media/tree/master/2021/IWBDA21).  I will add this to the top issue as well.

**Comment by jakebeal** [comment]
@pengbingyin I'm afraid that I'm a bit confused by your comments. All of what you are saying can be done with SBOL, but is out of scope of this particular project. Are you trying to propose a new project?

**Comment by pengbingyin** [comment]
> @pengbingyin I'm afraid that I'm a bit confused by your comments. All of what you are saying can be done with SBOL, but is out of scope of this particular project. Are you trying to propose a new project

@jakebeal (1) Frankly speaking, I know little to nothing about programming. I will try my best to understand first. I saw your recommendation of BioPython in other track. I will take a look as well. (2) I am trying to start a project in this area to simulate the genetic engineering methods. Yes. I am trying to propose a new project. Can we have a discussion in another chance? (3) I am quite interested in learning SBOL3 utilities, and commend line sounds appealing to me, but due to the limitation of knowledge, I have not yet identified the points I can contribute to. But I am keen to catch up.

**Comment by jakebeal** [comment]
@pengbingyin I understand; this issues isn't the place for brainstorming new projects, but please feel free to reach out to the SBOL community for help as you are getting started on your project.

**Comment by Akshat-Kumar-0610** [comment]
@jakebeal  I went through the tutorial you metioned and also going through SBOL-utilities library mentioned in issue itself. Can you please tell what needs to be done further.

**Comment by jakebeal** [comment]
@Akshat-Kumar-0610 In the SBOL utilities project, there are [a number of issues marked with "good first issue"](https://github.com/SynBioDex/SBOL-utilities/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). I would suggest picking one of these issues and starting to work on your first pull request.

**Comment by ahmedtarek26** [comment]
Hi @cannin, @khanspers
I am Ahmed Tarek and I am a medical informatics 3rd-year undergraduate student. I have good experience using python for two years.
I take a Genetics course at college and did a project using some ML libraries, Biopython, Py3Dmol, and ngl-view which you can find [here](https://github.com/ahmedtarek26/Top-10-Studied-Genes). I am interested in machine learning, and deep learning so I learned them during the last two years from DataCamp and joined Neuromatch Academy as an interactive student in which we used python so much. I am working as a research assistant on a research paper in NLP and we are about to publish our work soon.

I think I am good with python and I feel easy going through different python libraries to do specific tasks and am passionate to work on a new kinds of datasets to start working on this project for GSOC 22.
Thanks for your time

**Comment by khanspers** [comment]
NRNB has officially been accepted as a mentoring organization for GSoC 2022! Here are some useful links:

- [Project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
- [GSoC contributor guide](https://google.github.io/gsocguides/student/)
- [Program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.
