### ISSUE TITLE
Benchling SBOL3 App

### ISSUE THREAD

**Issue by jakebeal** [nrnb/GoogleSummerOfCode#186]
### Background
[Benchling](https://www.benchling.com/) is a popular DNA design tool, but currently supports only SBOL 1 and poorly at that. Benchling also offers a [Python SDK](https://docs.benchling.com/docs/getting-started-with-the-sdk) for accessing their API and the ability to [add apps](https://docs.benchling.com/docs/building-your-first-benchling-app) to extend the capabilities of Benchling. It should thus be possible provide SBOL import and export capabilities in a Benchling app using pySBOL3 and Benchling SDK.

### Goal
This project will produce a Benchling app that can import and export files in SBOL3 format.
Correctness will be validated by round-tripping (import, then export) at least the `Component` and `Sequence` objects in [SBOL3 files from the SBOL test suite](https://github.com/SynBioDex/SBOLTestSuite/tree/master/SBOL3) and by checking that imported materials can be sensibly viewed and edited in Benchling.

### Difficulty Level: Medium
While the overall project is relatively straightforward, it will require figuring out how to use Benchling's SDK and app interfaces.

### Size and Length of Project
- **175 hours**
- Timeline: flexible, length 12 weeks

### Skills

Essential skills: Python
Will be learned if not known: SBOL

### Public Repository
This project will produce a new app in a new open-source repository on GitHub.

### Potential Mentors
Vishwesh V Kulkarni <vvk215@gmail.com>, tom.mitchell@raytheon.com

**Comment by ArchitJain1201** [comment]
Hello @khanspers @jakebeal; I am Archit Jain looking forward to contributing to this project for GSOC 2022, any suggestions from where to begin and what to learn before contributing to it. Here is my Github Profile [GitHub](https://github.com/ArchitJain1201)

**Comment by jakebeal** [comment]
@ArchitJain1201 Glad to hear of your interest; please get in touch with potential mentors who are listed.

**Comment by tcmitchell** [comment]
@jakebeal I corresponded with @ArchitJain1201 about this project and I was unable to provide guidance on Benchling. @ArchitJain1201 did not receive any reply from Vishwesh V Kulkarni. Are there other resources for information on Benchling?
@ArchitJain1201 has also expressed interest in [Conversion between GenBank and SBOL3](#183) #183

**Comment by jakebeal** [comment]
@ArchitJain1201 If you are interested in learning more in advance, I would suggest either 1) familiarizing yourself with the Benchling interface by following their "build your first app" tutorial, and/or 2) familiarizing yourself with SBOL via the tutorials.

**Comment by khanspers** [comment]
NRNB has officially been accepted as a mentoring organization for GSoC 2022! Here are some useful links:

- [Project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
- [GSoC contributor guide](https://google.github.io/gsocguides/student/)
- [Program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by tcmitchell** [comment]
Here are some links from the GSoC Mentors mailing list that might be generally helpful to all who are interested in this project:
* [Naman Gera's Quora post](https://www.quora.com/How-can-I-apply-and-prepare-for-Google-Summer-of-Code/answer/Naman-Gera-11?ch=15&oid=238449657&share=ec4f0e17&srid=54exj&target_type=answer)
* [Sayak Paul's blog post](https://sayak.dev/gsoc-faqs/)

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by khanspers** [comment]
Closing in preparation for GSoC 2023.

**Comment by jakebeal** [comment]
Project is still valid and needed: reopening for 2023

**Comment by HarshRathi2511** [comment]
@tcmitchell @jakebeal @VishweshGitHub 
Hello there, I'm Harsh Rathi writing to express my interest in contributing to the SBOL project as a part of the Google Summer of Code program. I have worked decently in Python and I am excited to work on this project and learn more about it. Could you provide me with the resources and necessary theory for getting familiar with the codebase of SBOL,
so that I can start contributing . Here is my [Github](https://github.com/HarshRathi2511/) profile .

**Comment by jakebeal** [comment]
I would suggest starting by familiarizing yourself with [pySBOL3](https://github.com/SynBioDex/pySBOL3) and [SBOL-utilities](https://github.com/SynBioDex/SBOL-utilities). There is a good tutorial that you can use as a starting point at: https://github.com/SynBioDex/Community-Media/tree/master/2022/IWBDA22/sbol3-workshop

The other side of this will be connecting with[ Benchling's API](https://docs.benchling.com/docs/developer-platform-overview), As a student, you should be able to get access to Benchling with a free academic license.

**Comment by khanspers** [comment]
@HarshRathi2511 : Please note that we  (NRNB) are still in the process of applying as a mentoring organization; mentoring organizations will be announced on Feb 22. Check back after that date for more information.

**Comment by HarshRathi2511** [comment]
@khanspers Noted. 
@jakebeal  Thanks a lot . I'll have a look at this .

**Comment by khanspers** [comment]
NRNB has been accepted as a mentoring organization for GSoC 2023! Contributor applications open on March 20. Here are some useful links:

[GSoC contributor guide](https://google.github.io/gsocguides/student/)
[NRNB project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
[Eligibility requirements](https://developers.google.com/open-source/gsoc/faq#what_are_the_eligibility_requirements_for_participation)
[Full program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by HarshRathi2511** [comment]
Also @jakebeal @tcmitchell @VishweshGitHub can you suggest me some good issues to work that'll help me understand the product better.

**Comment by jakebeal** [comment]
@HarshRathi2511 Apologies for the slow reply - this is the right way to connect with us, but @tcmitchell and I have both been unavailable for a few days.

With regards to the Benchling API key: that is indeed mysterious. I've gotten in touch with their customer support, and will see about getting an answer. One way or another, I think we should be able to obtain you an API key.

In the mean time, to familiarize yourself with the SBOL side of the code base, I would suggest picking 1-2 issues from the "good first issues" tags on [pySBOL3](https://github.com/SynBioDex/pySBOL3/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or [SBOL-utilities](https://github.com/SynBioDex/SBOL-utilities/labels/good%20first%20issue) and trying to make a patch to fix them. That will help familiarize you with the code you'll be using, how to test the software, and how we review contributions coming into the project.

**Comment by jakebeal** [comment]
@HarshRathi2511 : Unfortunately, Benchling has told me that your problem is deliberate. Apparently, they are not allowing academics to use their API. Unfortunately, I think this means that this is no longer appropriate as an open source project: even though the SDK has an Apache license, one cannot actually use the library without a cost license. I am thus going to close this issue as a non-viable GSoC project. 

Would you be interested in one of the other SBOL-related projects?
Projects #187 and #215 are also format conversion projects, but work directly with files rather than depending on a closed API.

**Comment by HarshRathi2511** [comment]
@jakebeal Thanks for letting me know. I'm interested in the Snap Gene /SBOL3 integration
