### ISSUE TITLE
Adding visualization of protein-complex interaction to openPIP

### ISSUE THREAD

**Issue by MoHelmy** [nrnb/GoogleSummerOfCode#188]
### OVERVIEW
The [Open Source Protein Interaction Platform (openPIP)](http://baderlab.org/Software/openPIP) is an open-source software package for hosting protein-protein interaction (PPI) data based on the [PSI-MI-TAB format](https://code.google.com/archive/p/psimi/wikis/PsimiTab27Format.wiki). openPIP provides a PPI database and a customizable web interface that enables searching and visualizing the interactions as well as downloading the search results in different formats. The whole system is a ready-to-use virtual machine that can be imported to VMware. openPIP was used to build the portals f two major PPI project, [The Human Reference Protein Interactome Mapping (HuRI) Project](http://www.interactome-atlas.org/) ([Luck at el, Nature, 2020](https://www.nature.com/articles/s41586-020-2188-x)) and [The Yeast Protein Interactome Mapping (YeRI) Project](http://yeast.interactome-atlas.org/) (Under review).

### Focus
This project aims to add several new features  and enhancements to openPIP.

### Goals
1- Adding visualization of protein complex interactions. We had made a prototype in a previous GSoC project. It needs to be finished.
2- Adding default download options through the automatic creation of download link for each interactions dataset or interactions from the same publication).
3- Adding a custom download option (similar to STRING).
4- Adding organism level: so far, openPIP can host multiple datasets from different sources and in the search results it keeps track of all the differences (publishes/unpublished, experimental/predicted...). However, they are all from the same organism. We need to add support to the use in the use case of hosting interactions from different organisms.
5- Test and refine the setup process for new instances e.g. hosting the docker
container on DockerHub for more convenient access.

### Coding Skills
PHP, JavaScript, HTML/CSS, Symfony

### Acceptance Criteria
Students interested in working on this project will be asked to provide their CV and school transcript then the short-listed students will be asked to do an evaluation task that will be used for assessing their fitness for the project.

### Public Repository
[openPIP at GitHub](https://github.com/BaderLab/openPIP)

### Size and Length of Project
- **175 hours**
- **Timeline: flexible, length 12 weeks**

### Mentors
[Gary Bader](mailto:Gary.Bader@utoronto.ca), [Mohamed Helmy](mailto:mohamed_helmy@bii.a-star.edu.sg)

**Comment by alvinuday** [comment]
Hi Sir,
my name is Alvin Adarsh Kumar , I'm a second year CS undergrad with prior experience in front end development with HTML,CSS,JS , React and Vue. I wanted work on this issue with an enthusiasm to learn as well. I was hoping you could guide me further as to how i could get started with this issue?

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by khanspers** [comment]
Closing because this is an active project for GSoC 2022.
