### ISSUE TITLE
Improve the generation and customization of the analysis report of GeneCloudOmics

### ISSUE THREAD

**Issue by MoHelmy** [nrnb/GoogleSummerOfCode#189]
### OVERVIEW
[GeneCloudOmics](http://combio-sifbi.org/GeneCloudOmics/) GeneCloudOmics an easy-to-use web server for high-throughput gene expression analysis a comprehensive range of data analytics tools in one package that no other current standalone software or web-based tool can do currently). GeneCloudOmics allows both microarray and RNA-Seq data analysis with a comprehensive range of data analytics tools in one package that no other current standalone software or web-based tool can do. In total, GeneCloudOmics provides the user access to 23 different data analysis and bioinformatics tasks including reads normalization, scatter plots, linear/non-linear correlations, PCA, clustering (hierarchical, k-means, t-SNE, SOM), differential expression analyses, pathway enrichments, evolutionary analyses, pathological analyses, and protein-protein interaction (PPI) identifications [Helmy _et al_, **Frontiers in Bioinformatics**, 2021]( http://combio-sifbi.org/GeneCloudOmics/).

### Focus
Currently, GeneCloudOmics generates a report that contains the results of the analysis done by the user and this report is customizable and can be saved in PDF format. This project aims to improve the generation and customization of the analysis report of GeneCloudOmics.

### Goals
1- Improve the way the user adds components to the report.
2- Enhance the report generation. 
3- Improve the report’s format.
4- Improve the saved PDF to be in pages (page per result).
5- Add more saving formats for publication-ready graphics (TIFF, PNG, SVG).

### Coding Skills
R programming,  Shiny, JavaScript, HTML/CSS

### Acceptance Criteria
Students interested in working on this project will be asked to provide their CV and school transcript then the short-listed students will be asked to do an evaluation task that will be used for assessing their fitness for the project.

### Size and Length of Project
- **175 hours**
- **Timeline: flexible, length 12 weeks**

### Public Repository
[GeneCloudOmics at GitHub]( https://github.com/MoHelmy/GeneCloudOmics)

### Mentors
[Mohamed Helmy](mailto:mohamed_helmy@sifbi.a-star.edu.sg)
[Kumar Selvarajoo](mailto:kumar_selvarajoo@bii.a-star.edu.sg)

### Our Lab website
[The COMPUTATIONAL BIOLOGY AND OMICS GROUP](http://combio-sifbi.org)
Bioinformatics Institute (BII), A*STAR]

**Comment by KundeyVishwanath** [comment]
My name is Kundey Vishwanath and I am a second-year undergraduate student majoring in Computer Science Engineering . I am very much interested in joining this project for the summer and making contributions and my fully efforts to the code. In terms of development I am familiar with HTML, CSS, JS, R, shiny, Python, Java , C++, MERN stack. I have experience in  data analysis and data visualization  of Bio-Informatics projects  and I strongly believe  my skill set would fit this project perfectly. I am interested to create a improvised version of GeneCloudOmics. Please let me know how I can get started I am very excited to be part of this project.

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by khanspers** [comment]
Closing because this is an active project for GSoC 2022.
