### ISSUE TITLE
Offline SBML validation in the Java-based JSBML library

### ISSUE THREAD

**Issue by niko-rodrigue** [nrnb/GoogleSummerOfCode#19]
### Background

[SBML](http://sbml.org) is one of the most popular modeling and data exchange languages in systems biology.  In order to ensure reproducibilty of model simulation results, SBML files need to be carefully validated against the SBML specifications. The different SBML specifications (core + many packages) define a set of validation rules that go beyond  simple [XML](https://en.wikipedia.org/wiki/XML) schema validation.  (For examples, see the list of [error categories](http://sbml.org/Facilities/Documentation/Error_Categories) or section 'A' of the [SBML Level 3 core specification](https://sourceforge.net/projects/sbml/files/specifications/Level%203%20Ver.%201/sbml-level-3-version-1-core-rel-1.pdf/download?use_mirror=kent)). The current validation done by the [JSBML](http://sbml.org/Software/JSBML) library is performed via network access to the [web services on SBML.org](http://sbml.org/Facilities/Validator), but this is problematic when the user has no network connection or is on a very slow network.

### Goal

Add a validation system to JSBML that implements the necessary validation rules directly in the library, without requiring the use of a network. We do not ask for complete coverage of the SBML validation rules; it would be enough to implement a significant subset, such as some or all of the core SBML validation rules. The approach implemented in this project should provide the infrastructure to easily add more validations rules. 

### Technologies

There already exists preliminary work done using [RELAX NG](https://en.wikipedia.org/wiki/RELAX_NG) and [Schematron](https://en.wikipedia.org/wiki/Schematron). This could be used as the starting point for the validation system in JSBML. Another option would be to create a pure Java validation framework of some kind, following a similar structure as is done in [libSBML](http://sbml.org/Software/libSBML).  Some preliminary work in the latter direction has been done in the JSBML implementation of the SBML [Arrays package](http://sbml.org/Documents/Specifications/SBML_Level_3/Packages/arrays). This could serve as a possible inspiration or starting point.

### Potential Mentors

Sarah Keating, Nicolas Rodriguez, Andreas Dräger

### Contact

[JSBML developers] (mailto:jsbml-development@googlegroups.com) mailing list, available online at https://groups.google.com/d/forum/jsbml-development.

Useful pointers to documentation related to GSOC for student on the main NRNB web site :
* [Resources](http://nrnb.org/gsoc.html)
* [How to apply](http://nrnb.org/gsoc.html#apply-tab)

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
