### ISSUE TITLE
Create Jupyter Notebooks Showcasing COMBINE Standards

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#192]
### Background
The "Computational Modeling in Biology" Network (COMBINE, http://co.mbine.org/standards) is an initiative to coordinate the development of the various community standards and formats in systems biology and related fields.

### Goal
The goal is to produce a Python Google Colab (https://colab.research.google.com/) notebook (or several) that showcases these standards and their libraries around a common theme; the repressilator (https://pubmed.ncbi.nlm.nih.gov/10659856/). A number of the standards SED-ML, SBML, SBOL, SBGN, both have Python libraries and existing models based on the repressilator. The idea is to build a notebook utilizing these different representations of a repressilator. 

#### Additional Goals
* Any usage issues with the use of respective libraries will be addressed (or reported) to developers for later follow-up.
* As time permits, other COMBINE standards may be added. 

### Difficulty Level: Easy
The project will require learning a number of tools quickly. 

### Size and Length of Project
Size: **175 hours**
Length: 12 weeks

### Skills
* Essential skills: Python
* Nice to have skills: Java

### Public Repository
* SBML: http://sbml.org/, https://tellurium.readthedocs.io
* SBGN (Python): https://github.com/matthiaskoenig/libsbgn-python
* SED-ML: https://sed-ml.org/

#### Repressilator
* SBML: https://www.ebi.ac.uk/biomodels/BIOMD0000000012
* SED-ML: https://tellurium.readthedocs.io/en/latest/_notebooks/core/tesedmlExample.html, https://sed-ml.org/examples.html
* SBGN: http://web.newteditor.org/# (see File -> Samples)

### Potential Mentors
[Augustin Luna](mailto:aluna@jimmy.harvard.edu)
Matthias König

**Comment by Omarelsherif010** [comment]
Hi @cannin ,
I am Omar Elsherif, I am a third-year medical informatics undergraduate student. I have good experience using python for machine learning and data analysis. I also use Google Colab to run my code. I want to work on this project for GSoC 22 so If you have some recommendations to start, kindly tell me in order to start right away

**Comment by matthiaskoenig** [comment]
Hi @Omarelsherif010 
I recommend having a look at the COMBINE standards first.
There is some high level introduction in the following publications:

> Schreiber F, Gleeson P, Golebiewski M, Gorochowski TE, Hucka M, Keating SM, König M, Myers CJ, Nickerson DP, Sommer B, Waltemath D. Specifications of standards in systems and synthetic biology: status and developments in 2021. J Integr Bioinform. 2021 Oct 22;18(3):20210026. doi: 10.1515/jib-2021-0026. PMID: 34674411; PMCID: PMC8573232. https://pubmed.ncbi.nlm.nih.gov/34674411/

>Waltemath D, Golebiewski M, Blinov ML, Gleeson P, Hermjakob H, Hucka M, Inau ET, Keating SM, König M, Krebs O, Malik-Sheriff RS, Nickerson D, Oberortner E, Sauro HM, Schreiber F, Smith L, Stefan MI, Wittig U, Myers CJ. The first 10 years of the international coordination network for standards in systems and synthetic biology (COMBINE). J Integr Bioinform. 2020 Jun 29;17(2-3):20200005. doi: 10.1515/jib-2020-0005. PMID: 32598315; PMCID: PMC7756615. https://pubmed.ncbi.nlm.nih.gov/32598315/

>Hucka M, Nickerson DP, Bader GD, Bergmann FT, Cooper J, Demir E, Garny A, Golebiewski M, Myers CJ, Schreiber F, Waltemath D, Le Novère N. Promoting Coordinated Development of Community-Based Information Standards for Modeling in Biology: The COMBINE Initiative. Front Bioeng Biotechnol. 2015 Feb 24;3:19. doi: 10.3389/fbioe.2015.00019. PMID: 25759811; PMCID: PMC4338824.

And information on the webpage about COMBINE
http://co.mbine.org/
After having a high level view on what COMBINE is and the different standards are we can go more in the details. 
Let me know if you have any questions. 
Best Matthias

**Comment by Kartikkp07** [comment]
Hi @cannin ,
I am Kartik Kumar Pawar, a CSE sophomore at BITS PILANI. I have good experience using python for about 6 years.I am also adept in JAVA with knowledge of OOPS and basic design patterns,I have also worked with both SQL and NoSQL database systems.I am really excited to know more about this project and contribute to it, with the aim of becoming a GSOC 22 contributor as well.
I kindly request you to guide me for the same so I can start as soon as possible.

**Comment by matthiaskoenig** [comment]
Hi @Kartikkp07 and @Omarelsherif010,

if you are still interested in working on this please get into contact via email as soon as possible to plan further steps and writing the project proposal. Please write via konigmatt@googlemail.com, I will keep @cannin in the loop.

Best Matthias

**Comment by khanspers** [comment]
NRNB has officially been accepted as a mentoring organization for GSoC 2022! Here are some useful links:

- [Project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
- [GSoC contributor guide](https://google.github.io/gsocguides/student/)
- [Program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by aditya-ml** [comment]
Hi @matthiaskoenig and @cannin,

I am Aditya, a graduate student pursuing MSc in Computer Science at Lakehead University, Ontario, Canada. My research focuses on NLP-based approaches for analyzing social media and healthcare. 

I am interested in contributing to this project. I have extensive experience implementing python for NLP in google colab and I have read through the papers suggested here to get an overview of COMBINE. 

Please take a moment to review my portfolio links below, and I would greatly appreciate the opportunity to discuss my candidacy for this project.

Best regards,
Aditya Singhal
Website: [https://aditya-ml.github.io/](url)
LinkedIn: [https://www.linkedin.com/in/asinghal-a1/](url)

**Comment by matthiaskoenig** [comment]
In addition:
- CellML & NeuroML: additional modeling languages
- COMBINE archive: library to store simulation studies
- pyomex: low level library for annotations

Use 2 example models:
- repressilator: https://www.ebi.ac.uk/biomodels/BIOMD0000000012; https://www.ebi.ac.uk/biomodels/content/model-of-the-month?year=2006&month=07

**Comment by matthiaskoenig** [comment]
Hi all,

we have a highly motivated student who will submit a proposal for this project and started the community binding.
I recommend for other GSOC contributors to select a different project from NRNB (https://github.com/nrnb/GoogleSummerOfCode/issues).

Best Matthias

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.

**Comment by khanspers** [comment]
Closing because this is an active project for GSoC 2022.
