### ISSUE TITLE
NetBoxR Updates: Develop a Galaxy Platform Entry for NetBoxR, Pipeline for Processing cBioPortal Data, and Module Analysis Features

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#193]
### Background
netboxr (https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0234669) is an R package for the automated discovery of biological process modules by network analysis. 

### Goals
This project has multiple goals (proposals should discuss at least 2 of these; they are ordered from most to least important): 

* Add additional analysis features into netboxr, specifically (the following). This additionally will involve making use of module (community) detection algorithms in igraph (https://igraph.org/r/html/latest/communities.html)

  1. The ability to support weighted nodes in the module detection 
  2. The ability to parameterize the sizes of returned modules 

* Make netboxr more widely available. The Galaxy platform (https://galaxyproject.org/) is a platform to make tools more widely available. The goal would be to make netboxr available on Galaxy (https://galaxyproject.org/admin/tools/add-tool-tutorial/). 
* Process datasets from cBioPortal with netboxr (https://github.com/cBioPortal/datahub/tree/master/public) following the package vignette (https://bioconductor.org/packages/release/bioc/vignettes/netboxr/inst/doc/netboxrTutorial.html).

#### Getting Started
Eventually, you'll need to write a proposal (see details: https://nrnb.org/gsoc). Elements of this proposal should include:

1. Demonstrated understanding (code samples help) of what steps are involved in making a Galaxy tool 
2. Try out netboxr on different sets of data from cBioPortal given the instructions in the tutorial
4. An understanding of the igraph community methods 

##### Getting Help
Post issues if you encounter bugs in the tutorial here: https://github.com/mil2041/netboxr/issues

### Difficulty Level: Easy
Navigating the documentation for the Galaxy platform may have some difficulty. 

### Size and Length of Project
Size: **175 hours**

Length: 12 weeks

### Skills
* Essential skills: R, XML 

### Public Repository
* https://github.com/mil2041/netboxr

### Potential Mentors
[Augustin Luna](mailto:aluna@jimmy.harvard.edu)
Eric Minwei Liu

**Comment by cannin** [comment]
@sajo25 Thanks for the interest. Take a look the "Getting Started" section above.

**Comment by pramit026** [comment]
Hi @cannin , I am Pramit and i'm currently pursuing Bachelor's in Pharmaceutical Technology and i want to contribute to this project.. can you please guide me ?

**Comment by cannin** [comment]
@pramit026 Look at the "Getting Started" section.

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.

**Comment by khanspers** [comment]
Closing because this is an active project for GSoC 2022.
