### ISSUE TITLE
Updates to the Enrichment Table App

### ISSUE THREAD

**Issue by AlexanderPico** [nrnb/GoogleSummerOfCode#199]
### Background
[Cytoscape](http://www.cytoscape.org) is a highly popular open source bioinformatics software platform for visualizing, analyzing, and publishing graphs or networks representing molecular interactions, gene expression, other biological data. As a desktop platform, Cytoscape is one of the most successful open source projects in biology, and it is capable of integrating observational data from numerous sources. 

Previously, when users are working with a network of connected genes or proteins, they have to use external web tools to perform simple enrichment analyses, e.g., using [g:Profiler](https://biit.cs.ut.ee/gprofiler/gost). However, g:Profiler provides a web service interface, so we now provide access to this same service from _within_ Cytoscape via the [Enrichment Table app](https://github.com/cytoscape/enrichment-table-app/). More advanced tools for enrichment already exist as Cytoscape apps, such as BiNGO and ClueGO. The goal here is to keep it simple.

### Goal
Update the [Enrichment Table app](https://github.com/cytoscape/enrichment-table-app/) with a new v2.0 features, for example:

- Filtering the result table by Evidence Codes provided by g:Profiler.
- Improving the error logging and message display. The focus should be on coming up with appropriate user-friendly messages.
- Adding connections to the EnrichmentMap app (see how the [stringApp](https://github.com/RBVI/stringApp) does this).
- Improving the display of `species` and `name` options, which are currently hidden in options.
- Identifying species information provided by other apps in order to make better default choices for the user.
- Adding visualization of enrichment results as ring charts.
- Come up with an automated testing framework and write tests for the app.

### Difficulty Level: Medium
Good Java programming skills are required. Familiarity with the concepts of unit testing, enrichment analysis and basic biology is helpful. 

### Size and Length of Project
- **175 hours**
- **12 weeks**

### Skills
Essential skills: Java, Web services
Nice to have skills: Cytoscape, Enrichment analysis

### Public Repository
https://github.com/cytoscape/enrichment-table-app/

### Potential Mentors
 - [Alex Pico](mailto:alex.pico@gladstone.ucsf.edu)
 - Scooter Morris
 - Yihang Xin 
 - Indraneel Ghosh (2021 GSoC contributor to this project)

**Comment by AkMo3** [comment]
Hi everyone, 
I am Akash Mondal, a sophomore at LNM Institute Of Information Technology pursuing B Tech Computer Science. I am currently working as a Backend Develop Intern, and have worked with various tech stacks like SpringBoot (Java), Mockito, ANTLR, React, Node etc. In past, I have contributed to multiple Open Source organizations and had been a Supervisor too. I am looking forward to working on this project as part of GSoC'22 as a mentee. 

It would be great I could get some advice on how to move ahead from here.

**Comment by ighosh98** [comment]
Hi @AkMo3 
A good place to start setting up and learning about Cytoscape would be the [Cytoscape App Ladder](https://github.com/cytoscape/cytoscape/wiki/Cytoscape-App-Ladder). You can also refer to the [Cytoscape tutorial](https://www.cgl.ucsf.edu/home/scooter/Cytoscape3DevTut/slides.pdf)
You can find the [current version of the app in the Cytoscape library](https://apps.cytoscape.org/apps/enrichmenttable). You can set it up and understand how it works. Feel free to post any follow-up questions about it.

The problem description has a link to the current code repository that you can explore and identify areas of improvement. We have listed some ideas in the problem description that we have identified that a mentee can work on.  You can also look at the [issues logged in the current project](https://github.com/cytoscape/enrichment-table-app/issues) for ideas too. You can add your own improvement ideas while writing the proposal. Your proposal should properly outline how you would go about implementing improvements in the app.

**Comment by csvultrainstinct** [comment]
hello all, my name is vibhav. Currently working as a c++ developer, I have no prior open-source contributions. I have good theoretical knowledge of java, so is it possible for me to work on this project and learn java on the go.

**Comment by ighosh98** [comment]
Hi @csvultrainstinct 
I have listed the resources you need to get started working on writing your proposal. Please go through the code that is already written. Your proposal should outline how you would go about improving the app.

**Comment by csvultrainstinct** [comment]
@ighosh98 yeah sure I will go through the documention first , thank you sir

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.

**Comment by khanspers** [comment]
Closing because this is an active project for GSoC 2022.
