### ISSUE TITLE
Refactor Existing Converters into the Systems Biology Format Converter (SBFC) and Add Tests

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#20]
### Background

The Systems Biology community makes use of several key formats, including: BioPAX (qualitative models), SBGN (visualization), and SBML (quantitative models). One of the overarching goal of the community is to support interoperability. 
### Goal

Successful completion of this project will help us to expand the available sources of BioPAX content. BioPAX is used by the Pathway Commons database, an aggregated pathway database that currently includes molecular interactions from over 20 databases. 

Using existing Java-based converters complete the following: 
- SBGN2BioPAX: Take an existing converter from CellDesigner (similar in scope to SBGN) to BioPAX and replace CellDesigner components with the matching SBGN ones and integrate into SBFC. 
- SBML2BioPAX: Take an existing converter developed in a previous GSOC and integrate with it into SBFC (replace the existing converter). 
- Testing: Add testing to the converters above and to other converters using existing validators for SBGN, SBML, and BioPAX.
#### Links:
- BioPAX support in CellDesigner: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3232372/
- CellDesigner to BioPAX source code: ftp://ftp.pantherdb.org/biopax
### Technologies
- Systems Biology Format Converter (SBFC): http://sbfc.sourceforge.net/mediawiki/index.php/Main_Page
- libSBGN: http://www.sbgn.org/LibSBGN
- JSBML: http://sbml.org/Software/JSBML
- Paxtools (BioPAX): http://biopax.github.io/Paxtools/

### Skills
Java, XML

### Public Repository
CellDesigner to BioPAX source code: ftp://ftp.pantherdb.org/biopax

### Potential Mentors

[Augustin Luna](mailto:lunaa@cbio.mskcc.org)

**Comment by niko-rodrigue** [comment]
I will work on SBML2BioPAX (in SBFC) and hope to have a new version by the time GSoC starts.
