### ISSUE TITLE
Schema and UI designer for Cytoscape.js

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#200]
### Background
Both [desktop](https://cytoscape.org/) and [web](http://js.cytoscape.org/) versions of Cytoscape are highly popular and widely used graph libraries / tools for visualizing relational data in various domains including biology. 

### Goal
Tough Cytsocape.js allows one to customize the UI of the graph elements using css, a GUI based designer for end users to quickly put together complicated node/edge UIs would be great. This would require (at the least):
- a way to define a graph model/schema graphically
- a way to drag and drop shapes, visual cues, etc. for each graph element type
- a way to generate the necessary Cytoscape.js style sheets from the design

### Difficulty Level: Hard
This project requires a good knowledge of Cytoscape.js and a good set of skills for UX.

### Size and Length of Project
**350 hours**. This project is expected to take the whole 22 weeks of a student's summer.

### Skills
Essential skills: JavaScript, Cytoscape.js
Nice to have skills: React or Angular 

### Public Repository
https://github.com/cytoscape/cytoscape.js

### Potential Mentors
Ugur Dogrusoz
Max Franz

**Comment by SantamRC** [comment]
@ugurdogrusoz My name is Santam. I am proficient in JavaScript and Frontend Development using React. I would like to start contributing to this project. Can you guide me as to how to get started?

**Comment by ugurdogrusoz** [comment]
@SantamRC Thanks for your interest. This is not the time to do this project. This is an idea, based on which you may put together a proposal hopefully when NRNB is selected as an organization. Feel free to learn related technologies, etc. though.

**Comment by khanspers** [comment]
NRNB has officially been accepted as a mentoring organization for GSoC 2022! Here are some useful links:

- [Project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
- [GSoC contributor guide](https://google.github.io/gsocguides/student/)
- [Program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by Shubhrajyoti-Dey-FrosTiK** [comment]
I am Shubhrajyoti Dey, 2nd year undergrad at Indian Institute of Technology (BHU) Varanasi . I have been pursuing MERN stack development for the past 1.5 years and have completed 3 internships in this area. I am interested to contribute in this project in GSoC 2022. Can anyone guide me how to get started ?

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.

**Comment by khanspers** [comment]
Closing in preparation for GSoC 2023.
