### ISSUE TITLE
Palette Creator app for Cytoscape

### ISSUE THREAD

**Issue by scootermorris** [nrnb/GoogleSummerOfCode#204]
### Background
Cytoscape 3.7 implemented the concept of Palettes and Palette Providers into the core API.  A Palette simply provides an ordered list of colors and provides some information about the suggested usage (divergent gradients, sequential gradients, or qualitative [categorical] colors).  Cytoscape includes three different palette providers: Viridis, Brewer, and for backwards compatibility, the original color generators (see [how to use palettes in Cytoscape](http://manual.cytoscape.org/en/stable/Styles.html?highlight=palette#tutorial-3-creating-a-new-style-with-a-continuous-mapping)).  There is currently no way for a user to create or import a palette of their own into Cytoscape.

### Goal
Implement a Cytoscape app that will allow users to create palettes.  The user should be able to save and restore palettes, and the palettes should be preserved as part of the sessions.  A stretch goal is to use public color sites such as ColorLovers to provide palettes for the user to start with.

### Size and Length of Project
**175 hours** -- this should be relatively straightforward for a programmer familiar with Java

### Skills
Essential skills: Java

### Public Repository
https://github.com/cytoscape/cytoscape
https://cytoscape.org/javadoc/3.9.0/  (AP JavadocI)

### Potential Mentors
Scooter Morris, Alex Pico

**Comment by Panchiwalayash** [comment]
Hi @scootermorris @AlexanderPico,
I find this issue interesting and would like to work on it for Google Summer of Code 2022. Can you please guide me on how to proceed with the task?

Thank You.

**Comment by Kartikkp07** [comment]
Hi @scootermorris  ,
I am Kartik Kumar Pawar, a CSE sophomore at BITS PILANI. I have good experience using python for about 6 years.I am also adept in JAVA with knowledge of OOPS and basic design patterns,I have also worked with both SQL and NoSQL database systems.I am familiar with javascript and have worked with React and nodeJS as well. I am really excited to know more about this project and contribute to it, with the aim of becoming a GSOC 22 contributor as well.
I kindly request you to guide me for the same so I can start as soon as possible.

**Comment by AlexanderPico** [comment]
Here are some places to start:
 * Can you build Cytoscape from a clone of the repo? (see [README](https://github.com/cytoscape/cytoscape))
 * Can you identify where in the code the current palette management is handled?
 * Can you use palettes in the GUI, following one of the many tutorials at http://tutorials.cytoscape.org?
 * Can you provide mock-ups for the GUI users would use to add new palettes?

If you get stuck, ask specific, detailed questions.

**Comment by khanspers** [comment]
NRNB has officially been accepted as a mentoring organization for GSoC 2022! Here are some useful links:

- [Project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
- [GSoC contributor guide](https://google.github.io/gsocguides/student/)
- [Program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.

**Comment by khanspers** [comment]
Closing in preparation for GSoC 2023.
