### ISSUE TITLE
AnnotateMe - Interactive tool for the annotation of SBML models

### ISSUE THREAD

**Issue by matthiaskoenig** [nrnb/GoogleSummerOfCode#206]
![image](https://user-images.githubusercontent.com/900538/155311647-90c7815c-eeb5-4330-aa2b-ec1ecb0a96d1.png)

### Background
Life science researchers use computational models to articulate and test hypotheses about the behavior of biological systems. Semantic annotation is a critical component for enhancing the interoperability and reusability of such models as well as for the integration of the data needed for model parameterization and validation. Encoded as machine-readable links to knowledge resource terms, semantic annotations describe the computational or biological meaning of what models and data represent. These annotations help researchers find and repurpose models, accelerate model composition and enable knowledge integration across model repositories and experimental data stores. However, realizing the potential benefits of semantic annotation requires the development of model annotation standards that adhere to a community-based annotation protocol as well as tools which enable the user to annotate computational models.

Within recent years an interactive report for SBML could be established (https://sbml4humans.de), which allows display and navigation of models in the SBML format, including information in semantic annotations. A highly requested feature is to provide functionality for the interactive annotation of existing models within the sbml4humans report. Within this project SBML4Humans will be extended with interactive annotation functionality using existing ontologies (such as ChEBI, UniProt, FMA, ...) and web services (Ontology Lookup Service, bioontologies, AnnotateDB).

For more information please see:
* Neal ML, König M, Nickerson D, Mısırlı G, Kalbasi R, Dräger A, Atalag K, Chelliah V, Cooling MT, Cook DL, Crook S, de Alba M, Friedman SH, Garny A, Gennari JH, Gleeson P, Golebiewski M, Hucka M, Juty N, Myers C, Olivier BG, Sauro HM, Scharm M, Snoep JL, Touré V, Wipat A, Wolkenhauer O, Waltemath D. **Harmonizing semantic annotations for computational models in biology**. Brief Bioinform. 2019 Mar 22;20(2):540-550. doi: 10.1093/bib/bby087. PMID: 30462164; PMCID: PMC6433895., https://pubmed.ncbi.nlm.nih.gov/30462164/
* Gennari JH, König M, Misirli G, Neal ML, Nickerson DP, Waltemath D. **OMEX metadata specification (version 1.2)**. J Integr Bioinform. 2021 Oct 20;18(3):20210020. doi: 10.1515/jib-2021-0020. PMID: 34668356; PMCID: PMC8560343., https://pubmed.ncbi.nlm.nih.gov/34668356/
* Keating SM, Waltemath D, König M, Zhang F, Dräger A, Chaouiya C, Bergmann FT, Finney A, Gillespie CS, Helikar T, Hoops S, Malik-Sheriff RS, Moodie SL, Moraru II, Myers CJ, Naldi A, Olivier BG, Sahle S, Schaff JC, Smith LP, Swat MJ, Thieffry D, Watanabe L, Wilkinson DJ, Blinov ML, Begley K, Faeder JR, Gómez HF, Hamm TM, Inagaki Y, Liebermeister W, Lister AL, Lucio D, Mjolsness E, Proctor CJ, Raman K, Rodriguez N, Shaffer CA, Shapiro BE, Stelling J, Swainston N, Tanimura N, Wagner J, Meier-Schellersheim M, Sauro HM, Palsson B, Bolouri H, Kitano H, Funahashi A, Hermjakob H, Doyle JC, Hucka M; **SBML Level 3 Community members. SBML Level 3: an extensible format for the exchange and reuse of biological models**. Mol Syst Biol. 2020 Aug;16(8):e9110. doi: 10.15252/msb.20199110. PMID: 32845085; PMCID: PMC8411907., https://pubmed.ncbi.nlm.nih.gov/32845085/

Existing webservices:
- Ontology lookup service, https://www.ebi.ac.uk/ols/index
- BioPortal, bioontology, https://www.bioontology.org/

### Goal
Interactive tool for the annotation of SBML models using existing ontologies and web services.

### Difficulty Level: Medium
The project requires knowledge of python and javascript for creating an interactive web tool for the annotation of models in SBML. Knowledge of RDF and web services are required.

### Size and Length of Project
Project size could either be **175 hours** or **350 hours** and the timeline between 12 and 22 weeks depending of the subset of features to implement during the project.

### Skills
Essential skills: Python, Javascript
Nice to have skills: RDF, SBML, web services (REST)

### Public Repository
- https://github.com/matthiaskoenig/sbmlutils
- sbml4humans.de

### Potential Mentors
- Matthias König (konigmatt@googlemail.com)

**Comment by UtkarshChaurasia** [comment]
Hi @matthiaskoenig ,
I am Utkarsh Chaurasia, a final year B.Tech Computer Science Engineering student at SRM University, Chennai. Currently, I am working as SDE Intern at Red Hat India. I have experience in working with C++, Java, JavaScript, Python, and Golang. I would like to contribute to this project, could you please point me to the resources to get started.

**Comment by matthiaskoenig** [comment]
Hi @UtkarshChaurasia. thanks for the interest in the project. Please contact me via email on konigmatt@googlemail with your CV so we can discuss next steps.
Best Matthias

**Comment by UtkarshChaurasia** [comment]
Thanks for replying. I have mailed my CV.

**Comment by UtkarshChaurasia** [comment]
Hi @matthiaskoenig..as you said, I mailed you my CV. Would be grateful if you could let me know if there is any update on this.

**Comment by khanspers** [comment]
NRNB has officially been accepted as a mentoring organization for GSoC 2022! Here are some useful links:

- [Project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
- [GSoC contributor guide](https://google.github.io/gsocguides/student/)
- [Program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by matthiaskoenig** [comment]
Hi all,

we have a highly motivated student who will submit a proposal for this project and started the community binding.
I recommend for other GSOC contributors to select a different project from NRNB (https://github.com/nrnb/GoogleSummerOfCode/issues).

Best Matthias

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.

**Comment by UtkarshChaurasia** [comment]
Thanks, @AlexanderPico for pointing this out. But I think I fulfill this eligibility criterion as I am a beginner open source contributor and have contributed to only one open-source project and that was not a major contribution as well.

**Comment by khanspers** [comment]
Closing because this is an active project for GSoC 2022.
