### ISSUE TITLE
Improving web service for layout and rendering of networks

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#208]
### Background
Systems Biology Layout & Rendering Service ([SyBLaRS](https://github.com/iVis-at-Bilkent/syblars)) is a web service to lay out graphs in SBGNML, SBML, GraphML and JSON formats and/or produce corresponding images (in JPG, PNG or SVG formats) of the layouts in the backend.

### Goal
The goal of this project is to extend the service in certain ways, including but not limited to:
- Support for calculating and highlighting graph-theoretic properties in the given network
- Support for querying the given network for certain paths (such as shortest paths) and sub-networks (graph of interest based on nodes of interest)

### Difficulty Level: Hard
This might be a harder project since it not only requires knowledge of Cytoscape.js, JavaScript, css and html and backend technologies such as node.js but also requires knowledge of graph algorithms such as betweenness centrality, shortest paths, computing graph of interest and the like.

### Size and Length of Project
This is estimated as a **12 weeks** full length summer long project

### Skills
Essential skills: Cytoscape.js, JavaScript, css, html, node.js, express, jquery
Nice to have skills: Knowledge with graph algorithms

### Public Repository
[SyBLaRS](https://github.com/iVis-at-Bilkent/syblars)
[Cytoscape.js](https://js.cytoscape.org/) and many of its extensions

### Potential Mentors
Ozgun Babur
Ugur Dogrusoz

**Comment by AlexVelezLl** [comment]
Hi everyone! I am passionate about graph theory and I am quite interested in this project. I have a question, this project must be strictly developed in 12 weeks, or is there a possibility that it can be extended to 22 weeks?

**Comment by ugurdogrusoz** [comment]
@AlexVelezLl this program is only for the summer. The goal of GSoC is to recruit new people into open source projects though. So, there is a chance that you would keep contributing after the summer.

**Comment by AlexVelezLl** [comment]
@ugurdogrusoz  Thanks for the info!

**Comment by khanhcodes** [comment]
My name is Kaitlyn and I am a first-year undergraduate student majoring in Computer Science and Mathematics at the University of Georgia. I am very interested in joining this project for the summer and making contributions to the code. In terms of web development experience, I am familiar with HTML, CSS, React.js, JavaScript, Bootstap, and JQuery for frontend development. For the backend, my skills include Node.js, Python, and Java. I have experience both in working on bioinformatics data analysis projects as well as web development. I believe my skillsets could be useful in improving web service layouts.  Please let me know if I can be a part of your team.

**Comment by yash170106065** [comment]
My name is Yash Agarwal and I graduated from the Indian Institute of Technology Guwahati (IIT Guwahati) and also worked on Graphspace which is also part of the NRNB organization so I have experience working with cytoscape.js, javascript, Html, Python Java, CSS, Jquery where I worked in implementing comment system for graphs, so I would like to work more with Cytoscape.js graphs and learn more about them and would like to contribute on this and I have already done the local setup for this and ready for discussing more on this project so @ugurdogrusoz @ozgunbabur can you please tell me how we can connect for this or make some group on IRC channel like google hangouts, etc.

**Comment by ugurdogrusoz** [comment]
@yash170106065 thanks for your interest in this project. given your past background, if investigate the related repositories, you should be able to put together a proposal for this project. Let us know if there is any particular issue by email.

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.

**Comment by khanspers** [comment]
Closing in preparation for GSoC 2023.
