### ISSUE TITLE
Create Patient Data Similarity Networks using TumorComparer 

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#209]
## Background

TumorComparer (https://www.sciencedirect.com/science/article/pii/S2667237521000849?via%3Dihub) is an algorithm for mapping experimental model systems (i.e., cell lines) to patient samples by examining various -omic profiles.

cBioPortal (cbioportal.org) for Cancer Genomics is an open-access, open-source resource for interactive exploration of multidimensional cancer genomics data sets. The goal of cBioPortal is to significantly lower the barriers between complex genomic data and cancer researchers by providing rapid, intuitive, and high-quality access to molecular profiles and clinical attributes from large-scale cancer genomics projects, and therefore to empower researchers to translate these rich data sets into biologic insights and clinical applications.

### Data

cBioPortal data is available via the cBioPortal Data Hub (https://github.com/cBioPortal/datahub/tree/master/public) and also directly from cbioportal.org (during the exploration of individual datasets).

### Algorithm

TumorComparer can take in an arbitrary number of continuous or discrete datasets for a subset of genes and produce similarity scores. 

## Goal 

* Create a patient data similarity network using cBioPortal
* Create an interface for visualizing details of the generated similarity network
 * See project site tumorcomparer.org for how similarity information is currently visualized
 * Suggest alteratives or improvements
* Create an interface for adding new patient data into the existing similarity network

## Getting Started

* Download cBioPortal datasets (look at the "Invasive Breast Carcinoma" (BRCA) datasets from the cBioPortal Data Hub and cbioportal.org)
* Download/install TumorComparer and review the vignette (tutorial) 
* Develop an understanding of what transformations would be necessary to go from cBioPortal data to TumorComparer. This [cBioPortal URL](https://www.cbioportal.org/results/oncoprint?cancer_study_list=brca_tcga_pan_can_atlas_2018&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Cgistic%2Crna_seq_v2_mrna_median_Zscores%2Crppa_Zscores&case_set_id=brca_tcga_pan_can_atlas_2018_all&gene_list=AKT1%2520ALK%2520AR%2520ARAF%2520BRAF%2520CHEK2%2520CTNNB1%2520DDR2%2520EGFR%2520ERBB2%2520ERBB3%2520ESR1%2520FGFR1%2520FGFR2%2520FGFR3%2520FGFR4%2520FLT3%2520GNA11%2520GNAQ%2520GNAS%2520HRAS%2520IDH1%2520IDH2%2520KIT%2520KRAS%2520MAP2K1%2520MAP2K2%2520MET%2520MTOR%2520NRAS%2520NTRK1%2520NTRK3%2520PDGFRA%2520PIK3CA%2520RAF1%2520RET%2520ROS1%2520SF3B1%2520SMAD4%2520SMO%2520ERG%2520ETV1%2520CCND1%2520CCND2%2520CCND3%2520CDK4%2520CDK6%2520MYC%2520APC%2520FBXW7%2520PTEN%2520TP53&geneset_list=%20&tab_index=tab_visualize&Action=Submit) will provide a data subset that you can use to prepare your proposal; the same gene list in the URL can be used for other cBioPortal datasets. On the OncoPrint tab, the Download > Tabular menu downloads the dataset that you then need to consider how to transform into TumorComparer input.
  * Project code should allow the gene list to be configurable
  * [Example TumorComparer Dataset](https://github.com/sanderlab/tumorcomparer/tree/master/inst/extdata/mock_5_data_types)
    * Any gene weight can be set to 1 for demonstration purposes in a proposal
  * TumorComparer-cBioPortal Mapping: 
    * TumorComparer: cna -> cBioPortal: Amplification/Deletion
    * TumorComparer: exp -> cBioPortal: mRNA Hi/Lo 
    * TumorComparer: prot -> cBioPortal: Protein Hi/Lo
    * TumorComparer: mut -> cBioPortal: Any driver mutation

## Size and Length of Project
Size: 175 hours
Length: 12 weeks

## Skills
List skills/technologies that the student should be familiar with. Also tag the issue with these.

Essential skills: R

## Public Repository
* https://github.com/sanderlab/tumorcomparer
* https://github.com/cBioPortal/datahub/tree/master/public

## Potential Mentors
[Augustin Luna](aluna@jimmy.harvard.edu)

**Comment by Ritwick01** [comment]
Hello @cannin,
I am Ritwick Pal, a Computer Science and Social Sciences student. I was introduced to R in my econometrics course, and I am really interested to contribute to this project and take this opportunity to enhance my expertise over R. I am new to open-source, so can you please guide me as to how to get started.

**Comment by Ritwick01** [comment]
@cannin 
I have done the first two parts of getting started, but I have trouble understanding the third point. Can you please help me understand it?

**Comment by meagoodboy** [comment]
Hi @cannin!
I am Aswin Jose, a 3rd-year undergraduate research student (Btech in Computer science and MS in computational natural science) at the International Institute of Information Technology in Hyderabad, India. My research work primarily involves the analysis of TCGA data from a systems biological and ML perspective. I have been using R for analyzing multi-omics data for almost a year for my research-related work. I am interested in being part of this organization as my research work aligns quite well with this project. Hence I would like to contribute to this project as part of the GSoC program over the summer.

**Comment by cannin** [comment]
@Ritwick01 I have provided more instructions on the third point.

**Comment by cannin** [comment]
@meagoodboy you can start by looking at the "Getting Started" section.

**Comment by khanspers** [comment]
A reminder that the application period opens on Monday April 4. Proposals to NRNB must be submitted on the official GSoC Site (https://summerofcode.withgoogle.com/) before April 19, 18:00 UTC to be considered, and contributors are encouraged to submit proposals in draft format early, so that mentors can give feedback directly at the GSoC site.

**Comment by meagoodboy** [comment]
@cannin 
I have gone through the getting started part. Can you please recommend related research papers or other resources I can refer, to create a proposal.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.
