### ISSUE TITLE
Converter from CellDesigner diagrams to proper SBML layout+rendering format

### ISSUE THREAD

**Issue by mhucka** [nrnb/GoogleSummerOfCode#21]
### Background

[SBML](http://sbml.org) is one of the most popular modeling and data exchange languages in systems biology.  A very popular software application in systems biology is [CellDesigner](http://celldesigner.org). Long before the SBML extensions for [Layout](http://co.mbine.org/specifications/sbml.level-3.version-1.layout.version-1.release-1) and [Rendering](https://sourceforge.net/p/sbml/code/HEAD/tree/trunk/specifications/sbml-level-3/version-1/render/render-version-1-draft-1.pdf) were defined, CellDesigner already provided mechanisms to display network diagrams and store them inside SBML files. To achieve this, the developers of CellDesigner created their own SBML annotations. It would be useful if a standalone parser existed that could convert files in CellDesigner's SBML dialect into SBML Level 3 format using the SBML Level 3 Layout and Rendering packages.

### Goal

Implement a standalone conversion program that can convert CellDesigner's unique SBML-based diagrams into official SBML Level 3 format.  Time permitting, the result could be integrated into the [Systems Biology Format Converter  (SBFC)](http://sbfc.sourceforge.net/mediawiki/index.php/Main_Page).

### Technologies

SBML, possibly Java (with the help of [JSBML](http://sbml.org/Software/JSBML)) or possibly other languages (with the help of [libSBML](http://sbml.org/Software/libSBML)).  A skeleton for format converters exists in the form of the [Systems Biology Format Converter  (SBFC)](http://sbfc.sourceforge.net/mediawiki/index.php/Main_Page) system, and some portions of that could be used to help implement this CellDesigner format converter.

### Potential Mentors

Andreas Dräger, Akira Funahashi, Nicolas Rodriguez.

### Contact

[SBML Team](mailto:sbml-team@caltech.edu)

Useful pointers to documentation related to GSOC for student on the main NRNB web site :
* [Resources](http://nrnb.org/gsoc.html)
* [How to apply](http://nrnb.org/gsoc.html#apply-tab)

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
