### ISSUE TITLE
Integrate the CausalPath Algorithm with the existing CausalPath Cytoscape App

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#210]
## Background
Last year, we developed a Cytoscape app for visualizing results from the CausalPath algorithm (https://github.com/cannin/causalpath_cytoscape_app and https://apps.cytoscape.org/apps/causalpathcytoscapeapp). The app currently takes as input two files that result from running CausalPath separately to produce a visualization.

## Goal
Integrate the CausalPath algorithm with the existing CausalPath app (i.e., CausalPath algorithm should run in cytoscape which will produce the output and will be used by the existing app for visualization).

## Getting Started

* Install the Cytoscape app found here (https://github.com/cannin/causalpath_cytoscape_app) to see how things currently work
* Check ongoing issues with the Cytoscape app: https://github.com/cannin/causalpath_cytoscape_app/issues this may give a understanding of the current code status
* Focus your attention on the main issue of importance for Cytoscape app (https://github.com/cannin/causalpath_cytoscape_app/issues/10). Your goal is to write a proposal to address this issue

## Difficulty Level: Medium
The difficulty should be medium for the following reason.

To get a clear understanding of Cytoscape from the documentation will be time consuming and challenging; a lot of debugging will be required for beginners. Integrating the CausalPath algorithm with the existing app will be challenging as we might need to implement new interfaces for the existing algorithm. 

## Size and Length of Project
It is a medium length project with the following details

* Medium: 175 hours
* 12 weeks
 
## Skills :
Essential skills: Java, Cytoscape

## Public Repository
* Main Code link:  https://github.com/cannin/causalpath_cytoscape_app
* CausalPath Algorithm Link: https://github.com/PathwayAndDataAnalysis/causalpath
* Dataset link: https://www.biorxiv.org/highwire/filestream/83268/field_highwire_adjunct_files/4/258855-5.zip
* Cytoscape App Development Manual: https://github.com/cytoscape/cytoscape/wiki/Cytoscape-3.0-App-Development
 
## Potential Mentors
* Augustin Luna (aluna@jimmy.harvard.edu)
* Pritam Saha
* Ozgun Babur

**Comment by Umang03** [comment]
My name is Umang Gupta and I am a third-year undergraduate student pursuing engineering at Maharaja Agrasen Institute of Technology. I am very interested in this project for the summer and making contributions to the code. I am familiar with JavaScript, React.js, Java, Node,js, HTML, CSS, and BootStrap. Plz guide me more about this Project .

**Comment by cannin** [comment]
@Umang03 You'll need to submit a proposal. See details here:
https://nrnb.org/gsoc.html Refer to the Goal/Getting Started section to give you ideas of the content that you need to address.

**Comment by cannin** [comment]
@Umang03 You'll need to submit a proposal. See details here:
https://nrnb.org/gsoc.html Refer to the Goal/Getting Started section to give you ideas of the content that you need to address.

**Comment by cannin** [comment]
@Umang03 You'll need to submit a proposal. See details here:
https://nrnb.org/gsoc.html Refer to the Goal/Getting Started section to give you ideas of the content that you need to address.

**Comment by cannin** [comment]
@Umang03 You'll need to submit a proposal. See details here:
https://nrnb.org/gsoc.html Refer to the Goal/Getting Started section to give you ideas of the content that you need to address.

**Comment by Umang03** [comment]
Ok. I'll work on it.

**Comment by AlexanderPico** [comment]
**IMPORTANT REMINDER: GSoC 2022 is for new “beginners” to open source.** 

Applicants are expected to review eligibility requirements prior to applying.  We can not accept applications from contributors with prior open source development experience. From the GSoC FAQ https://developers.google.com/open-source/gsoc/faq:

> Can someone already participating in open source be a GSoC Contributor?
>
> The goal of GSoC is to bring new contributors into open source organizations. GSoC can also help beginner contributors learn the ins and outs of open source while being mentored by experienced community members.
> GSoC is for new and beginner contributors to open source, it is not for experienced contributors to open source.
