### ISSUE TITLE
Python SBOL2 <-> SBOL3 converter

### ISSUE THREAD

**Issue by jakebeal** [nrnb/GoogleSummerOfCode#215]
### Background
[SBOL3](https://sbolstandard.org/) can currently be converted to SBOL2 via the JavaScript [sboljs](https://github.com/SynBioDex/sboljs3) library. Many SBOL3 applications are written in Python, however, and calling out to this JavaScript library causes a number of issues.

We would like to have a converter implemented in Python as well, which can then be used natively within Python applications. This would be implemented as part of [sbol-utilities](https://github.com/SynBioDex/SBOL-utilities) using the [pySBOL2](https://github.com/SynBioDex/pySBOL2/) and [pySBOL3](https://github.com/SynBioDex/pySBOL3/) libraries.

### Goal
The end result will be a Python SBOL2 to SBOL3 converter that is at least as capable as the current JavaScript converter.

### Difficulty Level
**Medium**

### Size and Length of Project
- **larger: 350 hours**
- **22 weeks**

### Skills
List skills/technologies that the student should be familiar with. Also tag the issue with these.

Essential skills: Python

### Public Repository
https://github.com/SynBioDex/SBOL-utilities

### Potential Mentors
@tcmitchell @jakebeal

**Comment by Akshat-Kumar-0610** [comment]
Hi @jakebeal, I am Akshat Kumar third year CS undergrad at BITS Pilani, India. I would like to take up this project for GSOC 2023. I have previously contributed to the SBOl-utilities last year. Can you please guide me how to proceed for this project.

**Comment by jakebeal** [comment]
@Akshat-Kumar-0610 If you are interested, please propose to this project for GSoC

**Comment by Akshat-Kumar-0610** [comment]
@jakebeal should I start with proposal or make more contributions to the repository?

**Comment by jakebeal** [comment]
@Akshat-Kumar-0610 Please follow Google's process, https://summerofcode.withgoogle.com/how-it-works
If you wish to make contributions to the repository as well, you are welcome to and that will strengthen your proposal.

**Comment by khanspers** [comment]
@Akshat-Kumar-0610 : Please note that we (NRNB) are still in the process of applying as a mentoring organization; mentoring organizations will be announced on Feb 22. Check back after that date for more information.

**Comment by khanspers** [comment]
NRNB has been accepted as a mentoring organization for GSoC 2023! Contributor applications open on March 20. Here are some useful links:

[GSoC contributor guide](https://google.github.io/gsocguides/student/)
[NRNB project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
[Eligibility requirements](https://developers.google.com/open-source/gsoc/faq#what_are_the_eligibility_requirements_for_participation)
[Full program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by jakebeal** [comment]
While this project still needs to be done, we have decided that we are not in a good position to supervise a GSoC student on it in summer 2024.
