### ISSUE TITLE
Implement a R Shiny Module for Network Analysis in CellMinerCDB  

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#216]
### Background
CellMinerCDB provides a web-based resource (https://discover.nci.nih.gov/cellminercdb/) for integrating multiple forms of pharmacological and genomic analyses, and unifying the richest cancer cell line datasets (the NCI-60, Sanger/MGH GDSC, and Broad CCLE/CTRP). CellMinerCDB enables data queries for genomics analyses, and exploration of pharmacogenomic determinants of response. It leverages overlaps of cell lines and drugs across databases to examine several biological questions.  CellMinerCDB  is built using R Shiny which provides a modular framework. 

### Goal
The goal of this project is to develop a network module for CellMinerCDB that will allow users to visualize averaged genetic profiling data on top of a curated set of pathways. Applicants should be inspired by the PathwayMapper project (https://www.pathwaymapper.org/) and its ability to visualize genomics data from cBioPortal. 

### How to Start 
Interested applicants should: 

1. Explore the CellMinerCDB site: https://discover.nci.nih.gov/cellminercdb
1. Download project code and set up locally and report any issues in setup: https://github.com/CBIIT/cellminercdb 
   * Generate a srcContent data file using NCI-60 data:  https://github.com/CBIIT/cellminercdb/blob/master/buildSrcContent.R, https://bioconductor.org/packages/release/data/experiment/html/rcellminerData.html: 
2. Review Shiny module development here: https://shiny.rstudio.com/articles/modules.html
3. Download the cyjShiny R Shiny package for network visualization and explore demo here: https://github.com/cytoscape/cyjShiny
4. Contact potential mentors to ask questions and write proposal for GSOC 

### Size and Length of Project
175 hours
12 weeks

### Skills
R (essential), Javascript

### Public Repository
* https://github.com/CBIIT/cellminercdb 
* https://github.com/cytoscape/cyjShiny

### Potential Mentors
Augustin Luna ({first_name}_{last_name} AT hms.harvard.edu)

**Comment by kts-desilva** [comment]
Hi, may I know if this project is still available for GSOC 2023? 
Thanks.

**Comment by khanspers** [comment]
@kts-desilva: Yes it is. All open issues are available for GSoC 2023.

**Comment by khanspers** [comment]
This project is an **active GSoC 2023** project. Closing this issue because it is no longer available for other contributors/students.
