### ISSUE TITLE
Converter from COBRA format to SBML Level 3 "FBC" Version 2

### ISSUE THREAD

**Issue by mhucka** [nrnb/GoogleSummerOfCode#22]
### Background

A popular technique in systems biology is [Constraint-Based Reconstruction and Analysis (COBRA)](http://cobramethods.wikidot.com/).  Toolboxes exist for this approach, of which  [COBRA toolbox](http://opencobra.github.io/) for MATLAB and [COBRApy](https://github.com/opencobra/cobrapy) for Python are probably the most widely used.  Recently, the modeling community put out an updated definition of how to represent such models in SBML, in the form of Version 2 of the [SBML Level 3 "Flux Balance Constraints"](http://co.mbine.org/specifications/sbml.level-3.version-1.fbc.version-2.release-1) (FBC) package.  The format standardizes how these models can be represented more precisely, but meanwhile, models in COBRA format exist and will never be updated until a converter is created.
### Goal

Develop a converter from COBRA format to SBML Level 3 FBC Version 2 format. Time permitting, incorporate this converter as a module in [JSBML](http://sbml.org/Software/JSBML), the pure Java library for SBML.  Optionally also add it as a converter in the  [Systems Biology Format Converter  (SBFC)](http://sbfc.sf.net/) system.
### Potential Mentors

[Andreas Dräger](mailto:draeger@informatik.uni-tuebingen.de)
[Nicolas Rodriguez](mailto:nicolas.rodriguez@babraham.ac.uk)

### Contact

[SBML Team](mailto:sbml-team@caltech.edu)

Useful pointers to documentation related to GSOC for student on the main NRNB web site :
- [Resources](http://nrnb.org/gsoc.html)
- [How to apply](http://nrnb.org/gsoc.html#apply-tab)

**Comment by niko-rodrigue** [comment]
@tmHamm is implementing those converters at the moment.
