### ISSUE TITLE
Setting up the CI/CD with Github Actions on Graphspace

### ISSUE THREAD

**Issue by yash170106065** [nrnb/GoogleSummerOfCode#221]
### Background
[GraphSpace](http://graphspace.org/) is an easy-to-use web-based platform collaborating research groups can use for storing, interacting with, and sharing networks. A GraphSpace user can upload graphs through a REST API, import graphs created in Cytoscape, interact with graphs (view them, customize layouts, and save layouts), share graphs (create groups and add collaborators, share graphs among all members of a group or with the world), search graphs, and organize graphs using tags. GraphSpace has a comprehensive REST API that allows users to communicate programmatically with it. Overall, GraphSpace provides a rich set of user-friendly features designed to enhance network-based collaboration.

### Goal
This project aims to stabilise the project and its code repository as there are multiple dependencies so, this will also help in reducing problems and blockers while setting up this project locally and also setting up the pipeline and checks for the PR to be merged into master.

* **GraphSpace local setup issues:** Resolve blockers and issues while setting up GraphSpace locally and running this project for eg. upgrade versions of some libraries, resolve requirements.txt file with adding all remaining libraries, installation issues etc.

* **Create a Dockerfile:** Create a docker file for this project which provide a suitable environment for running this project with all required dependencies. Create a docker compose file which helps us to run this project in Github action workflows and create this image and also helps us to run this locally with minimal setup. 

* **Setup GitHub Actions:** Set up the workflow for the GitHub actions which will provide a suitable environment for running this project and no PR can be merged without the jobs and checks being successful in the workflow. On every pull request and for every commit in the PR, the GitHub actions should trigger all the workflows and jobs written for this project.
Try to research more actions you can add some of the example actions can be : 
* An action for automatically labelling pull requests.
* Should have all dependencies in the image required in GraphSpace.
* Run GraphSpace in this environment and try to check health controller response.
* Build an image after it successfully run and build completes.
* Publish the image to the ECR.
* Assign reviewers automatically on pr.
* Assign labels on PR's.
* Generate various reports, analysis and send notification on PR's.

I prefer you to research more and find out more additional actions and that can be added in the workflow
https://github.com/sdras/awesome-actions
### Size and Length of Project
- **medium: 175 hours**
- **12 weeks**

### Skills
[Docker](https://docs.docker.com/)
[GitHub Actions](https://docs.github.com/en/actions)
[Python]()

### Public Repository
https://github.com/Murali-group/GraphSpace/

### Potential Mentors
[Yash Agarwal](https://github.com/yash170106065)
[Daniyal Jahan Warsi](https://github.com/jahandaniyal)
[Aditya Bharadwaj](https://github.com/adbharadwaj)

### IRC
Discord for GSoC 2023: https://discord.gg/AqjnwHndq8
Gitter for community: https://gitter.im/graphspace/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by maheshkasabe** [comment]
Hello Yash , 
are these projects open to work ?
i really wanna work on them , would appreciate if you assign them to me !

**Comment by yash170106065** [comment]
Sure @maheshkasabe I appreciate that you are interested in contributing to Graphspace and its better you start by setting up Graphspace locally and identify the issues as well as write down each dependency version, this will be your first step as well as this will help while creating gsoc proposal.
Thanks

**Comment by yash170106065** [comment]
@khanspers can you please provide me access for putting the labels on this issue.

**Comment by jahandaniyal** [comment]
> Hello Yash , are these projects open to work ? i really wanna work on them , would appreciate if you assign them to me !

Hi @maheshkasabe - Like @yash170106065 said The best way to get started would be to build GraphSpace locally and then head over to GraphSpace's [Issue list](https://github.com/Murali-group/GraphSpace/issues). 
See if you can find anything that might sound interesting to you.

Cheers,

**Comment by Vikash-8090-Yadav** [comment]
Hey @yash170106065 am very intersted in this project as this match with my skill .Please tell from where should i start and if possible please provide any irc channel of that project or else something where i can ask query  .Thank u ✌️

**Comment by yash170106065** [comment]
@Vikash-8090-Yadav I appreciate that you are interested in this project as mentioned above you should start by setting up graphspace  locally
Below i am attaching IRC channel link

https://gitter.im/graphspace/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by maheshkasabe** [comment]
Definitely @jahandaniyal would love to add value this project !

**Comment by yash170106065** [comment]
Thanks, @khanspers i got it now

**Comment by deep-poharkar** [comment]
hey @yash170106065 i tried setting up GraphSpace locally but i'm getting an error when it comes to step 6 of https://github.com/Murali-group/GraphSpace/wiki/Running-GraphSpace-Locally i have been trying since days would appreciate if you help me out.

**Comment by yash170106065** [comment]
@maheshkasabe @Vikash-8090-Yadav @deep-poharkar I created a new discord server specifically for Gsoc 2023 that will help us to connect biweekly and resolve your issues 
https://discord.gg/AqjnwHndq8

**Comment by khanspers** [comment]
NRNB has been accepted as a mentoring organization for GSoC 2023! Contributor applications open on March 20. Here are some useful links:

[GSoC contributor guide](https://google.github.io/gsocguides/student/)
[NRNB project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
[Eligibility requirements](https://developers.google.com/open-source/gsoc/faq#what_are_the_eligibility_requirements_for_participation)
[Full program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by yash170106065** [comment]
Hey @muskan-k great to see that you are interested in this project and its amazing that you setup the graphspace locally in such a less time, as well as regarding something specific to proposal try not to share in public groups ask in discord direct messages.
Thanks

**Comment by khanspers** [comment]
This project is an **active GSoC 2023** project. Closing this issue because it is no longer available for other contributors/students.
