### ISSUE TITLE
Supporting ssGSEA and Pathway Commons in clusterProfiler 

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#222]
##### Pathway Commons 
Pathway Commons (http://pathwaycommons.org/) is an aggregated database of molecular interactions of millions of interactions. The data is aggregated from a collection of approximately 20 databases. Data from Pathway Commons is accessible here.

#### clusterProfiler
clusterProfiler (https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html) provides a univeral interface for gene functional annotation from a variety of sources and thus can be applied in diverse scenarios. It provides a tidy interface to access, manipulate, and visualize enrichment results to help users achieve efficient data interpretation.

### Goal 
There are two goals: 

* Add support for Pathway Commons dataset in clusterProfiler
* Add support for ssGSEA in clusterProfiler; a starting point for the proposal would be to integrate this functionality by using the GSVA package: https://bioconductor.org/packages/devel/bioc/vignettes/GSVA/inst/doc/GSVA.html

### How to Start

1. Examine the Pathway Commons GMT datasets here: https://www.pathwaycommons.org/archives/PC2/v12/ the code example below using readGmt() from paxtoolr can help: https://bioconductor.org/packages/release/bioc/html/paxtoolsr.html and enricher() from clusterProfiler may help understanding the code.

```
pc <- readGmt("PathwayCommons.12.Reactome.GSEA.hgnc.gmt", removePrefix = TRUE)
pcGmt <- data.frame(ont=character(0), gene=character(0))
for(i in 1:length(names(pc))) {
  x <- names(pc)[i]
  pcGmt <- rbind(pcGmt, data.frame(ont=x, gene=pc[[x]]))  
}
pcGmt <- saveRDS(pcGmt, "pcGmt.rds")
egmt <- enricher(genes, TERM2GENE=pcGmt)
```

2. Examine how other datasets are included in clusterProfiler: https://github.com/YuLab-SMU/clusterProfiler/blob/master/R/wikiPathways.R
3. Examine ssGSEA functionality and how GSEA was implemented for clusterProfiler: https://github.com/YuLab-SMU/clusterProfiler/blob/master/R/gseAnalyzer.R
4. Write your proposal for addressing the goals

### Size and Length of Project
175 hours
12 weeks

### Skills
R

### Public Repository
* https://github.com/YuLab-SMU/clusterProfiler
* https://github.com/rcastelo/GSVA
* https://github.com/BioPAX/paxtoolsr

### Potential Mentors
* Augustin Luna ({first_name}_{last_name} AT hms.harvard.edu)
* [GuangchuangYu](https://github.com/YuLab-SMU/)

**Comment by Jigyasa-G** [comment]
Hi @cannin !
I am interested in drafting a proposal for this issue. Kindly guide me on the next steps to be taken.

**Comment by Jigyasa-G** [comment]
> 
Sure thing, Thank you!

**Comment by Jigyasa-G** [comment]
@GuangchuangYu @cannin I have a couple of ideas for the above issue, should I include all of them in the proposal and justify which one would be more suited (with room for flexibility) or just pick one ?

**Comment by cannin** [comment]
@Jigyasa-G the proposal should cover the two main goals: Pathway Commons and ssGSEA. if you have multiple ideas for either of these i would just put your strongest/detailed one, otherwise your application might not be clear enough for proposal reviewers.

**Comment by Jigyasa-G** [comment]
> @Jigyasa-G the proposal should cover the two main goals: Pathway Commons and ssGSEA. if you have multiple ideas for either of these i would just put your strongest/detailed one, otherwise your application might not be clear enough for proposal reviewers.

Thank you for mentioning, will work accordingly.

**Comment by Jigyasa-G** [comment]
Hey @cannin @GuangchuangYu ! I have submitted a proposal, should I start with any PRs if you suggest?

**Comment by cannin** [comment]
@Jigyasa-G Currently the proposals are being reviewed.

**Comment by Jigyasa-G** [comment]
Thank you for allowing me the opportunity to work on this project!
 I am super excited to move further. Kindly guide me about the next steps @cannin @GuangchuangYu

**Comment by khanspers** [comment]
This project is an **active GSoC 2023** project. Closing this issue because it is no longer available for other contributors/students.

**Comment by Jigyasa-G** [comment]
@GuangchuangYu @cannin 
![image](https://user-images.githubusercontent.com/75614134/237002443-867a0397-d394-4dcf-a70a-df6f95ad3773.png)
I tried using the enricher() function for clusterProfiler however it seems like the function isn't available. I went through the docs but couldn't find why it is still unsupported.

**Comment by Jigyasa-G** [comment]
> @Jigyasa-G Did you have the clusterProfiler package installed and loaded properly?

It's working now with the updated R version.

**Comment by Jigyasa-G** [comment]
To be able to work with actual Biological data, I would need resources to understand the biology behind to be able to work out the methods. @GuangchuangYu @cannin Can you please suggest some?

**Comment by Jigyasa-G** [comment]
![image](https://github.com/nrnb/GoogleSummerOfCode/assets/75614134/91b2a0a9-1ecb-4eb6-a191-451a7f19f8a6)
@GuangchuangYu @cannin All the testthat tests have passed , however, I am unable to solve this error while using BiocCheck for testing. Kindly help

**Comment by cannin** [comment]
@Jigyasa-G please make issues/ask questions on the actual project and not here; please repost there and we'll answer them.
