### ISSUE TITLE
Automate Cytoscape.js release process using GitHub Actions

### ISSUE THREAD

**Issue by maxkfranz** [nrnb/GoogleSummerOfCode#224]
### Background

[Cytoscape.js](https://js.cytoscape.org/) is a library used to visualise and analyse [networks](https://en.wikipedia.org/wiki/Graph_theory) in the browser or in Node.js.

The Cytoscape.js [release process](https://github.com/cytoscape/cytoscape.js#release-instructions) is mostly manual.  This process could be automated to reduce the cost of making releases, especially given the potentially frequent release cadence.

### Goal

- Automate the release process using [GitHub Actions](https://docs.github.com/en/actions).
- Plan and document a mechanism for starting the release process (i.e. the trigger of the action).  A person will still have to decide when to make a release, for example.
- Document the details of the new, automated release process in the project readme.
- Extend the automation to handle contingencies, as outlined in your plan.

### Difficulty Level: Easy/Medium/Hard
Medium.  Parts of it are straightforward, but planning out the details may require creativity.

### Size and Length of Project

- **medium: 175 hours**
- **12 weeks**

### Skills

Essential skills: JS, Bash, Node.js
Nice to have skills: Prior use of GitHub & GitHub Actions

### Public Repository

https://js.cytoscape.org/

### Potential Mentors

- Max Franz (maxkfranz@gmail.com)
- Mike Kucera (mikekucera@gmail.com)
- Christian Lopes (chrtannus@gmail.com)
- Gary Bader (gary.bader@utoronto.ca)

**Comment by mak2002** [comment]
Hi @maxkfranz,

I am very interested in working on this project. I have been a Google Summer of Code 2022 contributor at Joplin. I have worked on implementation of bundling and installing default plugins for Desktop releases. In this project, I wrote a script for CI/CD workflow using TypeScript that fetches and bundles plugins with the app.  I believe my experience will be helpful for this project.

You can take a look at the PR [here](https://github.com/laurent22/joplin/pull/6679). My work report summary can be found [here](https://gist.github.com/mak2002/d9d537e9a61390427ca37976895ce215).

I would like to discuss ideas with you and other mentors also. Should I contact just contact you via email?

Thank You.

**Comment by maxkfranz** [comment]
Great.  The best way forward is to start on your proposal: https://nrnb.org/gsoc.html

If you have specific questions when working on your proposal, feel free to reach out by email.

**Comment by Deepanshu-Choudhary** [comment]
Hi @maxkfranz ,
My name is Deepanshu Choudhary and I'm a sophomore at BITS-Pilani. I have good experience with Java, JSP, Servlets, MySQL, DHTML and Node.js. I am eager to learn new things and more about open-source projects. I am interested in this project and looking forward for contributing to it.
Please guide me, How do I start?
Thank you

**Comment by khanspers** [comment]
This project is an **active GSoC 2023** project. Closing this issue because it is no longer available for other contributors/students.
