### ISSUE TITLE
Validation service for biological maps

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#225]
### Background
Systems Biology Graphical Notation (SBGN) [1] is a standard language for representing biological pathways with SBGNML being the exchange and storage format for SBGN. The Systems Biology Markup Language (SBML) [2] is the de facto standard for encoding computational models in systems biology. Both types of XML based formats have a well defined representation for maps, which might be logically invalid even though they are syntactically valid.

[1] N. Le Novère et al., "[The Systems Biology Graphical Notation](http://www.nature.com/nbt/journal/v27/n8/abs/nbt.1558.html)", Nature Biotechnology, 27, pp. 735-741, 2009.

[2]  M. Hucka et al. "[The systems biology markup language (SBML): a medium for representation and exchange of biochemical network models](https://doi.org/10.1093/bioinformatics/btg015)". Bioinformatics, 19, pp. 524–531, 2003. 

### Goal
The goal here is to take SBGNML or SBML maps (files) and construct a static image of these maps (performing an automatic layout where needed) with any invalid issues highlighted on the image. If desired, the service will try to fix these errors when possible.

### Difficulty Level: Easy/Medium/Hard
**Hard** (This project requires knowledge of both standards and related libraries as well as a good level of both front and back end development experience)

### Size and Length of Project
- **large: 350 hours**

### Skills
Essential skills: Java, JavaScript, Cytoscape.js
Nice to have skills: SBGN and SBML knowledge

### Public Repository
[libSBGN](https://github.com/sbgn/libsbgn)
[libSBML](https://github.com/sbmlteam/libsbml)

### Potential Mentors
Ugur Dogrusoz

**Comment by mak2002** [comment]
Hi @ugurdogrusoz! I am Mayank, Google Summer of Code 2022 contributor at Joplin. I have experience with JavaScript and Java and I have been exploring related libraries lately.

I find this project very interesting. I was wondering if you could provide me with more information about where this service will be implemented. Will it be a standalone software or integrated into an existing software or library, such as the SBGN library? 

Thank you.

**Comment by ugurdogrusoz** [comment]
It should be a standalone service, making use of existing libraries such as libsbgn.

**Comment by Deepanshu-Choudhary** [comment]
Hi @ugurdogrusoz ,
My name is Deepanshu Choudhary and I'm a sophomore at BITS-Pilani. I have good experience with Java, JSP, Servlets, MySQL, DHTML and Node.js. I am eager to learn new things and more about open-source projects. I am interested in this project and looking forward for contributing to it.
Please guide me, How do I start?
Thank you

**Comment by RaminGahramanzada** [comment]
Hi Ugur,

My name is Ramin Gahramanzada, and I have knowledge of Java SE, Java EE, MySQL, JSP, Spring, Maven, HTML, CSS, and JavaScript. I would like to join your project on automatically formatting and visualizing SBGNML or SBML maps.

Could you please let me know if you have some time to discuss the project and how I could contribute? I would also like to learn about the tasks that might be suitable for me to work on.

I am excited to collaborate with you, and I look forward to hearing from you soon.

Best regards,
Ramin Gahramanzada

**Comment by ugurdogrusoz** [comment]
Sorry for such a late decision but we are already addressing this idea internally at our lab.
