### ISSUE TITLE
Improve data upload and add geneset support to openPIP

### ISSUE THREAD

**Issue by MoHelmy** [nrnb/GoogleSummerOfCode#226]
### Background
Open-source Protein Interaction Platform (openPIP) as a customizable web portal designed to host experimental PPI maps. No coding skills are required to set up and customize the database and web portal. OpenPIP is freely available as a ready-to-use Docker container for hosting and sharing PPI data with the scientific community. OpenPIP has been used to build the databases and web portals of two major protein interactome maps, the Human and Yeast Reference Protein Interactome maps (HuRI and YeRI, respectively). For more about openPIP [Helmy _et al_ **_Journal of Molecular Biology_**, 2021](https://www.sciencedirect.com/science/article/pii/S0022283622001838), [HuRI](http://www.interactome-atlas.org/), [YeRI](http://yeast.interactome-atlas.org/)

### Goals

1. Improve the data import module of openPIP: the current data import/upload module uses the standard Proteomics Standards Initiative Molecular Interactions (PSI-MI) format and connects to several public databases to collect further information for all proteins in the dataset. The improvement that we need to make is to make the connection to the public databases optional, add the protein details to the PSI-MI file and create an upload script that can be used by admins to add data to the databases independent from the GUI upload module for advanced users. 
2. Adding support for gene/protein datasets: This will be an extension that we will develop to be able to visualize the gene/protein datasets (such as pathways) in a network similar to gene/protein networks. Currently, the networks that openPIP visualizes are protein PPI networks; the nodes are the proteins, and the edges are the interactions. The extension will allow visualization of gene/protein datasets where the node is the gene/protein dataset, and the edge is the overlap between the two connected gene/protein datasets.      

### Difficulty Level
**Medium to Hard**
the core of openPIP is based on some old packages. Some will need to be updated, and some cannot be updated. This adds so some difficulty. 

### Size and Length of Project
- **Large: 350 hours**
- **~20 weeks**

### Skills
Essential skills: PHP, JavaScript, Cytoscape, MySQL

### Public Repository
[openPIP GitHub repo](https://github.com/BaderLab/openPIP)

### Potential Mentors
Mohamed Helmy [webpage](https://www.vido.org/team/project-leaders-veterinarians/mohamed-helmy) [email](mailto:mohamed.helmy@usask.ca)

**Comment by Rohan-Ver-ma** [comment]
Hello Mohamed
I am interested in contributing to this issue . I believe I can offer some valuable insights and help with resolving it.
can you please point me to the organizations appropriate slack or discord server ? so that I can get my queries resolved regarding this issue .

**Comment by khanspers** [comment]
NRNB has been accepted as a mentoring organization for GSoC 2024. The contributor application period if March 28 – April 2. Here are some useful links:

[GSoC contributor guide](https://google.github.io/gsocguides/student/)
[NRNB project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
[Eligibility requirements](https://developers.google.com/open-source/gsoc/faq#what_are_the_eligibility_requirements_for_participation)
[Full program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by AryanBakliwal** [comment]
Hello @MoHelmy, Could you recommend a specific learning path or resources that would be most beneficial for someone new to the project? I'd really appreciate your help with this, so I can jump into contributing as soon as possible.

**Comment by MoHelmy** [comment]
@AryanBakliwal Here are some resources:
The repo of the system: https://github.com/BaderLab/openPIP
The publication: https://www.sciencedirect.com/science/article/pii/S0022283622001838
An online instance of the system: http://www.interactome-atlas.org/
Another online instance of the system: http://yeast.interactome-atlas.org/

**Comment by Bader533** [comment]
@MoHelmy 
Can I find out the details and how to register for the training

**Comment by AlaaAzzam2311** [comment]
@MoHelmy how to apply?

**Comment by Moemen-Gaballah** [comment]
@MoHelmy Dear, Professor Mohamed.
I am a PHP developer.

How do I join with you?
What's your name organization in `https://summerofcode.withgoogle.com/programs/2024/organizations`?

Thanks.

**Comment by mahmoudyosrimahmoud13** [comment]
@MoHelmy Dear, Professor Mohamed.
I am ML intern and flutter developer.
How can I join you?

**Comment by MoHelmy** [comment]
If you are interested, please send me your CV and portfolio.
The program details and application requirement: https://summerofcode.withgoogle.com/

**Comment by Moemen-Gaballah** [comment]
> If you are interested, please send me your CV and portfolio. The program details and application requirement: https://summerofcode.withgoogle.com/

Dear, Professor Mohamed
[My CV](https://drive.google.com/file/d/1-XNSICAvo9-w869K-DBraUMj6wJIx9y-/view?usp=sharing).

Thanks.

**Comment by MoHelmy** [comment]
@Moemen-Gaballah did you check the repo of the project?

**Comment by sharafabacery** [comment]
> If you are interested, please send me your CV and portfolio. The program details and application requirement: https://summerofcode.withgoogle.com/

and this is my resume Can you check it: [Resume](https://docs.google.com/document/d/1dPYANJC_kJHKotTz2dIkssOmVSEKOtAVbgOBw1j5Oo4/edit?usp=sharing) I have small problem my laptop can't run docker it would be problem.

**Comment by Moemen-Gaballah** [comment]
> @Moemen-Gaballah did you check the repo of the project?

Yes, but I have not installed it yet.

**Comment by Ahmed-H300** [comment]
Hello @MoHelmy 
I'm Ahmed a computer engineering student at Cairo university, 
I'm highly motivated to be part of GSOC'24 and open PIP community, 
I'm a back-end developer with 2 year of experience.
my technical stack is: PHP, Spring Boot, Express.js and planning to get more experience working on an open source projects this year
([github](https://github.com/Ahmed-H300)) ([linkedin](https://www.linkedin.com/in/ahmed-hany-33b3b420a/))
and My CV
 ([CV](https://drive.google.com/file/d/11aegfiZRf0fNM8L1mS9m_QqL8qlA29Y4/view?usp=drive_link))

currently checked this idea and interested to investigate this more
I wonder about some more details. How to start getting to know the code base, good first issue, or any qualification tasks to start with.

**Comment by MoHelmy** [comment]
@Ahmed-H300 You can start by checking the openPIP repo, live instances and publications. All are linked above.

**Comment by khanspers** [comment]
The organization name is NRNB: https://summerofcode.withgoogle.com/programs/2024/organizations/national-resource-for-network-biology-nrnb

All proposals for GSoC must be submitted via https://summerofcode.withgoogle.com/, before April 2 18:00 UTC. You can make updates to your proposals until the deadline. We cannot consider proposals/applications send directly to mentors by email, or in other forms.

**Comment by sukhmandhawan** [comment]
> ### Background
> Open-source Protein Interaction Platform (openPIP) as a customizable web portal designed to host experimental PPI maps. No coding skills are required to set up and customize the database and web portal. OpenPIP is freely available as a ready-to-use Docker container for hosting and sharing PPI data with the scientific community. OpenPIP has been used to build the databases and web portals of two major protein interactome maps, the Human and Yeast Reference Protein Interactome maps (HuRI and YeRI, respectively). For more about openPIP [Helmy _et al_ **_Journal of Molecular Biology_**, 2021](https://www.sciencedirect.com/science/article/pii/S0022283622001838), [HuRI](http://www.interactome-atlas.org/), [YeRI](http://yeast.interactome-atlas.org/)
> 
> ### Goals
> 1. Improve the data import module of openPIP: the current data import/upload module uses the standard Proteomics Standards Initiative Molecular Interactions (PSI-MI) format and connects to several public databases to collect further information for all proteins in the dataset. The improvement that we need to make is to make the connection to the public databases optional, add the protein details to the PSI-MI file and create an upload script that can be used by admins to add data to the databases independent from the GUI upload module for advanced users.
> 2. Adding support for gene/protein datasets: This will be an extension that we will develop to be able to visualize the gene/protein datasets (such as pathways) in a network similar to gene/protein networks. Currently, the networks that openPIP visualizes are protein PPI networks; the nodes are the proteins, and the edges are the interactions. The extension will allow visualization of gene/protein datasets where the node is the gene/protein dataset, and the edge is the overlap between the two connected gene/protein datasets.
> 
> ### Difficulty Level
> **Medium to Hard** the core of openPIP is based on some old packages. Some will need to be updated, and some cannot be updated. This adds so some difficulty.
> 
> ### Size and Length of Project
> * **Large: 350 hours**
> * **~20 weeks**
> 
> ### Skills
> Essential skills: PHP, JavaScript, Cytoscape, MySQL
> 
> ### Public Repository
> [openPIP GitHub repo](https://github.com/BaderLab/openPIP)
> 
> ### Potential Mentors
> Mohamed Helmy [webpage](https://www.vido.org/team/project-leaders-veterinarians/mohamed-helmy) [email](mailto:mohamed.helmy@usask.ca)

Hello ! @MoHelmy 

I am very excited and looking for to this. I have thereby emailed you my  resume as well.
And attached it here as well.
[Sukh-Resume.pdf](https://github.com/nrnb/GoogleSummerOfCode/files/14705911/Sukh-Resume.pdf)

**Comment by sukhmandhawan** [comment]
Hello ! @MoHelmy

I am very excited and looking for to this. I have thereby emailed you my resume as well.
And attached it here as well.
[Sukh-Resume.pdf](https://github.com/nrnb/GoogleSummerOfCode/files/14705911/Sukh-Resume.pdf)

**Comment by jana-source** [comment]
Dear, Professor Mohamed, 
                                             I am a recent Bioinformatics Ain shams university graduate and I am very interested in this project . 
 as it is required to know PHP, My SQL and Java Script I gathered screen shots of my work as a proof , I have applied using the form but was wondering where should I upload the proof that I have the required skills 
 so I will attach it here as well as my cv 
 
[php.pdf](https://github.com/nrnb/GoogleSummerOfCode/files/14837085/php.pdf)
[My SQL.pdf](https://github.com/nrnb/GoogleSummerOfCode/files/14837089/My.SQL.pdf)
[Java Script.pdf](https://github.com/nrnb/GoogleSummerOfCode/files/14837092/Java.Script.pdf)
[Jana's CV.pdf](https://github.com/nrnb/GoogleSummerOfCode/files/14837098/Jana.s.CV.pdf)

**Comment by khanspers** [comment]
Hi @jana-source: I don't see a proposal from you in the GSoC interface, please double-check your submission.
