### ISSUE TITLE
GPML support in Newt

### ISSUE THREAD

**Issue by hasanbalci** [nrnb/GoogleSummerOfCode#227]
### Background
[Newt](https://newteditor.org/) [1] is a [Cytoscape.js](http://js.cytoscape.org/) [2] based, open source viewer and editor for pathways in [Systems Biological Graphical Notation (SBGN)](http://sbgn.org/) [3] and [Simple Interaction Format (SIF)](http://www.pathwaycommons.org/pc2/formats#sif_relations). It's been built (with partial support from GSoC) around an editing library named [ChiSE](https://github.com/iVis-at-Bilkent/chise.js), which in turn was based on a viewer library named [SBGNViz](https://github.com/iVis-at-Bilkent/sbgnviz.js) [4]. The tool uses a number of [Cytoscape.js extensions](http://js.cytoscape.org/#extensions) built for various editing capabilities such as grid-guidelines, context-menus, and expand-collapse.

[GPML (Graphical Pathway Markup Language)](https://pathvisio.org/documentation/GPML) is the file format used to store pathway content at [WikiPathways](https://www.wikipathways.org/) [5]. It is a custom XML format compatible with pathway visualization and analysis tools such as [PathVisio](https://pathvisio.org/) [6] and [Cytoscape](https://cytoscape.org/). Currently, biological maps in GPML format can be created only with PathVisio which is a desktop application or via conversion from other formats such as SBGN and SBML by using Minerva converters.

[1] H. Balci et al., "[Newt: a comprehensive web-based tool for viewing, constructing, and analysing biological maps](https://doi.org/10.1093/bioinformatics/btaa850)", Bioinformatics, 37(10), pp.1475-1477, 2021.
[2] M. Franz et al. "[Cytoscape. js 2023 update: a graph theory library for visualization and analysis.](https://academic.oup.com/bioinformatics/article/39/1/btad031/6988031)", Bioinformatics 39.1, btad031, 2023.
[3] N. Le Novère et al., "[The Systems Biology Graphical Notation](http://www.nature.com/nbt/journal/v27/n8/abs/nbt.1558.html)", Nature Biotechnology, 27, pp. 735-741, 2009.
[4] M. Sari et al., "[SBGNViz: a tool for visualisation and complexity management of SBGN process description maps](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0128985)", PLoS ONE, 10(6), e0128985, 2015.
[5] A Agrawal et al. "[WikiPathways 2024: next generation pathway database](https://academic.oup.com/nar/article-abstract/52/D1/D679/7369835)", Nucleic Acids Research 52.D1, pp. D679-D689, 2024.
[6] M. Kutmon et al., "[PathVisio 3: An Extendable Pathway Analysis Toolbox](https://doi.org/10.1371/journal.pcbi.1004085)", PLoS Comput. Biol. 11(2): e1004085, 2015.

### Goal
The goal of this project is to add new functionalities to Newt to be able to create biological maps in GPML format from scratch or edit existing ones. This will provide users to have a web-based alternative to PathVisio where they can easily create/edit GPML maps from any computer with Internet access. The functionalities to be added will also include access to WikiPathways, easy identifier mapping and data visualization etc., as in PathVisio.

### Difficulty Level: Hard
This project will consist of roughly the following steps, requiring knowledge of different programming languages, libraries and tools:
- Implementation of JavaScript version of [libGPML](https://github.com/PathVisio/libGPML) to be able easily read/write GPML files.
- Addition of a new Palette section and a stylesheet for node and edge types in GPML.
- Addition of other functionalities such as access to WikiPathways, identifier mapping, data visualization etc.

### Size and Length of Project
- **large: 350 hours**
- **22 weeks**

### Skills
Essential skills: JavaScript, HTML, CSS, Java, Cytoscape.js, GPML
Nice to have skills: SBGNViz, ChiSE, PathVisio 

### Public Repository
[Newt GitHub repository](https://github.com/iVis-at-Bilkent/newt)
[ChiSE GitHub repository](https://github.com/iVis-at-Bilkent/chise.js)
[SBGNViz.js GitHub repository](https://github.com/iVis-at-Bilkent/sbgnviz.js)

### Potential Mentors
Hasan Balci
Martina Summer-Kutmon

**Comment by SainiAditya1** [comment]
Hey @hasanbalci ,
I am keen on contributing to this issue as I have proficiency in JavaScript, Java,Cytoscape.js, HTML, and CSS. I am confident that I can provide valuable insights and assist in resolving it. Could you please direct me to the appropriate Slack , Discord channel  or any other medium of the organization? This way, I can address any queries I have regarding this issue.

**Comment by harshikagoyal14** [comment]
Hey @hasanbalci @mkutmon 
I am proficient in JavaScript and this project aligns well with my interests. Can you please assign this issue to me

**Comment by hasanbalci** [comment]
The contributor application period is March 18 – April 2. Here are some useful links:

[GSoC contributor guide](https://google.github.io/gsocguides/student/)
[NRNB project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
[Eligibility requirements](https://developers.google.com/open-source/gsoc/faq#what_are_the_eligibility_requirements_for_participation)
[Full program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by khanspers** [comment]
This is an active GSoC 2024 project. Closing this project idea as it is no longer available to other contributors.
