### ISSUE TITLE
 SBML Reporter: a new systems biology model documentation tool

### ISSUE THREAD

**Issue by mhucka** [nrnb/GoogleSummerOfCode#23]
## Background

[XML](https://en.wikipedia.org/wiki/XML) files such as the [systems biology](https://en.wikipedia.org/wiki/Systems_biology) modeling format [SBML](http://sbml.org) are not human-friendly. To understand what is inside an SBML file, a user must either examine the raw XML content or import the file into an application and examine it there. We developed [SBML2LaTeX](http://www.ra.cs.uni-tuebingen.de/software/SBML2LaTeX/) to provide humans with a more intelligible and direct description of an SBML file. SBML2LaTeX generates a structured, well-formatted report of the components and equations in a model (using [LaTeX](https://en.wikipedia.org/wiki/LaTeX) for formatting equations) and outputs LaTeX, [PDF](https://en.m.wikipedia.org/wiki/Portable_Document_Format), [PNG](https://en.m.wikipedia.org/wiki/Portable_Network_Graphics) and other formats.
### Goal

Develop a new application, _SBML Reporter_ based on the template SBML2LaTeX. The new architecture should separate the output presentation from the internal data structures used to represent the SBML model, and avoid SBML2LaTeX’s direct basis in LaTeX (because this basis introduces various limitations, particularly for large models). A major goal for the new SBML Reporter is to support output in [HTML5](https://en.m.wikipedia.org/wiki/HTML5) + [MathJax](https://www.mathjax.org); time-permitting, also support other formats such as LaTeX, PDF, plain-text, and/or image formats such as PNG.  Finally, time-permitting, experiment with embedding the SBML model directly inside PDF files. (Many models are small enough that the combination will not be large.) The result will be human-readable, yet contain the full model. We expect this will be a useful form in which to put models on the web, to enhance discoverability by search engines. (Google does not index XML attributes, making it difficult to search for models referencing such things as specific proteins or genes—if they are not mentioned in a text note within the model, the entities are effectively invisible in Google. A PDF-based description of a model would not share that problem.)
### Technologies

A starting point would be [SBML2LaTeX](http://www.ra.cs.uni-tuebingen.de/software/SBML2LaTeX/)
### Potential Mentors

[Andreas Dräger](mailto:draeger@informatik.uni-tuebingen.de)

### Contact

[SBML Team](mailto:sbml-team@caltech.edu)

Useful pointers to documentation related to GSOC for student on the main NRNB web site :
- [Resources](http://nrnb.org/gsoc.html)
- [How to apply](http://nrnb.org/gsoc.html#apply-tab)

**Comment by souravsingh** [comment]
Is the project open for NRNB Academy?

**Comment by draeger** [comment]
Yes, it is. Please see details about how to apply here: http://nrnb.org/gsoc.html. We can then get in touch and discuss all further questions you may have.

**Comment by khanspers** [comment]
Closing this as it is an active student project.

**Comment by khanspers** [comment]
Closing for GSoC 2019

**Comment by draeger** [comment]
@khanspers I am confused why this is being closed because this project has not (really) been tackled. We tried to work on this, but the student was not successful and we had to stop early on.
