### ISSUE TITLE
Implement AWS DevOps Pipeline for Image Deployment for Graphspace

### ISSUE THREAD

**Issue by maheshkasabe** [nrnb/GoogleSummerOfCode#234]
## Background

[GraphSpace](http://graphspace.org/) is an easy-to-use web-based platform collaborating research groups can use for storing, interacting with, and sharing networks. A GraphSpace user can upload graphs through a REST API, import graphs created in Cytoscape, interact with graphs (view them, customize layouts, and save layouts), share graphs (create groups and add collaborators, share graphs among all members of a group or with the world), search graphs, and organize graphs using tags. GraphSpace has a comprehensive REST API that allows users to communicate programmatically with it. Overall, GraphSpace provides a rich set of user-friendly features designed to enhance network-based collaboration.

## Goal

This GitHub issue is focused on continuing the work started in GSoC 2023 for the NRNB Org and GraphSpace project, specifically targeting the deployment aspect that remained incomplete. The goal is to create an AWS DevOps pipeline to automate the deployment process of an image to an EC2 instance.

The task involves creating an AWS DevOps pipeline that can efficiently retrieve an image and deploy it to an EC2 instance. The steps might include:

### 1. Setting up an AWS account and configuring necessary permissions:

- **AWS Account Creation:** If the contributor doesn't have an AWS account, they'll need to sign up for one. They can visit the AWS website (https://aws.amazon.com/) and create a new account. Some services may have free tiers for new accounts, which can be utilized for this project.
- **IAM (Identity and Access Management):** Once the AWS account is set up, the contributor needs to configure Identity and Access Management (IAM) to define roles and permissions. IAM allows creating users, groups, and roles with specific permissions to access AWS resources. Permissions must be set to allow the pipeline to interact with required AWS services like EC2, S3, or ECR (Elastic Container Registry).

### 2. Creating a pipeline script to fetch the image from a designated repository:

- **Source Control Management (SCM):** The project's code repository, likely hosted on platforms like GitHub, GitLab, or Bitbucket, will contain the pipeline configuration and scripts.
- **Pipeline Configuration:** Using a CI/CD service (e.g., AWS CodePipeline or Jenkins), a pipeline will be configured. This pipeline will have stages defining actions to be performed, such as retrieving the image from a specific repository (e.g., Docker Hub, AWS ECR, or another container registry).

### 3. Automating the deployment process to the EC2 instance:
- **EC2 Instance Configuration**: The EC2 instance should be set up and configured appropriately. This includes selecting the instance type, installing necessary software or dependencies, and ensuring security configurations (e.g., security groups, key pairs).
- **Deployment Automation:** The pipeline script will automate the deployment process. Once the image is fetched, it should be deployed to the EC2 instance. This might involve using tools like AWS CLI or SDKs to interact with the EC2 service to start a new instance or update an existing one with the latest image.

## Difficulty Level

Medium

## Size and Length of Project

- medium: 175 hours
 - 12 weeks

## Skills 

AWS
Docker
Python

### Primary Mentor
[Mahesh Kasbe](https://github.com/maheshkasabe) 

### Secondary Mentor 
[Yash Agarwal](https://github.com/yash170106065)
[Daniel Warsi](https://github.com/jahandaniyal)
## Public Repository

https://github.com/Murali-group/GraphSpace/ 

## IRC
Discord for GSoC 2023: https://discord.gg/AqjnwHndq8
Gitter for community: https://gitter.im/graphspace/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by g4ze** [comment]
Hello @maheshkasabe I'm interested in this project given the devops background I have. I'd love to contribute to this project and the Organisation in general. Could you please direct me to some place where I can start to contribute, solve some issues and get involved in the community?
I've done AWS projects implementing pipelines using EKS, CodePipeLine, ECR, S3 buckets, etc. This project would help me learn more. Thankyou.

**Comment by Stranger1145** [comment]
Hello I'm also interested in project . I'm a Devops Intern  It will be really helpful if I can contribute to the project.

**Comment by deep-poharkar** [comment]
hey @maheshkasabe @yash170106065 , i am really interested in contributing to this project as a mentee. talking about myself i have recently completed my lfx mentorship and also been a part of graphspace community since a year. i look forward to share ideas and work together :)

**Comment by khanspers** [comment]
NRNB has been accepted as a mentoring organization for GSoC 2024. The contributor application period if March 28 – April 2. Here are some useful links:

[GSoC contributor guide](https://google.github.io/gsocguides/student/)
[NRNB project proposal template](https://docs.google.com/document/d/1Zi6L38CHEeq2aL6xzv0Ozhd_Y6D71W3yCBGHplmxr6k/edit?usp=sharing)
[Eligibility requirements](https://developers.google.com/open-source/gsoc/faq#what_are_the_eligibility_requirements_for_participation)
[Full program timeline](https://developers.google.com/open-source/gsoc/timeline)

**Comment by devarsh10** [comment]
Hi @maheshkasabe, 
I am Devarsh Shah from India. Currently, I am in my final semester. I have internship exposure in Cloud and DevOps & I am currently interning as a Full-Stack Developer.
I have created a Prototype/Flowchart considering all the points, mentioned in the Description. 

Could you please provide guidance, on what kind of ECR/DockerHub Image Deployment we'll be doing? What the Image will contain?

Kind Regards,
Devarsh Shah.

**Comment by khanspers** [comment]
This is an active GSoC 2024 project. Closing this project idea as it is no longer available to other contributors.
