### ISSUE TITLE
ASCETIC API and Shiny App

### ISSUE THREAD

**Issue by marcoxa** [nrnb/GoogleSummerOfCode#236]
### Background

By leveraging the ever-increasing availability of cancer omics data and the continuous advances in cancer data science and machine learning, we have discovered the existence of *cancer (sub)type-specific evolutionary signatures* associated with different disease outcomes. These signatures represent "favored trajectories" of driver genes acquisition that are repeatedly detected in patients with similar prognosis. The *Agony-baSed Cancer EvoluTion InferenCe* (ASCETIC) is a novel framework that extracts such signatures from NGS experiments generated by different technologies such as bulk and single-cell sequencing data (cfr., [1]).

### Goal

The goal of the the project is to design an *API* to the ASCETIC analysis pipeline and to develop a dedicated *Shiny App* with enhanced data processing, interaction and visualization capabilities.

### Difficulty Level: Medium

The difficulty of the project is twofold: first of all the developer will have to fully understand the ASCETIC pipeline, both from the machine learning and the mathematical perspectives.  Secondly, the developer will have to design an API that will ease the ASCETIC use, in addition with a new easy-to-use Shiny App.  The App will take as input raw (DNA or RNA) sequencing data and will provide as output interactive models of cancer evolution, and the stratification of patients in prognostically significant clusters, related to the discovered evolutionary signatures.  Results will be delivered both in a easy-to-understand graphical fashion, and in file formats complaint to other data analysis pipelines.

#### Size

The project size is **medium: 175 hours**.

#### Length

Timeline is **flexible** and the project is **12 weeks**

### Skills

* Essential skills: R, understanding of machine learning and mathematical models. 
* Nice to have skills: knowledge of **Bioconductor** distribution

### Public Repository

The current repository is:
[ASCETIC](https://github.com/danro9685/ASCETIC "ASCETIC Github
link").  A new one will probably be needed in the future.

### References

1. [Fontana, D., et al., *Nat Commun* 14 (2023)](https://doi.org/10.1038/s41467-023-41670-3 "Nature Communication Ascetic paper")

### Potential Mentors

* Alex Graudenzi, <alex.graudenzi@unimib.it>
* Daniele Ramazzotti, <daniele.ramazzotti@unimib.it>
* Marco Antoniotti, <marco.antoniotti@unimib.it>

**Comment by divyansh169** [comment]
Hello @marcoxa @khanspers 
I am interested in contributing to this issue as I am compatible with this tech stack and currently learning about the project.
Can you please guide where to ask project related queries?

**Comment by luke-estes** [comment]
Hello my name is luke, I have 2 years experience with R and have some experience and interest in working phylogenies. how would I go about joining the team?

**Comment by khanspers** [comment]
This is an active GSoC 2024 project. Closing this project idea as it is no longer available to other contributors.
