### ISSUE TITLE
Integration of complexity score functions into the iGEM DNA kit distribution workflow

### ISSUE THREAD

**Issue by Gonza10V** [nrnb/GoogleSummerOfCode#242]
### Background
Synthetic biologists use the Design, Build, Test, Learn (DBTL) cycle to engineer biological systems. The Synthetic Biology Open Language (SBOL) was developed by the community as a standard to represent biological designs and covers the whole DBTL cycle. Although this standard is used and agreed by the community it is mostly used in its visual format and the data format has not been widely adopted, being PDF the primary format to share DNA sequences. The adoption of SBOL[1] by the community can increase the reproducibility of experiments, facilitating building upon previous knowledge. 
To streamline the DBTL cycle and increase the adoption of SBOL we propose the development of a workflow prototyped at iGEM, that uses complexity score functions to facilitate DNA synthesis orders using Excel as user interface and storing metadata in SBOL.

[1] Buecherl, Lukas, Mitchell, Thomas, Scott-Brown, James, Vaidyanathan, Prashant, Vidal, Gonzalo, Baig, Hasan, Bartley, Bryan, Beal, Jacob, Crowther, Matthew, Fontanarrosa, Pedro, Gorochowski, Thomas, Grünberg, Raik, Kulkarni, Vishwesh, McLaughlin, James, Mısırlı, Göksel, Oberortner, Ernst, Wipat, Anil and Myers, Chris. "Synthetic biology open language (SBOL) version 3.1.0" Journal of Integrative Bioinformatics, vol. 20, no. 1, 2023, pp. 20220058. https://doi.org/10.1515/jib-2022-0058

### Goal
Develop an updated workflow that uses the existing iGEM DNA kit distribution workflow to integrate a synthesizability assessment of genetic designs and build plans for DNA assembly.

Specific Goals:
Integrate a complexity score function or mediator into the [iGEM-distribution](https://github.com/iGEM-Engineering/iGEM-distribution) GitHub Actions.
Encode results in the workflow output and in SBOL.
Create a visualization showing designs synthesizable by all providers in the mediator for a synthesis order.
Document the workflow and how to use actions to modify SBOL files.

### Difficulty Level: Easy/Medium/Hard
This project involves the development of GitHub actions, integration of Python code and coordination with the iGEM Engineering Committee.

### Size and Length of Project
- **medium: 175 hours**
- **16 weeks**

### Skills
Essential skills: GitHub Actions, Git
Nice to have skills: Python, Excel

### Public Repository
https://github.com/iGEM-Engineering/iGEM-distribution

### Potential Mentors
Gonzalo Vidal (Gonzalo.vidalpena@colorado.edu)
Jake Beal

**Comment by jguillen15** [comment]
I would like to work on this project.
Thanks.

**Comment by Gonza10V** [comment]
Hi @jguillen15 thanks for your interest in the project. Please familiarize yourself with the GitHub actions used in the public repository https://github.com/iGEM-Engineering/iGEM-distribution. Let me know if you have any doubt about the specific goals that will guide the project advance.

**Comment by khanspers** [comment]
@jguillen15 : All proposals for GSoC must be submitted via the GSoC interface before the deadline (April 2, 18:00 UTC); we cannot consider proposals sent to us by other means. You can update a draft proposal in the GSoC interface up until the deadline.

**Comment by jguillen15** [comment]
Thank you @Gonza10V , I will start familiarizing myself with the GitHub actions used in the iGEM distribution repository.
Thank you @khanspers , I will submit my candidacy to the GSoC portal as well.

**Comment by giahienpham** [comment]
@jguillen15 @khanspers Hi, my name is Hien Pham from Vietnam and I'm a CS & Math student at US. I'm very, very interested and would love to contribute to this project because I have been interested about Biology since primary school. My goal is to learn more from the experts and use my skillset to create a meaningful application for our community. I have summitted my application on GSoC and I'm looking forward to work, learn and delve into biology world like you guys!

**Comment by khanspers** [comment]
Hi @giahienpham: The deadline for GSoC applications is today at 18:00, in 2 hours. Applications must be submitted through the GSoC interface: https://summerofcode.withgoogle.com/.

**Comment by khanspers** [comment]
This is an active GSoC 2024 project. Closing this project idea as it is no longer available to other contributors.
