### ISSUE TITLE
BridgeDb plugin for PathVisio

### ISSUE THREAD

**Issue by mkutmon** [nrnb/GoogleSummerOfCode#27]
### Background
[BridgeDb ](http://www.bridgedb.org)is an identifier mapping framework used in [PathVisio ](http://www.pathvisio.org)and [WikiPathways](http://www,wikipathways.org). Currently it is possible to load a mapping databases for gene products and metabolites. This should be extended with interaction mapping databases.

### Goal
The existing [BridgeDbConfig plugin](http://developers.pathvisio.org/wiki/BridgeDbConfigPluginHelp) provides functionality to load more mapping databases or to use other web services for the mappings. This functionality should be extended and integrated into the core PathVisio application as another core module. The configuration dialog has to be improved so it is more intuitive and user friendly. Furthermore the plugin should allow users to download and update BridgeDb mapping databases from within PathVisio. Currently the users have to download the databases first and then load them into PathVisio. This step should be automatized by the plugin.

### Difficulty Level 2
Separate plugin but with consequences for the core parts of the program.

### Skills
Java (essential)
PathVisio, BridgeDb (nice to have)

### Public Repository
https://github.com/pathvisio/pathvisio
https://github.com/bridgedb/BridgeDb

### Potential Mentors
[Martina Kutmon](mailto:mkutmon@gmail.com)

### Contact
[Martina Kutmon](mailto:mkutmon@gmail.com)

**Comment by PratyushTalreja** [comment]
Hi

I am Pratyush Talreja from Indian Institute of Technology Bombay. I am having experience in Java development.

I am interested in applying for this Idea. Can you please help me get started.

**Comment by khanspers** [comment]
@PratyushTalreja Please contact the mentor directly (mkutmon@gmail.com), since questions posted here may go unnoticed. For more information on the application process, see http://nrnb.org/gsoc.html.
