### ISSUE TITLE
Improved citation framework for PathVisio and WikiPathways

### ISSUE THREAD

**Issue by mkutmon** [nrnb/GoogleSummerOfCode#28]
### Background
[PathVisio](http://www.pathvisio.org) is a commonly-used pathway editor, visualization and analysis tool implemented in Java and is linked with the collaborative pathway database [WikiPathways](http://www.wikipathways.org). In the pathway models created by PathVisio, curators can add references to literature for every element in the pathway (including the complete pathway). Currently, only the search and annotation of [PubMed](http://www.ncbi.nlm.nih.gov/pubmed) identifiers is enabled but there are existing libraries that allow querying of DOIs etc. 

### Goal
The goal of this project is to extend the functionality to allow the reference of other identifiers like [DOIs](https://en.wikipedia.org/wiki/Digital_object_identifier), export references in standard formats like [Bibtex](http://www.bibtex.org/) or EndNote and provide statistics about citations used on WikiPathways (total number of citations, avg. number of citations per pathway, top cited papers/journals, ...).

### Difficulty Level 2
The student will need to adapt the user interface in the PathVisio core application, implement functionality to query other services besides PubMed, and adapt the WikiPathways pathway page to show those references and their linkouts correctly.

### Skills
Java, PHP (essential)
mediawiki (nice to have)

### Public Repository
PathVisio: https://github.com/PathVisio/pathvisio
WikiPathways: https://github.com/wikipathways/wikipathways.org

### Potential Mentors
[Martina Kutmon](mailto:mkutmon@gmail.com)
[Egon Willighagen](mailto:egon.willighagen@gmail.com)

### Contact
[Martina Kutmon](mailto:mkutmon@gmail.com)

**Comment by koppor** [comment]
Possibly related: The recommender system of Docear. See http://www.docear.org/docear/blog/.

**Comment by khanspers** [comment]
Closing for GSoC 2019.
