### ISSUE TITLE
Extending and improving PathVisio data import

### ISSUE THREAD

**Issue by mkutmon** [nrnb/GoogleSummerOfCode#29]
### Background
[PathVisio](http://www.pathvisio.org) is a pathway editor and analysis tool. PathVisio allows users to upload and visualize data on biological pathways. Currently, it is possible to upload only one dataset at a time as a comma separated file. This process needs to become more user-friendly and flexible. Check 
out the PathVisio [data visualization tutorial](https://www.pathvisio.org/documentation/tutorials/tutorial-2/) on how the data import works at the moment. 

**Features:**
- Loading multiple datasets at once: these could be any kind of quantitative or qualitative data about any pathway element, such as genes, proteins, metabolites, and interactions.
- Linking each individual dataset to a particular element on a pathway, for eg. linking a gene expression dataset to genes on pathways and a flux data set to interactions on pathways.
- Importing data from multiple file formats (For eg: .xls, .ods).
- Create a pop-up panel accessible from the menu bar of the PathVisio main window to show (1) all the currently loaded datasets, (2) the biological elements they are linked to, and (3) the currently loaded annotation databases.

### Goal
This functionality should be extended to allow uploading a number of data files at the same time as well as uploading of multiple data file formats (for eg. Excel sheets) should be allowed. This will involve extending the gex and data modules of PathVisio. These modules are part of the PathVisio core and take care of importing experimental data and mapping it to the elements in a pathway.

### Difficulty Level 2
Changes in the core part of the application.

### Skills
Java (essential)

### Public Repository
https://github.com/pathvisio/pathvisio

### Potential Mentors
[Martina Kutmon](mailto:mkutmon@gmail.com)

### Contact
[Martina Kutmon](mailto:mkutmon@gmail.com)

**Comment by JUDEX24** [comment]
Good day,

I am a Computer science 3rd yr student with some background in Java, C++. I was just reading through this project and found it really interesting. I would like to part-take on working on this project however I am new to the GSoC environment. Therefore I would like some assistance to get started, and maybe requirements info as well as how to facilitate communication with mentors.

Thank you
