### ISSUE TITLE
Tutorial mode for PathVisio

### ISSUE THREAD

**Issue by mkutmon** [nrnb/GoogleSummerOfCode#31]
### Background

[PathVisio ](http://www.pathvisio.org) is a commonly-used pathway editor, visualization and analysis tool implemented in Java. The analyses in PathVisio and the different advanced visualization methods can become very complex and having an integrated tutorial mode in the application is a powerful tool to give detailed instructions while performing a task.
### Goal

Documentation and tutorials are crucial elements of software development and the goal of this project is to implement a tutorial mode in PathVisio. This will be implemented as a set of interactive tutorials available in a new side panel. It will give the users a step-by-step guide with hints and additional information while learning how to use PathVisio. PathVisio can be extended through [plugins](http://www.pathvisio.org/plugins/plugins-repo/), so the tutorial mode should allow other modules to provide additional tutorials that can be selected if the plugins are installed. 
Initially, three basic tutorials should be implemented: pathway drawing, data mapping and visualization and over-representation analysis.
### Potential Mentors

[Martina Kutmon](mailto:mkutmon@gmail.com), [Kristina Hanspers](mailto:kristina.hanspers@gladstone.ucsf.edu), [Sravanthi Sinha](mailto:kmitsravanthi@gmail.com)
### Contact

[Martina Kutmon](mailto:mkutmon@gmail.com), [Kristina Hanspers](mailto:kristina.hanspers@gladstone.ucsf.edu), [Sravanthi Sinha](mailto:kmitsravanthi@gmail.com)

**Comment by PratyushTalreja** [comment]
Hi

I am Pratyush Talreja from Indian Institute of Technology Bombay. I am having experience in Java development.

I am interested in applying for this Idea. Can you please help me get started.

**Comment by AlexanderPico** [comment]
Hi Pratyush,

The best way to get started is to contact mentors via their links above. And instead of asking for general help, it's better to research the topic as much as possible and ask specific questions, so that the mentors can tell what you know already and where you are stuck.

**Comment by PratyushTalreja** [comment]
Thank you AlexanderPico

**Comment by mkutmon** [comment]
removed for 2018 GSoC idea list
