### ISSUE TITLE
Interconversion between the systems biology modeling formats SBML and BioPAX

### ISSUE THREAD

**Issue by draeger** [nrnb/GoogleSummerOfCode#33]
### Background

[BioPAX](http://biopax.org) and [SBML](http://sbml.org) belong to the most popular modeling and data exchange languages in systems biology. While SBML focusses on quantitative modeling and dynamic simulation of models, BioPAX concentrates mainly on visualization and qualitative analysis of pathway maps. BioPAX describes reactions and relations. In contrast, SBML core exclusively describes quantitative processes such as reactions. The SBML extension for [Qualitative Models (qual)](http://bmcsystbiol.biomedcentral.com/articles/10.1186/1752-0509-7-135), makes interconversion between both formats possible. The tools BioPAX2SBML and SBML2BioPAX have been developed for interconversion. Since then, both SBML and BioPAX have further developed and come now with enhanced model components that are not yet covered by neither converter.

### Goal

In this project, we will enhance [BioPAX2SBML](http://bioinformatics.oxfordjournals.org/content/28/20/2648) in response to experiences with its use and specific feedback from the BioPAX community. We will also enhance [SBML2BioPAX](http://sbfc.sourceforge.net/mediawiki/index.php/SBML2BioPAX) to translate more SBML constructs, handle SBML Level 3 packages to the extent possible, and add features requested by the BioPAX community. Both programs should be incorporated into one common framework.

### Technologies

 * [BioPAX2SBML](http://www.cogsys.cs.uni-tuebingen.de/software/BioPAX2SBML/)
 * [SBML2BioPAX](http://sbfc.sourceforge.net/mediawiki/index.php/SBML2BioPAX)
 * [SBML qual](http://co.mbine.org/specifications/sbml.level-3.version-1.qual.version-1.release-1.pdf)

### Potential mentors

Andreas Dräger, Michael Hucka, Nicolas Rodriguez, Akira Funahashi

### Contact

[SBML Team](mailto:sbml-team@caltech.edu)

Useful pointers to documentation related to GSOC for student on the main NRNB web site :
* [Resources](http://nrnb.org/gsoc.html)
* [How to apply](http://nrnb.org/gsoc.html#apply-tab)

**Comment by abhishek0198** [comment]
@draeger @mhucka @niko-rodrigue @funasoul 
I am Abhishek, computer science undergraduate student from India. I am very interested in working on this project. I went through the documentation of SBML (http://sbml.org/Main_Page) and JSBML library (http://sbml.org/Software/JSBML) and understood the format and parsing mechanism. 

I would like to get started by setting up local dev to be more specific on my proposal for this project. I am assuming I need BioPAX2SBML and SBML2BioPAX in order to get started. Are there any dev docs avaialble to get started?

Also what is the best method to communicate regarding questions/issues? 

Thanks

**Comment by draeger** [comment]
The best way to get started is by creating a Google Document for your application and to share it with all potential mentors. The easiest way to do so is to post the link to the mailing list sbml-team@caltech.edu.

**Comment by abhishek0198** [comment]
Thanks @draeger, Is there a recommended format of proposal for this project?

**Comment by draeger** [comment]
There is no official template, but the application should cover:
* A section about yourself including (but not limited to)
  * Your contact information
  * Your motivation why you want to work on that project
  * Your relevant skills you can contribute and devote to the project
  * Your relevant experience
* A section about the project, which could, for instance, include
  * Project deliverables
  * A detailed project plan with weekly descriptions of aims, e.g., in form of a Gantt chart
  * Expected difficulties
  * Time that can be exclusively devoted to the project
  * Your personal contribution

I strongly recommend to just getting something started and to discuss on the private mailing list.

**Comment by niko-rodrigue** [comment]
You check the main NRNB web site for GSOC that contain many pointers to documentation related to GSOC for student: http://nrnb.org/gsoc.html

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
