### ISSUE TITLE
Import graphs in multiple formats into GraphSpace

### ISSUE THREAD

**Issue by tmmurali** [nrnb/GoogleSummerOfCode#36]
### Background
[GraphSpace](http://graphspace.org) is an easy-to-use web-based platform  collaborating research groups can use for storing, interacting with, and sharing networks. A GraphSpace user can upload graphs through a REST API, import graphs created in [Cytoscape](http://www.cytoscape.org), interact with graphs (view them, customize layouts, and save layouts), share graphs (create groups and add collaborators, share graphs among all members of a group or with the world), search graphs, and organize graphs using tags. GraphSpace has a comprehensive REST API that allows users to communicate programmatically with it. 

### Goal
GraphSpace currently allows import of networks specified in a JSON format. This project will add functionality to import networks in other formats, e.g., GPML, BioPAX, and GraphML. Users should be able to import graphs both through the [network upload page](http://graphspace.org/graphs/upload) as well as by using the [REST API](http://graphspace.org/help/programmers).  

### Potential Mentor
[T. M. Murali](http://bioinformatics.cs.vt.edu/~murali/)

### Contact
murali@cs.vt.edu

**Comment by MridulS** [comment]
@tmmurali I found this project to work on over the summer. Any pointers where to start from?

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
