### ISSUE TITLE
Import Cytoscape files into GraphSpace 

### ISSUE THREAD

**Issue by tmmurali** [nrnb/GoogleSummerOfCode#37]
### Background
[GraphSpace](http://graphspace.org) is an easy-to-use web-based platform  collaborating research groups can use for storing, interacting with, and sharing networks. A GraphSpace user can upload graphs through a REST API, import graphs created in [Cytoscape](http://www.cytoscape.org), interact with graphs (view them, customize layouts, and save layouts), share graphs (create groups and add collaborators, share graphs among all members of a group or with the world), search graphs, and organize graphs using tags. GraphSpace has a comprehensive REST API that allows users to communicate programmatically with it. 

### Goal
GraphSpace can import "cyjs" files that can be exported by Cytoscape. These files are in JSON format. However, it appears that these files may not store information related to node or edge color/size/shape. This project will enhance the exporter for Cytoscape files to store not just the nodes and edges but also their colors, sizes, and shapes, and their x- and y-coordinates, if possible. Users should be able to import graphs both through the [network upload page](http://graphspace.org/graphs/upload) as well as by using the [REST API](http://graphspace.org/help/programmers).  

### Difficulty level 1:
No prior experience with Cytoscape or GraphSpace development is required.

### Potential Mentor
[T. M. Murali](http://bioinformatics.cs.vt.edu/~murali/)

### Contact
murali@cs.vt.edu

**Comment by srikanthBezawada** [comment]
Hi Murali,

Is the goal of the project to enhance the Cytoscape core feature (File -> Export -> Network -> (cyjs)) ? OR can it be done by a Cytoscape app which adds a new export feature with better compatibility for GraphSpace. Just assessing the project idea.

Thanks,
Srikanth.

**Comment by AlexanderPico** [comment]
Hi Srikanth.  You should contact mentors directly by means of their recommended info (see "Contact" above). They might not see the questions here...

**Comment by tmmurali** [comment]
Hi Srikanth,
  I don't see a way to contact you by email so I am replying via GitHub. A Cytoscape app seems like a better option. Essentially, we would like to try to replicate in GraphSpace as much as possible of the layout (coordinates) and node and edge styles of a Cytoscape network. I am imagining situations where a Cytoscape user spends a lot of time positioning nodes and edges and styling them and wants to export to GraphSpace to easily share with other colleagues. Let me know if you have more questions. Email to murali@cs.vt.edu is the best way to reach me.
   Murali

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
