### ISSUE TITLE
Drag and Drop or Palette Editor for SBGN and other graphical notations in Cytoscape

### ISSUE THREAD

**Issue by scootermorris** [nrnb/GoogleSummerOfCode#39]
### Background

The [Systems Biology Graphical Notation (SBGN)](http://www.sbgn.org/Main_Page) is a standard graphical notation for presenting pathways and protein interactions. Currently, [Cytoscape](http://www.cytoscape.org) lacks the node symbols and edge types required for SBGN. In this project, those notations will be added to the [Cytoscape core](http://cytoscape.org/documentation_developers.html), and a simple palette editor developed for user interaction. Relevant work as a Cytoscape 2 plugin called [CySBGN](http://apps.cytoscape.org/apps/cysbgn) could serve as reference material.
### Goal

The goal is to design and implement a drag-and-drop or palette-based editor for Cytoscape. The editor would include nodes, edges, and graphical annotations. The initial palette would be based on SBGN, but we envision adding other options to the editor to replace the current right-click actions for adding nodes, edges, and annotations.  In the ideal case, this would be extensible so that apps add their own nodes or edges with specific graphical attributes. 
### Difficulty Level: 2

Some experience with Cytoscape and/or implementing editor tools is preferred.
### Potential Mentors
- Scooter Morris
- Alex Pico
### Contact

[Scooter Morris](mailto:scooter@cgl.ucsf.edu)

**Comment by Kera24** [comment]
@AlexanderPico I would like to work on this project. After going through the initial requirement. How should I proceed?

**Comment by AlexanderPico** [comment]
@Kera24 Go through the [Cytoscape App developer ladder](https://github.com/cytoscape/cytoscape/wiki/Cytoscape-App-Ladder) and see how far you get. Let us know by email: alex.pico@gladstone.ucsf.edu. Also share your prior Java experience (required) and any prior experience with SBGN or other biology related glyphs or curation standards (optional).
