### ISSUE TITLE
Developing Web Interface For The Online Resource for Interface- Based Interaction Networks (TOR-IBIN) 

### ISSUE THREAD

**Issue by MoHelmy** [nrnb/GoogleSummerOfCode#4]
### Background
The protein-protein interaction (PPI) is a physical contact between two proteins, or more, resulted from biochemical reaction or electrostatic forces. The interaction usually takes place through an Interface, which is part of the protein (e.g. protein domain) with special molecular structure that enables and mediates the interaction between proteins. Interface-based PPI predictions help in understanding the mechanisms of interactions between proteins as well as helps in deciphering the functional roles of the proteins.

### Focus
*TOR-IBIN* is an online resource for gathering and storing the published interface-based (IB) protein-protein interaction networks (IN) predicted using any PPI prediction method. *TOR-IBIN* aims to make these networks available in a central repository with unified format and comprehensive search functions that maximize the use of these data. *TOR-IBIN* web-based interface aims to implement the browse and search functions and well as network visualization using [Cytoscape.js](http://js.cytoscape.org/) and network download in several formats including JSON and tab-delimited formats. *TOR-IBIN* is a relational database implemented in MySQL. 
The web interface and functionality will be similar to the web interface of the [Cancer Variants Database (Can-VD)](http://canvd.baderlab.org).

### Goals
1- Develop a web-based interface for interface-based PPI data retrieval with a comprehensive search functions and data download options.
2- Develop a visualization and annotation module using [Cytoscape.js](http://js.cytoscape.org/) to visualize the retrieved PPI data as a network with annotations that highlights the features of the predicted PPI such as the prediction confidence and validation...etc.

### Inputs
The student will be provided with the database design and sample data as well as an introduction to the topic and the different possible visualizations and annotations needed. The student will have the freedom to choose among them or to propose other options.

### Technology and Skills
Cytoscape.js, Javascript, JSON, PHP, JQuery

### Potential Mentors
Mohamed Helmy, Gary Bader

### Contact
[Mohamed Helmy](mailto:mohamed.attiashahata@utoronto.ca), [Gary Bader](mailto:gary.bader@utoronto.ca)

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
