### ISSUE TITLE
Improve and expand Cytoscape’s color mapping options

### ISSUE THREAD

**Issue by scootermorris** [nrnb/GoogleSummerOfCode#40]
### Background

Currently, the color options for [Cytoscape’s](http://www.cytoscape.org) discrete color mappings are very limited.  Several sites exist to provide dynamic color palettes, including [ColorBrewer](http://colorbrewer2.org/) and [COLOURLovers](http://www.colourlovers.com/).  COLOURLovers provides a REST interface, and there are Java libraries for generating Brewer colors. 
### Goal

The goal behind this project is to create an interface to extend the current palette for discrete colors and continuous colors and utilize that interface to access palettes from COLOURLovers and create Brewer colors.  This would significantly enhance the ability of users to generate palettes of colors that are perceptually similar in luminosity but divergent in hue or somehow consistent with a relevant color scheme that reflects the node identity or value.
### Skills

Java, Cytoscape
### Potential Mentors

Scooter Morris
### Contact

scooter@cgl.ucsf.edu

**Comment by heuermh** [comment]
Willing to help mentor if necessary, I wrote a [java library](http://www.dishevelled.org/color-scheme/) that includes schemes based on ColorBrewer among others.

**Comment by ssinghal123** [comment]
Hi, I am Shubham Singhal, a fourth year undergraduate from IIT Bombay. I am interested in this idea to work upon for Google Summer of Code 2016 and would like to contribute to NRNB. However, to be honest, I am not familiar with Cytoscape. Is it possible to start working on this project without having enough knowledge about it? If, this is the case, I would like to contribute towards the idea and submit a proposal.

**Comment by AlexanderPico** [comment]
Hi Shubham,

As a "difficulty:1" project, I think it's possible without prior Cytoscape experience.  Demonstrating your capacity to pick up on Cytoscape and color palette libraries during the application process will be important. Follow the link to Cytoscape and go through the developer documents, for example. then contact the mentor directly  (see Contact info) and describe your experience level and any specific questions you have.
