### ISSUE TITLE
Visualization of Time-series Cluster Data

### ISSUE THREAD

**Issue by scootermorris** [nrnb/GoogleSummerOfCode#43]
### Background

Currently, the [clusterMaker app](http://apps.cytoscape.org/apps/clustermaker2) uses standard heat maps to visualize attribute cluster data (based on Java TreeView). Increasingly, time series data is becoming important for clustering applications and it would be useful to expand the provided visualization options to explicitly support time series data. For these purposes, we’re thinking about time-series that have multiple conditions in each series, which means we need to move beyond the standard two-dimensional heat map. 
### Goal

This project can explore utilizing animation, [small multiples](https://en.wikipedia.org/wiki/Small_multiple), or other standard visualization techniques (or your own novel techniques) to provide new visualization opportunities to users. Ideally, this would be integrated with network-based animation tools such as [DynNetwork](http://apps.cytoscape.org/apps/dynnetwork) or [CyAnimator](http://apps.cytoscape.org/apps/cyanimator). We are expecting students to independently research visualization techniques and propose implementation plans that can work in a Cytoscape app.
### Difficultly Level: 2

While no prior experience is necessary, this project does expect a fair amount of independent research on a tough visualization challenge, plus rapid uptake of multiple Cytoscape apps, most critically, the [clusterMaker app](http://apps.cytoscape.org/apps/clustermaker2).
### Technology and Skills

Cytoscape, Java
### Public Repository 

https://github.com/RBVI/clusterMaker2
### Potential Mentors

Scooter Morris
### Contact

scooter@cgl.ucsf.edu

**Comment by cdgramos** [comment]
I'm currently working with data-series in my master thesis but I don't need to really visualize them. This would be interesting for me to implement.

The main steps for making it I idealized are:
 - Plot the "dots" of the values
 - Connect them
 - Add the hability to add more than one data serie to the scene
 - Add the possibility to change the color
 - Zoom in and out

**Comment by martincerny** [comment]
I think that implementation of this could be based on CyDataSeries (https://github.com/martincerny/cy-dataseries) which imports and visualises time series (although at present, its rather basic)

**Comment by AdrianBZG** [comment]
Hi @scootermorris ,

I'm a senior Computer Science university student from Spain, and I feel interested on this project for GSoC'17.

After reading the project goal I have some questions, can you please illustrate me with the project idea of the time series representation, or give me a use-case scenario?

Thank you!
