### ISSUE TITLE
Implement a Cytoscape App to generate a legend as part of the network

### ISSUE THREAD

**Issue by scootermorris** [nrnb/GoogleSummerOfCode#44]
### Background

[Cytoscape](www.cytoscape.org) currently provides a number of tools to represent data values as colors, sizes, shapes, and other visual attributes. Currently, the only way to generate a legend that equates these visual attributes to data ranges is part of the [Visual Styles panel](http://wiki.cytoscape.org/Cytoscape_3/UserManual/Styles) and the result is an image that must be separately edited and integrated into the network image. New features in Cytoscape 3 allow graphical annotations to be created and grouped together as part of the network panel.  These graphical annotations are exported as part of the high-resolution network image.
### Goal

The goal of this project is two fold:
1. Provide a tool to align graphical annotations
2. Provide a tool that will generate a legend built with graphical annotations that may be positioned and moved on the network canvas.
### Difficulty level: 2

Prior experience with Cytoscape app development is recommended. Prior Java graphics experience is a plus.
### Technology and Skills

Java, Cytoscape
### Potential Mentors

Scooter Morris
### Contact

scooter@cgl.ucsf

**Comment by devkhan** [comment]
I'm interested in this project. I have experience in Java (mostly via Android) and I know a little about Cytoscape. Can you please guide me how to proceed with this project? Any resources, material, links, etc.?

**Comment by khanspers** [comment]
Hi Devesh, please contact the mentor directly as messages on github may not be noticed right away.
