### ISSUE TITLE
Implement Principal Coordinate Analysis in clusterMaker

### ISSUE THREAD

**Issue by scootermorris** [nrnb/GoogleSummerOfCode#45]
### Background
One technique for dimensionality reduction is [principal coordinate analysis (PCA)](https://en.wikipedia.org/wiki/Principal_component_analysis).  This technique is an analog of principal component analysis, but it works on distance matrices, which are not appropriate for principal component analysis.  Adding this to [clusterMaker](http://apps.cytoscape.org/apps/clustermaker2) would allow users to select the edges to retain based on an analysis of the contributed variance.

### Goal
The goal of this project is to add PCA to clusterMaker and provide useful visualizations that will allow users to select the components to remove from the network and those to retain.  As networks get larger and larger, providing tools to reduce the dimensionality of graphs is going to be increasingly important, and this could provide one approach to doing so.

### Difficulty level: 1
Prior experience with Cytoscape app development is not required.

### Technology and Skills
Java, Cytoscape, matrix math

### Potential Mentors
Scooter Morris

### Contact
scooter@cgl.ucsf.edu

**Comment by SupunArunoda** [comment]
Are there any errors in github example repository? Some exceptions have occurred while run them using maven...

**Comment by khanspers** [comment]
Hi. Which repository are you referring to? If you have questions about the PCA in clustermaker project, please contact the mentor directly by means of the recommended info (see "Contact" above). They might not see the questions here.

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
