### ISSUE TITLE
Collaborative System for Creating/Sharing Biological Icons

### ISSUE THREAD

**Issue by ariutta** [nrnb/GoogleSummerOfCode#5]
### Background

Biological pathways provide intuitive diagrams of the interactions underlying biological processes. For example, the [SIDS Susceptibility Pathways](http://wikipathways.org/index.php/Pathway:WP706) shows interactions between metabolites, genes and proteins, such as DDC catalyzing the conversion of L-DOPA to Dopamine (look for the items highlighted in yellow on the lower right). The site [WikiPathways](http://www.wikipathways.org) is an open, collaborative platform dedicated to drawing and sharing biological pathways. These pathways often use icons to represent items like mitochondria or cardiac myocytes (heart muscle cells). The WikiPathways drawing editor has a limited set of icons built in, but it does not allow pathway authors to create and re-use custom icons. For example, the cardiac myocyte icon is repeated in the SIDS Susceptibility Pathways for mouse and for human, but the only way to re-use the icon is to manually redraw or copy/paste it. Improvements to the icon in one pathway do not appear in the other.
### Goal

Build a biological icon library that allows pathway authors to create icons, share them with other WikiPathways’ users and reuse them across pathways. It could work like GitHub for icons, allowing users to create, fork and merge their work, with the best icons rising to the top via a rating system. The library will work as a plugin for the current WikiPathways viewer/editor [Pvjs](https://github.com/wikipathways/pvjs), allowing pathway authors to draw or import new icons. It may have a backend component to store the icons and a front-end component to allow WikiPathways users to view and search for icons. See [my comment below](https://github.com/nrnb/GoogleSummerOfCode/issues/5#issuecomment-192381595) for more details.
### Links
- [This SVG drawing tool](https://code.google.com/p/svg-edit/) has a large number of icons. It might provide some ideas.
- We're currently using [this library](https://github.com/ariutta/cross-platform-shapes) for our shape generation.
- [Another shape library of interest](https://github.com/sebmarkbage/art/).
### Difficulty Level: 3

Prior experience with WikiPathways required. Strong JavaScript skills required, because this project will likely require some refactoring of the existing code for Pvjs. Some backend experience (PHP, Node.js or Python) may be required to create a backend for saving the icons. SVG or Canvas experience a plus.
### Technology and Skills
- WikiPathways
- JavaScript
- PHP, Node.js or Python
- SVG or Canvas
### Potential Mentors
- Anders Riutta
- Alex Pico
- Kristina Hanspers
### Contact

[Anders Riutta](mailto:anders.riutta@gladstone.ucsf.edu), [Alex Pico](mailto:alex.pico@gladstone.ucsf.edu), [Kristina Hanspers](mailto:kristina.hanspers@gladstone.ucsf.edu)

**Comment by maxkfranz** [comment]
It would be good to have icon font generation using [fontcustom](https://github.com/FontCustom/fontcustom).  For example, there is a set of model organism icons from the GeneMANIA project using fontcustom: https://github.com/GeneMANIA/bio-icons

You may want to take some inspiration from the [Noun Project](https://thenounproject.com/), as this project looks like a bio-centric take on it.  Though having an embedded editor is great, I suspect people will also want SVG upload (because they use Inkscape, Illustrator, etc.).

**Comment by ariutta** [comment]
Great suggestions -- thanks @maxkfranz!

One note: some of the icons are multi-colored (e.g., the cardiomyocytes in the SIDS Susceptibility Pathways linked above). The font icons are single colored only, right?

**Comment by maxkfranz** [comment]
Icon fonts are usually single coloured so you can colour each instance as desired.  Fonts definitely also support explicit colourings (with multiple colours), like the emojis used on iOS and Mac.  Worst case, you can always a large SVG sheet for good compatibility across devices/OSes/etc.

**Comment by ariutta** [comment]
More resources:
We're currently using [this library](https://github.com/ariutta/cross-platform-shapes) for our shape generation. Other options to explore include [this alternative library](https://github.com/sebmarkbage/art/).

Some icons may need to be able to be resizable while maintaining selected dimensions of sub-parts, e.g., an icon for a double-walled cell compartment might look like two concentric circles, and the radius of the outer circle needs to be able to changed without changing the thickness of the double-wall. That means the radius of the inner circle would equal R.outer.circle - wall-thickness.

**Comment by ariutta** [comment]
There are two primary options to focus on for this project, either of which is acceptable for proposals.

## Option 1: Reuse Existing External Images
As mentioned by @maxkfranz, there is a wealth of existing openly-licensed material that pathway authors would like to reuse. A few examples:
* GeneMANIA project's [model organism icons](https://github.com/GeneMANIA/bio-icons)
* [Noun Project](https://thenounproject.com/)
* Google Image search: [mitochondria ext:svg site:commons.wikimedia.org](https://www.google.com/search?q=mitochondria+ext:svg+site:commons.wikimedia.org&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiG9piM1afLAhUHwGMKHb-6CvcQ_AUIBygB&biw=1440&bih=702)
* Metabolite icons as described for [this project](https://github.com/nrnb/GoogleSummerOfCode/issues/47)

This project could focus on making it easier for pathway authors to:
1. Find appropriate pre-existing icons
    a. Develop a search interface for a curated set of image sources
    b. Allow authors to tag and rate specific images to help other authors with findability
2. Add the icons to pathways
   a. Authors may want to resize the icons
   b. Icons must be compatible with both the JavaScript viewer/editor pvjs and the Java viewer/editor [PathVisio](http://www.pathvisio.org/)

The icons should be recognized as icons in pvjs if an author edits the pathway later, but in PathVisio, they may only need to be displayable, even if they are not recognized as icons. One means of doing this could be to make it possible to convert SVG to [GPML](http://www.pathvisio.org/gpml/), the data format used by PathVisio.

Nice to have: pathway authors may sometimes want to resize an icon while maintaining selected dimensions of sub-parts, e.g., an icon for a double-walled cell compartment might look like two concentric circles, and the radius of the outer circle needs to be able to changed without changing the thickness of the double-wall. That means the radius of the inner circle would equal radius of the outer wall minus the constant wall thickness.

Nice to have: some means of handling changes to the external images.

## Option 2: Create New Icons
As a pathway author is creating a pathway diagram, the author may want to create new icons like the cardiac myocyte mentioned above. It would be helpful to allow these authors to enter an "icon creation mode" using a tool like [SVG-Edit](https://code.google.com/p/svg-edit/) to give them more control and power for creating attractive icons.

In the "icon creation mode," a pathway author could reuse icons created by other pathway authors, possibly using a model similar to Github, where users can fork existing projects and make pull requests with suggested improvements.

Additionally, we could set up a dependency management system like NPM so that each icon would have a name and a version. Then one user could create an icon, and another user could add that icon to a specific pathway, which would mark that icon as a versioned dependency for that pathway. If the icon creator later publishes an improvement to the icon, it should be possible for the pathway creator (or any other authorized user) to optionally update the dependency to get the latest version of the icon to display in the pathway.

**Comment by ariutta** [comment]
Applicants, you may want to review the [other Pvjs ideas](https://github.com/nrnb/GoogleSummerOfCode/issues?q=is%3Aopen+is%3Aissue+label%3Apvjs). Do you see any overlap or a better separation of concerns in terms of implementing the desired functionality? If so, don't feel constrained to a rigid interpretation of this idea. Feel free to use composition (putting together parts of any of the ideas) when in drafting your proposal, as long as you keep the scope realistic for a summer project.
