### ISSUE TITLE
ELUDE: A cytoscape app for generating protein interaction networks from co-fractionation data.

### ISSUE THREAD

**Issue by fgoebels** [nrnb/GoogleSummerOfCode#53]
### Background
The co-fractionation technique combines extensive biochemical fractionation with quantitative mass spectrometry for mapping protein interactions in different organelles and tissues ([link](http://www.sciencedirect.com/science/article/pii/S0092867412010069)). These interactions are measured by separating proteins across multiple biochemical fractions to create a distinct elution profile for each protein. In the subsequent step, computational scoring is applied to identify protein pairs with similar elution profiles, which is highly associated with physical interaction. Test data is [here](http://www.cell.com/cms/attachment/2021768736/2041631102/mmc1.xlsx) available. It consist of an matrix where each column represents a biochemical fraction, and each row a protein.

### Goals
The goal of this project is the creation of a [Cytoscape app](http://wiki.cytoscape.org/Cytoscape_3/AppDeveloper/Cytoscape_App_Ladder) that automatically creates networks from co-fractionation data. The co-fractionation method is executed by many research groups around the world, and in order to help them processing their own data, we plan to help create a Cytoscape app, that:

*	Allows for quick and easy processing of the co-fractionation data
*	Has a intuitive graphical user interface for reading, and processing co-fractionation data 
*	Automatically build, visualize and layout the created interaction network
*	Allow the integration of additional annotation data such as functional associations

### Language Skills
Cytoscape, Java, Python

### Potential Mentors
Florian Goebels, Gary Bader

### Difficulty
2

### Contact
[Florian Goebels](mailto:florian.goebels@gmail.com)

**Comment by khanspers** [comment]
No longer available.
