### ISSUE TITLE
PiType: A protein interaction type prediction cytoscape app. 

### ISSUE THREAD

**Issue by fgoebels** [nrnb/GoogleSummerOfCode#54]
### Background

Protein interactions mediate a wide spectrum of functions in various cellular contexts. Functional versatility of protein complexes is due to a broad range of structural adaptations that determine their binding affinity, the number of interaction sites, and the lifetime. In terms of stability it has become customary to distinguish between obligate and non-obligate interactions dependent on whether or not the protomers can exist independently. In terms of spatio-temporal control protein interactions can be either simultaneously possible or mutually exclusive. PiType is a computational method for classifying protein interactions into simultaneously possible and mutually exclusive as well as into obligate and non-obligate ([link to publication](http://bmcsystbiol.biomedcentral.com/articles/10.1186/1752-0509-7-S6-S5)). The central advantage of PiType is that it's based on readily accessible features, such as sequence and functional properties of the two binding partners and their local network topology. Thus, PiType does not rely on atomic structures and is thus suitable for characterizing proteome-wide interaction data sets.
### Goals

The goal of this project is to create a ([Cytoscape app](http://wiki.cytoscape.org/Cytoscape_3/AppDeveloper/Cytoscape_App_Ladder)) for the PiType prediction tool ([PiType demo can be found here](http://webclu.bio.wzw.tum.de/PiType/help.php)). The app will allow researchers to  automatically classify their loaded protein network into their respective interaction type and display the classified interactions in a new network. In this project it is open to the applicant to integrate novel resources or features for calculating the protein interaction types. One suggest resource that can be integrated is the [STRING](http://string-db.org/) database.
### Language Skills

Python, Java, Cytoscape
### Difficulty level: 2

Ideally, the student would also be familiar with protein interaction concepts/terminology. Prior experience with Cytoscape is a plus.
### Potential Mentors:

Florian Goebels, and Gary Bader
### Contact

[Florian Goebels](mailto:florian.goebels@gmail.com)

**Comment by saksham1115** [comment]
Hello

I am Saksham Agrawal. I am currently pursuing my B.Tech. in Computer Science and M.S. in Computational Natural Sciences from International Institute of Information Technology, Hyderabad.

I am in my 3rd year. In the past years, I have done various kinds of projects in python (like making a potential energy simulator for a system that also calculates other energy dynamics)  PHP and Javascript as well ( I made a prototype last year that converted Computational Biological Models into Boolean Circuits)

I have background in Machine Language too. I implemented a paper that  required me to use different sentiment analysis techniques and compare their results.
I used python for this project.

I would like to work on this project. Could you please help me out.

**Comment by tafodinho** [comment]
i will love to work on this project

**Comment by khanspers** [comment]
@tafodinho Please contact the mentor directly (florian.goebels@gmail.com), as questions posted here may go unnoticed.

**Comment by souravsingh** [comment]
@fgoebels I am interested in working on the project.

**Comment by fgoebels** [comment]
Sure Sourav. If you are interested you can send me a draft of your project proposal and I can give you feedback.

**Comment by khanspers** [comment]
GSoC 2017 selected project
