### ISSUE TITLE
Enhance Cytoscape command-line scripting

### ISSUE THREAD

**Issue by scootermorris** [nrnb/GoogleSummerOfCode#56]
### Background
[Cytoscape 3](http://www.cytoscape.org/) includes the capability to read and execute command scripts, including commands exposed by Apps.  Users can also enter commands via a command line dialog that provides very rudimentary help and command input.

### Goal
There are two, features that have often been requested that we do not currently support.  First, it would be extremely useful to support some kind of variable substitution.  This could be as simple as "special" strings (e.g. %SELECTED_NODES% or something) or more elaborate for untyped variables.  Second, some simple loop constructs would really be useful.  Together these two features would allow users to create very useful extensions to Cytoscape without having to be able to program in Java or Python.

Once these two features are implemented, there are a number of useful changes to the [CommandLineDialog](http://wiki.cytoscape.org/Cytoscape_3/UserManual/Command_Tool) that would significantly improve it's usability as a tool to create and debug scripts.

### Difficulty level: 2
Prior experience with Cytoscape, network semantics, and scripting language specification is recommended.

### Technology and Skills
Java, Cytoscape

### Possible Mentors
Scooter Morris

### Contact
scooter@cgl.ucsf.edu

**Comment by gvaibhavraj2** [comment]
@scootermorris Hi! I am Vaibhav Raj Gupta, third year undergrad from IIT Roorkee,India. I am highly interested in this project.

**Comment by jooolia** [comment]
Hi,

I've been working with CyREST API using R (and sometimes Python). I know this is quite different from what is proposed here, but would there be any interest in developing a package during GSOC that would facilitate the use of this API in R?

**Comment by khanspers** [comment]
@jooolia and @gvaibhavraj2 : Please contact the mentor directly at scooter@cgl.ucsf.edu. Messages github may go unnoticed.

**Comment by jooolia** [comment]
Thanks @khanspers! Will do.

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
