### ISSUE TITLE
Visual biology with Escher

### ISSUE THREAD

**Issue by draeger** [nrnb/GoogleSummerOfCode#59]
### Background

The web-based graphical editor for biological networks [Escher](http://escher.github.io) ([King et al. 2015](http://dx.doi.org/10.1371/journal.pcbi.1004321)) enjoys growing popularity and is being used for modeling, documentation, and visualization of measurement data. As a typical web-based program, Escher uses a JSON-based data structure to represent its pathways. A separate application allows users to convert these [JSON](http://json.org) files to the community formats [SBML](http://sbml.org) and [SBGN-ML](http://www.sbgn.org). 

### Goal

The aim of this project is to develop a web-based import and export function for community standards ([SBML](http://sbml.org) and [SBGN-ML](http://www.sbgn.org)) that will replace the already existing [EscherConverter](https://escher.readthedocs.org/en/stable/escherconverter.html).

### Technologies

JavaScript, Java, JSON, SBML, SBGN-ML

### Potential mentors

Zachary A. King, Andreas Dräger

### Contact

[Zachary A. King](mailto:zaking@ucsd.edu), [Andreas Dräger](mailto:andreas.draeger@uni-tuebingen.de)

Useful pointers to documentation related to GSOC for student on the main NRNB web site :
* [Resources](http://nrnb.org/gsoc.html)
* [How to apply](http://nrnb.org/gsoc.html#apply-tab)

**Comment by devkhan** [comment]
I'm interested in taking up this project. I have experience in JS, Java, JSON, and a little bit in Escher. Can you guide me how to get started in knowing more about this project? I will try to learn more about SBML and SBGN.

**Comment by khanspers** [comment]
Hi Devesh, the mentors have referenced several resources above with additional information. Please review those and then contact the mentors directly via their emails above. They may not see messages here immediately.

**Comment by draeger** [comment]
Hi @khanspers, @devkhan, and @zakandrewking! Thanks, we had already direct e-mail contact. So please, just click on the e-mail links if there are any questions. Many thanks!

**Comment by devkhan** [comment]
@draeger I'm unable to find the source for **EscherConverter**. There's only a download link in the docs. Isn't the source available?

**Comment by draeger** [comment]
@devkhan I will provide you with the source code. For your application, however, you will not need to do programming yet.

**Comment by devkhan** [comment]
Thanks. I know, but I need to study the current implementation as it will help me better grasp the concepts.

**Comment by draeger** [comment]
Actually, the main idea is to create a bipartite matching between two different data formats. [EscherConverter](http://escher.readthedocs.org/en/stable/escherconverter.html) reads JSON, recursively goes through that data structure and while reading fills in corresponding entries in SBML or SBGN-ML.

An optimal implementation would use the [Builder Pattern](https://en.wikipedia.org/wiki/Builder_pattern) for this and have specific handler interfaces for objects. This separation allows us to create of diverse output data formats while reusing the reader function as a common framework.

Summarizing, what a file format converter needs to do is:
1. Read the input file format.
2. Recognize concepts, i.e., data structures.
3. Call build methods on a specific builder for output file formats and pass those structures to the builder.
4. Write the output file format.

The rest are details. I recommend reading about [design patterns](https://en.wikipedia.org/wiki/Software_design_pattern) (in particular the [builder pattern](https://en.wikipedia.org/wiki/Builder_pattern)) as well as introduction to [SBML](http://de.slideshare.net/thehuck/mhucka-sbmltutorialpart1icsb2014) and the [Layout Extension](http://bioinformatics.oxfordjournals.org/content/22/15/1879.full.pdf), [SBGN-ML](http://bioinformatics.oxfordjournals.org/content/28/15/2016.full.pdf) and [JSON](http://json.org), rather than going through Java™ source code (which I think is more difficult and less helpful).

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.

**Comment by devkhan** [comment]
Hosted here: https://github.com/SBRG/EscherConverter
