### ISSUE TITLE
Web based SBGN editor

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#60]
### Background
SBGNViz.js, or simply SBGNViz, is a software tool / library for viewing process description maps in [Systems Biology Graphical Notation](http://sbgn.org) (SBGN-PD) [1]. It is based on [Cytoscape.js](http://js.cytoscape.org). A sample application for the library is provided [here](http://www.cs.bilkent.edu.tr/~ivis/SBGNViz.js/).

### Goal
With this project, we aim to turn SBGNViz into a full-blown editor/curator tool for biologists to construct new models or modify existing ones in SBGN-PD notation. 

### Description
Currently SBGNViz allows one to load process description maps in SBGN-ML format and apply certain filtering operations but it doesn't allow you to modify the topology of the maps. This project aims adding new facilities for adding / removing biological entities and processes of varying types into / from a new map or an existing one. In addition, operations for resizing and annotating (with state variables and units of information) biological entities are to be provided. Furthermore, advanced complexity management techniques including expand/collapse of complexes and compartments and corresponding specialized layout operations are to be employed. Finally undo/redo support is needed to recover from mistaken operations.

### Potential Mentors
[Ugur Dogrusoz](mailto:ugurdogrusoz@gmail.com), Ozgun Babur

[1] M. Sari, I. Bahceci, U. Dogrusoz, S.O. Sumer, B.A. Aksoy, O. Babur, E. Demir, "SBGNViz: a tool for visualization and complexity management of SBGN process description maps", PLoS ONE, 10(6), e0128985, 2015.

**Comment by stefan2212** [comment]
Hello :) . My name is Stefan and i study Computer Science at University Alexandru Ioan Cuza from Iasi Romania. I am in the second year of study and i would like to participate at this project

**Comment by ugurdogrusoz** [comment]
Please take a look at this paper to learn about SBGNViz.js. This is what we'd like to turn into a full pledged editor. So far, we have done quite a bit of work. Latest can be found here: http://cs.bilkent.edu.tr/~ivis/SBGNViz.js_editor/sample-app/

This project aims to improve the editing capabilities of the tool further with things like specialized layout upon expand/collapse, creation of processes through templates provided to the users, etc.

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
