### ISSUE TITLE
Toolbox for systems biology model building and slicing

### ISSUE THREAD

**Issue by draeger** [nrnb/GoogleSummerOfCode#65]
### Background

Online databases such as [BiGG](http://bigg.ucsd.edu) or [BioModels](https://www.ebi.ac.uk/biomodels-main/) provide a large variety of published models in SBML format. When building new models, the content of these databases can be very helpful. In particular, it is often desired to take submodels from existing models as a scaffold for building models for related organisms or tissues. The Java™ library [JSBML](http://sbml.org/Software/JSBML) facilitates reading, manipulating, and writing of systems biology models in the XML-based [SBML](http://sbml.org) format. It provides an elaborate type hierarchy for dealing with all model components in memory.

### Goal

In this project, utility classes for model slicing (sub model extraction) and convenient model building in JSBML will be developed, extended and improved, and documented. These functions are particularly important because models will in the future become more and more modular. Submodel building is useful for hierarchical modeling. The model builder functions are helper functions because many [SBML](http://sbml.org) objects have several mandatory attributes. Calling all required set methods individually requires users to type long code fragments. The model builder significantly shortens the code and eases working with [JSBML](http://sbml.org/Software/JSBML). JUnit test cases will be developed to ensure the correctness of the developed procedures.

### Public Repository
https://github.com/sbmlteam/jsbml

### Potential mentors

[Andreas Dräger](mailto:draeger@informatik.uni-tuebingen.de)
[Nicolas Rodriguez](mailto:rodriguezn@babraham.ac.uk)

### Contact

[JSBML developers mailing list](mailto:jsbml-development@googlegroups.com), available online at https://groups.google.com/d/forum/jsbml-development.

Useful pointers to documentation related to GSOC for student on the main NRNB web site :
- [Resources](http://nrnb.org/gsoc.html)
- [How to apply](http://nrnb.org/gsoc.html#apply-tab)

**Comment by kapilkd13** [comment]
Hi I am Kapil, from National Institute of Technology, Delhi.I want to contribute to this project. I have worked with Java and XML on few projects. I looked at few models from  [BioModels](https://www.ebi.ac.uk/biomodels-main/). I want to know if there exist a documentation explaining these models as it would be easy to slice the model once I have a clear understanding of the it.
Regards,
Kapil Kumar

**Comment by hsauro** [comment]
Check the paper by:

https://www.ncbi.nlm.nih.gov/pubmed/24078714

A C library for retrieving specific reactions from the BioModels database.

Might give you a start.

**Comment by kapilkd13** [comment]
Thanks a lot. I would consult you if I found any difficulty.
Thanks

**Comment by Hemant27031999** [comment]
Hello, I'm Hemant, a Computer Science sophomore from the Indian Institute of Technology, Roorkee India. I have experience with java and XML, and I find this issue interesting. 
Is it open for GSoC 2020?
Thanks.

**Comment by draeger** [comment]
Thanks for your interest in this topic, @Hemant27031999! Right now, we are in the procedure of applying to Google. On February 20th we will get to know if we can offer this project through the Google-funded program. See the time line here: https://summerofcode.withgoogle.com. We would be happy to help you applying for this project once NRNB has been accepted as a mentoring organization for 2020.

**Comment by Hemant27031999** [comment]
Ok! Thanks for your quick reply.

**Comment by vaniisgh** [comment]
hey :)
I recently learnt about the NRNB Academy program and wish to work on this project though that, I have filled out the application form outlining my background and experience etc and indicating my interest for this project. 
I wanted to know if you would be open to letting me work on this project though the program) or otherwise as well :)

**Comment by khanspers** [comment]
Hi Vani, thank you for your interest in NRNB projects! I saw your NRNB Academy inquiry and will respond directly in email.
