### ISSUE TITLE
Interconversion between SBML layout and SBGN-ML

### ISSUE THREAD

**Issue by draeger** [nrnb/GoogleSummerOfCode#67]
### Background

Systems biological networks are often displayed in form of graphs. Examples include biochemical reaction networks, gene-regulatory relationships, or signaling networks. The [SBML](http://sbml.org) file format allows storing such graph layout information using the layout extension package. With the help of the rendering extension package, it is even possible to make those displays more expressive by defining colors, shapes, gradients, and similar graphical aspects. Another popular standard for storing layout information is [SBGN-ML](http://sbgn.github.io/sbgn/). While SBML allows users to combine mathematical models with graphical displays, [SBGN-ML](http://sbgn.github.io/sbgn/) has been developed to specifically store two-dimensional graphs only. Therefore, the information content can be quite different. Still, it would be desirable to interconvert between the two the the greatest possible extend.

### Goal

In this project, a converter between SBML with layout extension and SBGN-ML should be conceived and implemented in Java™ using the libraries [JSBML](http://sbml.org/Software/JSBML) and [libSBGN](https://github.com/sbgn/sbgn/wiki/LibSBGN).  [JUnit](http://junit.org/junit4/) test cases will be developed to ensure the correctness of the developed procedures.

### Potential mentors

[Andreas Dräger](mailto:draeger@informatik.uni-tuebingen.de)
[Nicolas Rodriguez](mailto:nicolas.rodriguez@babraham.ac.uk)

### Contact

[JSBML developers mailing list](mailto:jsbml-development@googlegroups.com), available online at https://groups.google.com/d/forum/jsbml-development.

Useful pointers to documentation related to GSoC for student on the main NRNB web site :
- [Resources](http://nrnb.org/gsoc.html)
- [How to apply](http://nrnb.org/gsoc.html#apply-tab)

**Comment by haleyyew** [comment]
Thank you for your email responses. I will look into this project and update you once I made some progress.

**Comment by khanspers** [comment]
GSoC 2017 selected project
