### ISSUE TITLE
SBML Distributions: incorporating descriptions of probability distributions

### ISSUE THREAD

**Issue by skeating** [nrnb/GoogleSummerOfCode#68]
### Background

SBML Level 3 is being developed in a modular fashion with a core specification with optional packages can be included to add functionality. One of these packages is the [Distributions package](http://sbml.org/Documents/Specifications/SBML_Level_3/Packages/distrib) which has the additional requirement of needing to encode information related to probablility distributions. We initially used UncertML and liaised with its developers to work towards a new version that could easily be referenced from SBML. Unfortunately, at this point, progress on UncertML has stalled, which has stalled progress on SBML Distributions as well. This a situation that this project hopes to address

### Goal

Given that UncertML 3 has not been officially agreed, we would at this point seek to adapt what *has* been done to create XML descriptions of the relevant probability distributions that can be used by the SBML 'distrib' package.  The first stage of the project would involve producing this standard format.

Once a standard format has been decided, code for [libSBML](http://sbml.org/Software/libSBML), the API for working with SBML content, could be generated using [Deviser](https://github.com/sbmlteam/deviser). Deviser, a tool to facilitate the development of SBML Level 3 packages, is still under development, so using Deviser may involve additional coding to produce the necessary C++ code for libSBML. The generated code would then need to be integrated into libSBML and tests created to ensure the functionality is as expected. Tests could be done in C++ or optionally the Deviser code could be adapted to create the C++ tests.

A highly successful student who completed the stages above could then move on to look at RNG schemas and JSBML implementation.

This project does not involve one unique area of coding, but would allow a participant a opportunity to  experience development within an established team with softwares at various stages of maturity.

### Potential mentors

[Lucian Smith](mailto:lucianoelsmitho@gmail.com)
[Sarah Keating](mailto:skeating@caltech.edu)

### Contact

[SBML Team mailing list](mailto:sbml-team@googlegroups.com), available online at https://groups.google.com/d/forum/sbml-team.

Useful pointers to documentation related to GSOC for student on the main NRNB web site :
- [Resources](http://nrnb.org/gsoc.html)
- [How to apply](http://nrnb.org/gsoc.html#apply-tab)

**Comment by souravsingh** [comment]
@skeating I am interested in working on the project.

**Comment by neerajkr** [comment]
Hello,

I have good prior experience with python and xml but i have not used SBML.
I am interested in this project. Can i apply for this?
I can learn SBML before starting the project.

**Comment by niko-rodrigue** [comment]
We will soon know if the NRNB organisation has been accepted for the GSOC 2017 program. In the meantime, to prepare for your potential GSOC application, you can of course to try to get familiar with SBML, uncertML, the current distrib proposal and any other concept/software mentioned in the proposal.

**Comment by matthiaskoenig** [comment]
Just to comment:

It would be great when SBML distributions are implemented that there will be a method to encode joint distributions of parameters. For the sampling of the parameter distributions the covariance (joint distribution) information is required. The reason is that I often have distributions of different parameters which are not-independent, i.e. it is not sufficient to write the single distributions for the individual parameters, but it is necessary to specify the joint distribution (often scaled from a data covariance matrix).

**Comment by luciansmith** [comment]
Not selected, and won't need next year.  Matthias, I'll contact you externally about multivariate distributions.
