### ISSUE TITLE
Improvements in tool for curating biological maps in SBGN

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#69]
### Background

[SBGNViz](https://github.com/iVis-at-Bilkent/sbgnviz.js) [1] is a [Cytoscape.js](http://js.cytoscape.org/) based viewer for biological maps in Systems Biology Graphical Notation (SBGN) notation [2].  [ChiSE](https://github.com/iVis-at-Bilkent/chise.js) is based on SBGNViz to add editing facilities for construction of SBGN maps or modification of existing ones.

### Goal

ChiSE already supports many features including:
- SBGN PD notation
- expand-collapse and hide-show for complexity management of large maps
- layout support
- undo/redo, grid and grid guidelines support

With this project, we aim to design and implement new features for the ChiSE editor.
 
### Description

Among the new features that are scheduled for the first public availability are:

- support for Activity Flow notation and multiple node/edge palletes
- user profiles
- port / connection point support
- user interface improvements
- miscellaneous other features

### Difficulty level: 2

This project requires good programming skills. Experience in web technologies (JavaScirpt , html, css) is required. Experience with Cytoscape.js and its extensions is a plus.

### Potential mentors

[Alexander Mazein](mailto:amazein@eisbm.org), [Ugur Dogrusoz](mailto:ugurdogrusoz@gmail.com)

[1] M. Sari, I. Bahceci, U. Dogrusoz, S.O. Sumer, B.A. Aksoy, O. Babur, E. Demir, "SBGNViz: a tool for visualization and complexity management of SBGN process description maps", PLoS ONE, 10(6), e0128985, 2015.
 
[2] N. Le Novère et al., "The Systems Biology Graphical Notation", Nature Biotechnology, 27, pp. 735-741, 2009.

**Comment by kinimesi** [comment]
Hi, I have submitted the draft of my proposal. Could you please review it and give feedback? Thanks.
@ugurdogrusoz @amazein

**Comment by khanspers** [comment]
GSoC 2017 selected project
