### ISSUE TITLE
Biological Pathway Styling Themes

### ISSUE THREAD

**Issue by ariutta** [nrnb/GoogleSummerOfCode#7]
### Background

Description: [Biological pathways](http://wikipathways.org/index.php/WikiPathways:About) provide intuitive diagrams of the interactions underlying biological processes. For example, the [SIDS Susceptibility Pathways](http://www.wikipathways.org/wpi/PathwayWidget.php?id=WP706&label[]=L-DOPA&label[]=Dopamine&label[]=DDC&colors=yellow) show interactions between metabolites, genes and proteins, such as DDC catalyzing the conversion of L-DOPA to Dopamine (look for the items highlighted in yellow on the lower right). The site [WikiPathways](http://www.wikipathways.org/) is an open, collaborative platform dedicated to drawing and sharing biological pathways. These diagrams are viewed in many different environments, such as laptop screens, presentation slides and printed science journals. At WikiPathways today, the default styling theme for these diagrams is best suited for viewing by an individual on a computer screen, but it would be useful to export the diagrams with themes optimized for print and for presentations.
### Goal

Develop a custom theming system to allow for exporting pathways with themes optimized for print and for projected presentation slides. For example, the presentation export option might make pathway diagrams easier to read by removing some text, enlarging the remaining text and inverting the colors of the diagram. Optionally, the presentation option could integrate with one or more existing online presentation framework(s).
### Difficulty Level: 3

Strong JavaScript skills, because this project will likely require some refactoring of the existing code for Pvjs. Some prior experience with pathway diagrams and/or presentation frameworks is preferred.
### Links
- [Pvjs: WikiPathways pathway viewer/editor](https://github.com/wikipathways/pvjs)
- Example online presentation frameworks:
  - http://github.com/hakimel/reveal.js
  - http://github.com/bartaz/impress.js
  - http://docs.google.com/presentation
### Technology and Skills
- WikiPathways
- User experience
- graphical design
- CSS
- some JavaScript
### Potential Mentors
- Anders Riutta
- Alex Pico
- Kristina Hanspers
### Contact

[Anders Riutta](mailto:anders.riutta@gladstone.ucsf.edu), [Alex Pico](mailto:alex.pico@gladstone.ucsf.edu), [Kristina Hanspers](mailto:kristina.hanspers@gladstone.ucsf.edu)

**Comment by jacobwindsor** [comment]
Hi @ariutta, would this be a PVJS only feature or a Kaavio one too? I know Kaavio already allows the custom style input but operations like removing text are not yet implemented as far as I'm aware. So would things like this be in PVJS or Kaavio? Actually, thinking about it, would those sort of operations require dynamically altering the GPML?

**Comment by ariutta** [comment]
Hi @jacobwindsor, good question! Both Kaavio and Pvjs might be responsible, just for different things. For example, the Kaavio API could expose themes and transformations that are not pathway specific, such as a color filter to make the diagram colorblind-friendly or a presentation theme to thicken lines, increase text size, invert colors and/or increase color contrast. Pvjs would be responsible for pathway-specific things. For example, if we removed any text, we'd have to be careful and know the context for when doing that is OK, which would probably be more appropriate in Pvjs.

Regarding GPML, we are already going from GPML to JSON, so any operations would be done on the JSON.

Related:
* https://www.technologyreview.com/s/601782/how-enchromas-glasses-correct-color-blindness/
* http://www.blopig.com/blog/2013/10/a-colourblind-guide-to-colourful-presentations/
* http://www.color-blindness.com/2007/01/23/confusion-lines-of-the-cie-1931-color-space/
* https://en.wikipedia.org/wiki/Lab_color_space

**Comment by ariutta** [comment]
Applicants, you may want to review the [other Pvjs ideas](https://github.com/nrnb/GoogleSummerOfCode/issues?q=is%3Aopen+is%3Aissue+label%3Apvjs). Do you see any overlap or a better separation of concerns in terms of implementing the desired functionality? If so, don't feel constrained to a rigid interpretation of this idea. Feel free to use composition (putting together parts of any of the ideas) when in drafting your proposal, as long as you keep the scope realistic for a summer project.
