### ISSUE TITLE
Develop a Synthetic Biology Publication Workflow that Leverages the Synthetic Biology Open Language

### ISSUE THREAD

**Issue by cjmyers** [nrnb/GoogleSummerOfCode#75]
### Background

The Synthetic Biology Open Language (SBOL) is an emerging standard for describing synthetic biology designs.  It includes a data standard for representing components such as DNA sequences and proteins, as well as the interactions between them organized as modules.  SBOL also includes a standard set of symbols for visualizing these designs. The ACS Synthetic Biology journal has recently announced that authors of papers for their journal should encode and visualize their synthetic biology designs using the SBOL standard.  

Various software tools supporting SBOL are now available.  These include data repositories such as the SynBioHub and ICE, sequence editing tools such as SBOLDesigner and Benchling, and circuit design tools such as Cello and iBioSim.  These tools enable complete tool chains supporting composition, modeling, data storage, and visualization.

### Goal

The goal of this project is to leverage software tools that support SBOL to construct an open source workflow for publication of synthetic biology designs.  This workflow will enable authors to construct their biological designs effectively, and share them in data repositories such as SynBioHub and ICE.  Data sharing should include both private access for paper reviewers, as well as public access after publication.  This workflow should target both publication for journals, as well as by students participating in the iGEM competitions.  Finally, this workflow should include visualizations of these designs that are of publication quality, and it should provide a means for both automated and semi-automated data curation.  

### Skills Required

Experience with Java, Javascript, and web application development. Familiarity with SBOL is a plus.

### Potential Mentors

[Chris Myers](mailto:myers@ece.utah.edul)
[Anil Wipat](mailto:anil.wipat@newcastle.ac.uk)
[James McLaughlin](mailto:j.a.mclaughlin@newcastle.ac.uk)

### Main Contact

[Chris Myers](mailto:myers@ece.utah.edul)

### References

N. Hillson, H. Plahar, J. Beal, and R. Prithviraj, “Improving Synthetic Biology: Recommended Practices for Visual Depiction and Digital Submission of Genetic Designs”,  ACS Synthetic Biology, vol. 5, no. 6, pp. 449-451, Jun. 2016. [doi: 10.1021/acssynbio.6b00146](http://pubs.acs.org/doi/abs/10.1021/acssynbio.6b00146)

N. Roehner, J. Beal, K. Clancy, B. Bartley, G. Misirli, R. Grunberg, E. Oberortner, M. Pocock, M. Bissell, C. Madsen, T. Nguyen, M. Zhang, Z. Zhang, Z. Zundel, D. Densmore, J. Gennari, A. Wipat, H. Sauro, and C. Myers. “Sharing structure and function in biological design with SBOL 2.0,” ACS Synthetic Biology, vol. 5, no. 6, pp. 498-506, Apr. 2016. [doi: 10.1021/acssynbio.5b00215](http://pubs.acs.org/doi/abs/10.1021/acssynbio.5b00215)

**Comment by 16zzundel5** [comment]
I'm planning on submitting a proposal for this!

**Comment by khanspers** [comment]
GSoC 2017 selected project
