### ISSUE TITLE
Improve handling of time series and similar in Cytoscape

### ISSUE THREAD

**Issue by martinmodrak** [nrnb/GoogleSummerOfCode#76]
## Background

Time series and multiple measurements are becoming a frequent form of biological data. These include time-course gene expression, differential gene expression, time-course protein concentrations, and many other as well as simulated time-course data. However, Cytoscape is not very well equipped to handle such data and plugins working with time-series data (e.g. [TiCoNe](http://apps.cytoscape.org/apps/ticone) and [CyNetworkBMA](http://apps.cytoscape.org/apps/cynetworkbma) use ad-hoc methods to store them. [CyDataSeries](https://github.com/martincerny/cy-dataseries/wiki), a plugin for a more general and systematic handling is currently in public beta and could be made much more useful if it included a broad range of tools to handle time series and/or multiple measurements.

## Goals

Improve the way time series and multiple measurements are handled in CyDataSeries. The following list of possible improvements is more of an outline on what is possible. The exact content of the project will be negotiated with the student and the student is encouraged to propose other improvements that align with their interest.

- Comprehensive and effective UI for basic manipulation with time series (e.g., merging, splitting, applying numerical transformations)
- Implementing (or integrating) several smoothing/interpolation/extrapolation algorithms
- Implementing (or integrating) several signal processing algorithms + design an effective UI
- Implementing (or integrating) several time series prediction algorithms + design an effective UI
- Integrating time series with [CyAnimator](http://apps.cytoscape.org/apps/cyanimator)
- Improve import and export capabilities (parse XLSX files, improve [SOFT](https://www.ncbi.nlm.nih.gov/geo/info/soft.html) format support, export SOFT files)

## Student requirements

Students should be familiar with the Java language and preferably with the Swing UI library, but no prior experience with Cytoscape is required. If the student wants to focus on implementing time-series algorithms, they should have basic knowledge of time-series analysis.

## Mentors

[Martin Černý](https://github.com/martincerny/), Institute of Microbiology of the Czech Academy of Sciences (martin.cerny@biomed.cas.cz).

**Comment by JyotsanaS** [comment]
Hi,
I am Jyotsana. I have knowledge of Java and Swings. Previously I have applied time series modelling for prediction of bunching of buses and have since developed interest in it. I would like to contribute to this project.

**Comment by martincerny** [comment]
Hi Jyotsana, the project is available and your skills seem to be a good fit. 

However, keep in mind that the GSoC 2017 selection process is still underway and mentor groups will be announced on 27 February 2017. Our group, NRNB, has been selected several years in the past, so the chances of being selected this year are very good. After selection, we would be happy to work with interested applicants such as yourself, to develop a student proposal. This is NRNB's GSoC page. It has the timeline of key dates: http://nrnb.org/gsoc.html 
Be sure to check the student guides under the "How to Apply" tab as well. 

Please  write back if you have any other questions.

**Comment by JyotsanaS** [comment]
Thank you Martin, I will keep track of GSoC dates and fervently hope NRNB is selected. 

Meanwhile, I will try getting more familiar with Cytoscape and CyDataSeries and expand my knowledge on time-series algorithms. Please tell me if I am heading in right direction.

**Comment by martincerny** [comment]
Yes, this seem like the right approach. I wish you best of luck.

**Comment by AKK-55** [comment]
Hello Sir,
I am Ashish K. Kaushal, I have knowledge of JAVA language and know the basic use SWING library.
I want to contribute in this project for GSOC 2017. This is my first time, so can you please help me on how should I proceed with my GSOC preprations ?

**Comment by martincerny** [comment]
@AKK-55 Please see my comment above - in particular, check out http://nrnb.org/gsoc.html and the "How to apply" tab there and be aware, that working on student proposals is contingent on the (likely) acceptance of NRNB as a mentor group at the end of February.

**Comment by sarthaksahu5** [comment]
Hi, I am Sarthak. I have knowledge of Java and Swing development. However, I don't have an idea about time series analysis. Should I apply ? I am a 2nd-year undergraduate student of Computer Science. 
My linkedin profile - https://www.linkedin.com/in/sarthak-sahu-94a07a119/

**Comment by martincerny** [comment]
@sarthaksahu5 Hi, experience in time series analysis is not required (although it is beneficial). What is required is ability and willingness to learn. There are two general ways this project can be handled:

- *Focus on infrastructure.* Connect CyDataseries with available open-source implementations of the comon algorithms, build plumbing to integrate CyDataseries with other parts of the Cytoscape ecosystem. Here, only basic knowledge of the math behind time series will be required (you need to be able to at least understand the questions one may ask about time series), but more emphasis is on student's skills in software engineering.

- *Focus on algorithms.* Make CyDataseries an interesting tool by providing implementations of algorithms that are not available in other Java-based packages. This will require reasonable understanding of the underlying math (especially linear algebra) and basic knowledge of pitfalls to be avoided when implementing a numerical solution in a computer. On the other hand, the software engineering requirements are somewhat lower.

Note that there is no clear cut between the two ways and a proposal may take a middle ground.

**Comment by ShaikAsifullah** [comment]
Hi, I have been using ApacheStorm for realtime analysis for quite long. More Specifically I have been working on different timeseries models ARIMA and other forecasting models on the timeseries data. And also I know Java (good) and Swing (have done some GUIs). Can I get some guidance on this ?

**Comment by martincerny** [comment]
@ShaikAsifullah I am not sure what kind of guidance are you asking for. I can however confirm that your skills would be a good fit for the project.

**Comment by khanspers** [comment]
Closing for GSoC 2018
