### ISSUE TITLE
Improve the ICE DNA sequence data model to be compatible with SBOL 2 data standard

### ISSUE THREAD

**Issue by hplahar** [nrnb/GoogleSummerOfCode#79]
### Background

The [Inventory of Composable Elements (ICE)](https://github.com/JBEI/ice) is an open source registry platform and biological data repository that is widely used by numerous academic institutions and research labs. It provides support for storing DNA sequence information in the FASTA, GenBank and [Synthetic Biology Open Language (SBOL)](http://sbolstandard.org/) formats and permits interconversion between these different formats. It achieves this by using an intermediate data model to store the sequence information. This data model is much better suited to storing DNA sequence information described in the GenBank format than the newer SBOL 2 format. As a result, to avoid potentially losing information when storing synthetic biology designs described in SBOL 2, ICE simply stores SBOL 2 design files that cannot be converted to GenBank as flat files.  

### Goal

The goal of this project is to convert the internal data model ICE uses for representing DNA sequence information. SBOL includes a data standard for representing DNA sequences and therefore the improvements to the ICE sequence data model should be compatible with the SBOL 2 standard.

### Skills Required

Experience with Java, familiarity with SBOL

### Mentors
[Hector Plahar](mailto:haplahar@lbl.gov)
[Chris Myers](mailto:myers@ece.utah.edu)

### References

Ham, T.S., Dmytriv, Z. Plahar, H., Chen, J., Hillson, N.J., and Keasling, J.D. (2012) Design, Implementation and Practice of JBEI-ICE: An Open Source Biological Part Registry Platform and Tools. Nucleic Acids Research. [DOI: 10.1093/nar/gks531] (http://nar.oxfordjournals.org/content/early/2012/06/18/nar.gks531)

J. Beal, R. Cox, R. Grunberg, J. McLaughlin, T. Nguyen, B. Bartley, M. Bissell, K. Choi, K. Clancy, C. Macklin, C. Madsen, G. Misirli, E. Oberortner, M. Pocock, N. Roehner, M. Samineni, M. Zhang, Z. Zhang, Z. Zundel, J. Gennari, C. Myers, H. Sauro, A. Wipat. “Synthetic Biology Open Language (SBOL) Version 2.1.0,” Journal of Integrative Bioinformatics, 13(3):291, 2016. [doi:10.2390/biecoll-jib-2016-291] (http://journal.imbio.de/article.php?aid=291)

**Comment by bhaveshsunny** [comment]
Hi, I am Bhavesh and I am interested in this project. I am WebDeveloper and also a student of Biology. I am familiar with java, python, HTML5, CSS3, jQuery and Django. I am not familiar with SBOL but I am willing to learn

**Comment by cjmyers** [comment]
Hi Bhavesh,

Thank you for your interest.  To learn more about the SBOL data standard, I recommend that you have a look here:

http://sbolstandard.org <http://sbolstandard.org/>

Please do not hesitate to ask if you have any questions.  As far as ICE, it is an open source project located here:

https://github.com/JBEI/ice <https://github.com/JBEI/ice>

You might also try it out here:

https://acs-registry.jbei.org/login <https://acs-registry.jbei.org/login>

Nathan, Hector: is there anywhere else you would like to point this student to learn more?

Cheers,

Chris

**Comment by cjmyers** [comment]
Hi Chris,

I would suggest that the Public JBEI Registry would be better to look at,
as it has more entries than does the ACS SynBio Regitry:
https://public-registry.jbei.org/

Some more information can also be found here:
http://ice.jbei.org/

The original ICE paper (albeit outdated at this point) is here:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3467034/

Nathan

**Comment by khanspers** [comment]
Closing for GSoC 2018
