### ISSUE TITLE
"Flattening" of hierarchical systems biology models in JSBML

### ISSUE THREAD

**Issue by niko-rodrigue** [nrnb/GoogleSummerOfCode#8]
### Background

[SBML](http://sbml.org) is one of the most widely used modeling formats in [systems biology](https://en.m.wikipedia.org/wiki/Systems_biology). With the release of [SBML Level 3](http://sbml.org/Documents/Specifications#SBML_Level_3), the syntax and semantics of plain SBML be extended by SBML _packages_. The [Hierarchical Model Composition](http://co.mbine.org/specifications/sbml.level-3.version-1.comp.version-1.release-3) ("comp" for short) package defines how models in [SBML](http://sbml.org) can be composed of multiple individual submodels. These submodels can be stored in the same file, or be distributed as separate files in a file system, or even referenced over a network using [resource identifiers](https://en.m.wikipedia.org/wiki/Uniform_Resource_Identifier). While this format adds a large number of benefits and freedom for the model creator, it also significantly increases the complexity of the SBML documents. In addition, most software tools today do not (yet) implement direct support for hierarchical models, although they can usually deal with models that have been "flattened" to an equivalent non-hierarchical version. The specification of the SBML comp package describes how such a flattening algorithm works.
### Goal

The aim of this project is to implement the flattening algorithm in [JSBML](http://sbml.org/Software/JSBML). This will allow JSBML to take a hierarchically-composed SBML file and generate an equivalent nonhierarchical version that does not use the comp package (meaning it uses only SBML Level 3 "core" constructs). This will enable a much larger number of software systems to work with SBML "comp" models.

A flattening algorithm has already been defined, and has also been implemented in the C++-based library [libSBML](http://sbml.org/Software/libSBML). The latter may help in developing an equivalent implementation in [JSBML](http://sbml.org/Software/JSBML).

An additional goal of this project is the implementation of basic validation rules for the SBML comp package.
### Potential mentors

[Nicolas Rodriguez](https://github.com/niko-rodrigue), [Lucian Smith](https://github.com/luciansmith), [Chris Myers](https://github.com/cjmyers), [Leandro Watanabe](https://github.com/leandrohw)

### Contact

[JSBML developers mailing list](mailto:jsbml-development@googlegroups.com), available online at https://groups.google.com/d/forum/jsbml-development.

Useful pointers to documentation related to GSOC for student on the main NRNB web site :
- [Resources](http://nrnb.org/gsoc.html)
- [How to apply](http://nrnb.org/gsoc.html#apply-tab)

**Comment by matthiaskoenig** [comment]
Hi all,
Was there anything implemented for this? 
Is somebody working on this ?

I would like to use this functionality
The best
Matthias

**Comment by niko-rodrigue** [comment]
We have a student working on it at the moment.
