### ISSUE TITLE
Enable browsing of SBOL Stack instances on ICE Web of Registries

### ISSUE THREAD

**Issue by hplahar** [nrnb/GoogleSummerOfCode#80]
### Background

Freely open-source examples of digital biological information repositories (and design tools that interface with them) include (but certainly are not limited to): ICE (e.g., https://public-registry.jbei.org), [SBOL Stack](http://sbolstack.org/), and [Genetic Constructor)(https://geneticconstructor.bionano.autodesk.com/). ICE has recently established a RESTful API that enables its Web of Registries functionality (including private-remote collaboration), even for repositories and design tools not natively running ICE. SBOL Stack also has a RESTful API, and Genetic Constructor can access DNA sequences from NCBI and the iGEM Registry. However, it is not currently possible to browse/search SBOL Stack instances via the ICE Web of Registries, and Genetic Constructor does not currently access the ICE Web of Registries or SBOL Stack instances. It would be great to further develop ICE and SBOL Stack (and likely their RESTful APIs), and Genetic Constructor (invoking these APIs), so that ICE and SBOL stack instances could communicate with each other on a united Web of Registries that Genetic Constructor could access. 

### Goal

1. Develop ICE and SBOL Stack (and their APIs) to enable a united Web of Registries
2. Develop Genetic Constructor to connect with this united ICE/SBOL Stock Web of Registries

### Skills Required
Experience with Java. 
Since ICE, SBOL Stack, and Genetic Constructor are existing software platforms, stick to their established architectures, languages, and frameworks, where possible.

### Mentors
[Hector Plahar](mailto:haplahar@lbl.gov)

### Resource 

- [ICE repo](https://github.com/JBEI/ice)
- [SBOL Stack repo](https://github.com/ICO2S/sbolstack)
- [Genetic Constructor repo](https://github.com/autodesk-bionano/genome-designer) 
- [ICE installation, user manual, RESTful API documentation](http://ice.jbei.org)

### References

Ham, T.S., Dmytriv, Z. Plahar, H., Chen, J., Hillson, N.J., and Keasling, J.D. (2012) Design, Implementation and Practice of JBEI-ICE: An Open Source Biological Part Registry Platform and Tools. Nucleic Acids Research. [DOI: 10.1093/nar/gks531] (http://nar.oxfordjournals.org/content/early/2012/06/18/nar.gks531)

**Comment by khanspers** [comment]
Closing for GSoC 2018
