### ISSUE TITLE
Develop a converter for SBML spatial models

### ISSUE THREAD

**Issue by funasoul** [nrnb/GoogleSummerOfCode#81]
# Introduction
Today [SBML](http://sbml.org) has several extension packages to extend its capability. One of its extension is called 
[Spatial Processes (spatial)](http://sbml.org/Documents/Specifications/SBML_Level_3/Packages/spatial) which supports for describing processes that involve a spatial component, and describing the geometries involved. In spatial package, there are several ways (analytic geometry, sampled field geometry, parametric geometry, CS geometry, mixed geometry) to describe the spatial geometries in a model.
Currently, most of the spatial simulator which supports SBML spatial package supports analytic geometry and sampled field geometry. While we just focus on developing a spatial simulator with FDM (Finite Difference Method) or FVM (Finite Volume Method) as a numerical integrator, supporting analytic geometry and sampled field geometry will be enough. But if we want to implement our spatial simulator with a more stable integrator such as FEM (Finite Element Method), then the model should be described with parametric geometry. Creating a spatial model with parametric geometry from scratch is quite tough, especially if we want to create a spatial model from microscope image.

This summer, we would like to mentor a student in developing a converter which will convert spatial SBML models with different spatial geometries.

# Goal
The project could be split down into following 3 tasks.
- Convert a spatial model with sampled field geometry to parametric geometry
- Convert a spatial model with analytic geometry to parametric geometry
- Convert a spatial model with analytic geometry to sampled field geometry

# Student requirements
Students should be familiar with the Java™ programming and handling XML documents with their favorite APIs. If the student are interested in creating a simple GUI application to visualize their converted spatial models, he/she should have some experience on creating a GUI application using Swing or JavaFX.

# Potential Mentors
- [Akira Funahashi](https://github.com/funasoul) Keio University, Japan
- [Kaito ii](https://github.com/kaitoii11) Keio University, Japan
- [Andreas Draeger](https://github.com/draeger) University of Tubingen, Germany

**Comment by rnavagamuwa** [comment]
Hi ,
 I am Randika Navagamuwa and I am a final year undergraduate of [Department of Computer Science and Engineering,](http://www.cse.mrt.ac.lk/) [University of Moratuwa, Srilanka](http://www.mrt.ac.lk/web/). Last year also I have participated and completed GSoC with Eclipse foundation [1].  This year I thought of applying for this project. Since there is plenty of time before applying as a student, I thought of getting familiar with the project. As the initial step what should I be doing.

[1] [https://summerofcode.withgoogle.com/archive/2016/projects/4930443140923392/](https://summerofcode.withgoogle.com/archive/2016/projects/4930443140923392/)

Thank you,

**Comment by kapilkd13** [comment]
Hi I am Kapil from National Institute of Technology, Delhi. I would like to be a part of this project. I have prior experience with Java and XML. Can you point us towards the resources that we should go through in order to have better understanding of this project.
Regards,
Kapil Kumar

**Comment by funasoul** [comment]
Hi,

Thank you both for your interest.
At first, I recommend you to look through the documentation on [SBML spatial process](http://sbml.org/Documents/Specifications/SBML_Level_3/Packages/spatial) and API for parsing SBML spatial process on [JSBML](https://github.com/sbmlteam/jsbml).
(Andreas, could you point out the exact Javadoc on SBML spatial process?)

Also, you may find a good example of converting sampled field geometry to parametric geometry in [other application](https://imagej.net/3D_Viewer). Although it does not support SBML at all, but you can see how sampled field geometry is converted to parametric geometry.

Hope this helps.

**Comment by rnavagamuwa** [comment]
Hi @funasoul ,
 Thank you for the the links. Will go through these and get back to you.

Best regards,

**Comment by khanspers** [comment]
GSoC 2017 selected project

**Comment by AlexanderPico** [comment]
GSoC 2017 project canceled... project open again.

**Comment by funasoul** [comment]
migrated to #98
