### ISSUE TITLE
Develop a web service which provides simulation / steady state analysis / parameter estimation with SBML models

### ISSUE THREAD

**Issue by funasoul** [nrnb/GoogleSummerOfCode#82]
# Background
Currently, there are over 280 software packages which support [SBML](http://sbml.org). While there are enormous numbers of software packages to support mathematical modeling, simulation and analysis tools for research related to systems biology, it is still quite hard for a software tool to solve all required tasks on a single application so that users have to install several different software packages and configure them to work on their platform.
This process is not a hard task for computer scientists, but sometimes it is a big hurdle for biologists, who are not familiar with tweaking computers and operating systems. Systems biology operates at the interface of mathematics, computer science, and biology, so that developing a software tool which has a user-friendly UI, is easy to install and easy to manipulate is still an important task in this field.

This summer, we would like to mentor a student in developing a web service with Graphical User Interface (GUI) which provides ODE (Ordinary Differential Equation) simulation, steady state analysis, and parameter estimation which are commonly used in this field. To make an install procedure as easy as possible, we decided to provide this service as a web service so that users do not have to install any software tool on their computers.

# Goal
The project could be split down into following 4 tasks.
- Develop a server side application which will accept SBML as a mode and execute simulation / steady state analysis / parameter estimation.
- Develop a reporter which will generate results for above tasks.
- Develop a JavaScript-based GUI for sending tasks to the server, and receiving the results.
- Create a [Docker](https://www.docker.com) image which contains this web service.

Following simulator / analysis tools will be used to run simulations etc.
- [COPASI](http://copasi.org)
- [Simulation Core Library](http://simulation-core.sourceforge.net)
- [LibSBMLSim](https://github.com/libsbmlsim/libsbmlsim)
- [LibRoadrunner](http://libroadrunner.org)

# Student requirements
Students should be familiar with the Java™ and JavaScript programming. Better to have an experience in numerical calculation, but not required.

# Potential Mentors
- [Akira Funahashi](https://github.com/funasoul) Keio University, Japan
- [Kaito ii](https://github.com/kaitoii11) Keio University, Japan
- [Andreas Dräger](https://github.com/draeger) University of Tübingen, Germany

**Comment by PratyushTalreja** [comment]
Hi

I am pursuing Masters from Indian Institute of Technology Bombay. I had completed Bachelors in Information Technology. I am having a work experience of 1 year working with Cognizant Technology Solutions in Java domain. I am having hands on experience working with JavaScript during my work experience and previous year Google Summer of Code project. Also, I am having experience working with Web Services because of my course projects.

I am very much interested in working for this project. Can you guide me with the further steps.

Thank you.

**Comment by funasoul** [comment]
Hi,

Thank you for your interest in our project.
At first, if you have not yet tried [Docker](https://www.docker.com), then please have a try and launch a web server (nginx, apache httpd, etc) on a virtual machine. It will make you easy to try and test your web service.
Next step is to look into APIs. If you are familiar with Java, then I prefer you to look into [Simulation Core Library](http://simulation-core.sourceforge.net/) which is a pure Java library for simulating SBML models.
Also, understanding SBML (not completely, but the concept of SBML and its example models) will be a help. For example, the specification of [SBML Level 3 Version 1 Core](http://sbml.org/Documents/Specifications#SBML_Level_3_Version_1_Core) will be a good starting point.

Hope this helps.

**Comment by PratyushTalreja** [comment]
Thank you @funasoul for the detailed information. I have started working on the tasks and will keep you posted in case of any difficulty with any task.

**Comment by draeger** [comment]
Dear @PratyushTalreja, if needed contact me via e-mail and I will provide you with a few examples for excellent student proposals from earlier years that you can use to shape your proposal.

**Comment by PratyushTalreja** [comment]
Thanks @draeger . I have sent you a mail.

**Comment by TakahiroYamada** [comment]
Hi,
I am Doctor student from next year from Keio University, Japan. I mainly researched biological phenomenon using the methodology of systems biology in Bachelor and Master course. I have experience of ODE simulation and steady state analysis using COPASI with my coworker and I understood detail algorithm of these method. I have knowledge of Java language and have experience of implementing Runge-Kutta simulator. 
I'm very interested in this project. I'm not familiar with JavaScript now but I'm willing to learn and apply for this project.

Thank you.

**Comment by draeger** [comment]
@TakahiroYamada: do you have an e-mail address to contact you? You can also directly contact the mentors listed above via e-mail and we will assist you putting your proposal together.

**Comment by TakahiroYamada** [comment]
Thanks @draeger. I have an e-mail address. I will send you my proposal via e-mail after writing.

**Comment by draeger** [comment]
@TakahiroYamada: sounds good, thanks.

**Comment by niko-rodrigue** [comment]
Might be nice to have a look as well, time permitting, at tools like https://pdp10.github.io/sbpipe/ who already do a lot works for complex parameter estimation tasks.

**Comment by niko-rodrigue** [comment]
Also something that modelers struggle a lot to do in standard tools is bifurcation analysis.

**Comment by khanspers** [comment]
GSoC 2017 selected project
