### ISSUE TITLE
Time series data visualization in Escher

### ISSUE THREAD

**Issue by zakandrewking** [nrnb/GoogleSummerOfCode#86]
## Introduction

[Escher](http://escher.github.io) is a web-based tool for metabolic pathway visualization. Escher currently accepts data related to metabolites (e.g. metabolomics), reactions (e.g. calculated fluxes), and genes (e.g. transcriptomics). Users can use color, size, and text to represent these data types in the visualization [1]. However, Escher only accepts single datasets or pairs of datasets and cannot visualize time-series data.

## Goals

Extend the web-based pathway visualization tool Escher to accept time-course data for metabolomics, transciptomics, and flux visualization.  Create animations of the time course (with or without interpolation) using d3.js, and create a slider for users to switch between sets. These features should also be accessible through the Python/Jupyter interface to Escher. 

A previous student started on the project, but the changing structure of Escher means we might want to start from scratch.  

This project will require creativity in addressing user interaction and data representation. We will also need to consider standards for data storage.

## Skills Required

Language: JavaScript, JSON
Tools: [Bootstrap](http://getbootstrap.com), [Node.js](https://nodejs.org/en/), [D3.js](https://d3js.org)

## Difficulty level 2

The biggest challenge for this project will be getting up to speed on the Escher codebase and the way it handles data. This should be tractable for somehow who is already familiar with JavaScript, web technologies, and concepts like JSON and DOM.

## Possible Mentors

[Zachary King](mailto:zaking@ucsd.edu)
[Andreas Dräger](mailto:draeger@informatik.uni-tuebingen.de)

## Main contact

[Zachary King](mailto:zaking@ucsd.edu)

## References

[1] King ZA, Dräger A, Ebrahim A, Sonnenschein N, Lewis NE, Palsson BO. Escher: A Web Application for Building, Sharing, and Embedding Data-Rich Visualizations of Biological Pathways. PLoS Comput Biol. 2015;11: e1004321. doi:[10.1371/journal.pcbi.1004321](https://doi.org/10.1371/journal.pcbi.1004321)

**Comment by MitPandya** [comment]
Hi, I am interested in this project as my skillset and experience matches the requirements. Can you please tell me what is the right way to apply a proposal for this project!

**Comment by zakandrewking** [comment]
Hello!

Please read the "For Students" and "How to apply" sections here: http://nrnb.org/gsoc.html

If you have any questions after that, you can send me an email.

**Comment by AnamikaD** [comment]
@zakandrewking  is this project available for GSoC?

**Comment by draeger** [comment]
Yes, it is.

**Comment by AnamikaD** [comment]
@draeger Thank you for the reply! Can you explain me what does time-series data mean? I have experience in javascript, c3.js (learner). What are the expectation from the project? Is there a link to the project?

**Comment by draeger** [comment]
Time series means that you have data organized in a kind of a table, where the first column denotes the time (e.g., seconds, hours etc.) and all following columns would denote either reaction velocity values (e.g., moles per hour) or metabolite concentrations (e.g., moles). You could then map those data to a biochemical network and visualize how concentrations and reaction velocities change with time.

**Comment by zakandrewking** [comment]
Hi @AnamikaD. No issues right now. We certainly look forward to reading a draft of your proposal!

**Comment by draeger** [comment]
@AnamikaD please send me an e-mail and I'll provide you with a link to successful examples of applications for previous GSoCs. I didn't see your Gitter call, sorry for that. Please create and share a Google Doc that's really easiest to move forward. BTW, click on my icon and you'll see my e-mail address in my profile.

**Comment by draeger** [comment]
@AnamikaD please send me an e-mail and I'll provide you with a link to successful examples of applications for previous GSoCs. I didn't see your Gitter call, sorry for that. Please create and share a Google Doc that's really easiest to move forward. BTW, click on my icon and you'll see my e-mail address in my profile.

**Comment by AnamikaD** [comment]
@draeger Thank you for the reply. I will do that.

**Comment by Tivcrmn** [comment]
Hello, @zakandrewking , I am a senior student in BUPT from China and also I am a frontend developer. I have done a lot of full-stack project using Vue, Express and MongoDB. And also I have some experience with some data visualization tools such as chart.js and g2. I am so interested in the project and look forward to participate in it. Please give me some suggestions about how to get started with it.Or should I get familiar with the tools used in the project and try to do some demos by myself? Looking forward to your reply!!!
Thank you!!!!!

**Comment by zakandrewking** [comment]
Hi @Tivcrmn. This issue is actually from last year's GSoC, and we already found a student to work on it. So I'm closing this now.

Please take a look at some of the other exciting projects in the NRNB GSoC repo!
