### ISSUE TITLE
SBOL integration for IBW

### ISSUE THREAD

**Issue by harfel** [nrnb/GoogleSummerOfCode#87]
**Context:** Computer-Aided Design (CAD) Tools serve important tasks in the design process of
synthetic biological devices and systems. The Infobiotics Workbench (IBW) is a CAD software suite
developed at Newcastle University. IBW supports the synthetic biologist in a) the specification of novel
synthetic devices, b) the analysis of their behavior through simulation, c) the rigorous verification of
desired functionalities under all conceivable conditions, as well as d) the eventual generation of DNA
sequences that would realize the pursued design in vitro and in vivo. IBW is a Java application based on the Eclipse Modelling Framework.

**Goal of the project:** This MSc project will enhance the Infobiotics Workbench by interfacing it with
the Synthetic Biology Open Language (SBOL), a standard exchange format for synthetic biological
devices. This will enable synthetic biologists who have design specifications in SBOL to benefit from
the tools provided by IBW, and will enable users of IBW to benefit from the SBOL software universe.
The project aims are in detail:
1. To enhance the existing IBW biocompilation plugin with the ability to read and write SBOL genetic sequence definitions.
3. To provide an IBW plugin that transforms an SBOL design into an equivalent IBW design and vice versa.
5. To demonstrate full SBOL support with examples from the SBOL stack repository.

**Skills required:** Java, Eclipse, SBOL

**Potential mentors:** Harold Fellermann ([harold.fellermann@ncl.ac.uk](mailto:harold.fellermann@ncl.ac.uk)), Natalio Krasnogor ([natalio.krasnogor@ncl.ac.uk](natalio.krasnogor@ncl.ac.uk))

**References**
1. J. Blake, J. Twycross, F. Romero-Campero, N. Krasnogor. “The Infobiotics Workbench: an integrated in silico modelling platform for Systems and Synthetic Biology” (2011) Bioinformatics 27(23):3323-3324.
2. N. Roehner et al. “Sharing structure and function in biological design with SBOL 2.0” (2016) ACS Synthetic Biology 5(6):498-506

**Comment by khanspers** [comment]
Closing for GSoC 2018.
