### ISSUE TITLE
Develop a Web Application for the EnrichmentMap Workflow

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#89]
### Background
Enrichment analyses allow biologists to analyze their results by understanding whether a group of genes involved in a process (e.g. metabolism) are strongly represented in their results. Often many hundreds of these processes are tested. These proceses can be related (e.g. cell cycle upregulation, cell cycle downregulation), and it can be helpful to group/cluster these processes. The Bader Lab has recently produced a workflow for running this type of enrichment analysis, called [EnrichmentMap](http://www.baderlab.org/Software/EnrichmentMap).

The complete workflow involves multiple steps that are carried out by different tools:

* Gene Set Enrichment Analysis (R scripts)
* Visualize with clustered results EnrichmentMap (Cytoscape)

Below is an example output:

![EnrichmentMap](https://github.com/jooolia/gsoc_Rcy3_vignettes/raw/master/EM_ex_6.png)

A tutorial for R was written as part of a previous GSOC project:

https://github.com/jooolia/gsoc_Rcy3_vignettes/blob/master/recreating_enrichment_map_vignette_part2.Rmd

The tutorial makes use of the [cyREST REST API](https://github.com/cytoscape/cyREST) to interact with the desktop Cytoscape.

### Goal
The goal of this project is to produce a prototype web application that allows biologist to use a website to run the workflow described above without the need to directly use Cytoscape Desktop or R. After a user inputs their data, the application should make a call to R using an API; for this the R components need to be wrapped into an API using [OpenCPU R package](https://cran.r-project.org/web/packages/opencpu/index.html). The parts of the workflow that are run in Cytoscape desktop will continue to be run in Cytoscape, but with Cytoscape running within Docker containers. Lastly, rather than returning a static image, the goal of the project would be to show the results in an interactive visualization with [cytoscape.js](http://js.cytoscape.org/).

### Description
1. Get the workflow working locally.
2. Get the workflow working using Cytoscape in Docker
3. Make a REST API for the R components using OpenCPU
4. Make web application
5. Export results from Cytoscape Desktop as a cytoscape.js JSON file and visualize within the application

### Skills
Javascript (React preferable), REST APIs, R (would be helpful)

### Difficulty level 2
This project makes use of a pre-existing

### Public Repository
[EnrichmentMapApp](https://github.com/BaderLab/EnrichmentMapApp)

### Potential mentors
Augustin Luna (aluna@jimmy.harvard.edu)

### References
* [EnrichmentMap](http://www.baderlab.org/Software/EnrichmentMap)
* [OpenCPU](https://www.opencpu.org/)
* Docker Containers 
  * [Cytoscape Embedded in Docker](https://hub.docker.com/r/cannin/cytoscape-desktop/)
  * [OpenCPU Docker Container](https://github.com/cannin/docker-opencpu)
* [VNC Viewer to View Cytoscape within Docker](https://www.realvnc.com/download/viewer/)
* [EnrichmentMap Workflow](https://github.com/jooolia/gsoc_Rcy3_vignettes/blob/master/recreating_enrichment_map_vignette_part2.Rmd)
* [cytoscape.js](http://js.cytoscape.org/)
  * [cytoscape.js Format](http://js.cytoscape.org/#notation/elements-json)
* [Cytoscape](http://www.cytoscape.org/)
* [cyREST](https://github.com/cytoscape/cyREST)

**Comment by bhaveshsunny** [comment]
Hi ,
I am a WebDeveloper and I am interested in this project. Could you guys just point me in the right direction?

**Comment by shubhamkmr47** [comment]
Hi
I am Shubham Kumar pursuing my Btech in Computer Science and MS by Research in Computational Natural Sciences at International Institute of Information Technology, Hyderabad, India. I have hands on experience in the technologies like Javascript, OpenCPU(R), cytoscape, REST api. 
I am very much interested in this project.

I'm my previous year(2016) GSOC project I have developed a web-based application to perform various statistical computations in an interactive and graphical manner. The tool utilises R based server to enable interactive statistical analyses such as descriptive statistics, graphing, clustering, classification etc. Here's link to my gsoc project: https://github.com/HelikarLab/StatisticalPlatform

I could share my resume so that you could know more about my work experiences. I believe that I have adequate technological and conceptual knowledge which is required for the project.
I would like to start actively contributing and so I would be grateful if I could get a few pointers regarding how to get started with the code-base and the reference documents. I would be thankful if someone could guide me towards a moderate/beginner level bug in this regard so that I could first have some idea about how things work and get started.

Thank you

**Comment by cannin** [comment]
Thank you for your interest. I have built a very rough prototype of the application that I envision for the project. 

# Demo
The app currently is hosted here:

http://sanderlab.org/shinydebug/

Though it, soon, might be moved to:  

http://sanderlab.org/emdemo/

You'll quickly notice some components are not functional. Below is a screenshot of the demo was supposed to look like. 

<img width="1392" alt="screen shot 2017-02-23 at 11 59 22 am" src="https://cloud.githubusercontent.com/assets/790284/23565248/cac418a0-001a-11e7-947c-f68720f8532b.png">

# Code
The prototype code is here:

https://github.com/cannin/enrichmentmap-demo

The prototype was developed using the [Shiny, R web framework](https://shiny.rstudio.com/). This was done out of convenience. The goal of the project is to use the technologies outlined on this template project:

https://github.com/maxkfranz/slush-js

Plus [cytoscape.js](https://github.com/cytoscape/cytoscape.js) for the network views and the R-based analysis code needs to be wrapped in an [OpenCPU API](https://www.opencpu.org/api.html). Lastly, the entire application needs to be wrapped in a [Docker container](https://www.docker.com/). NOTE: You might need Redux (or easier, [MobX](https://github.com/mobxjs/mobx)) to handle state. 

# Next Steps
As far as what could be done as starting points: 

* Work to prototype the interface in [React](https://facebook.github.io/react/). Make sure you use [Bootstrap](https://react-bootstrap.github.io/) with a [Flatly theme](https://bootswatch.com/flatly/). NOTE: The Bootstrap link is to the first library I found not necessarily the one that should be used. 
* Work to prototype the backend API. [This Dockerfile](https://github.com/cannin/docker-opencpu)/[container](https://hub.docker.com/r/cannin/opencpu/) would be the best starting point because the base container has a lot of the dependencies (but not all) that you would need. 
 * The R code being used is on the "Run in R" tab of the demo app.

**Comment by shubhamkmr47** [comment]
Hi cannin
I have been trying to build the project. I have cloned the enrichmentmap-demo repository. But I am facing trouble running it. I am getting some error. Could you help me with that

> Error response from daemon: no such id: emdemo
> FATA[0000] Error: failed to remove one or more containers

**Comment by cannin** [comment]
@shubhamkmr47 I updated the README on the repo to help, but make sure you understand the Docker commands by reading other documentation/tutorials

**Comment by bhaveshsunny** [comment]
I have the shiny server up and running. Just started reading the shiny docs. What do I do next.
Here's a screen shot
![screenshot from 2017-03-05 16-12-23](https://cloud.githubusercontent.com/assets/16358797/23586640/39e148f2-01bf-11e7-8a7a-6e5883d9b9c5.png)

**Comment by shubhamkmr47** [comment]
I have started the application. Some of the features weren't working like you mentioned in the description. I am trying to fix them just to get started with the flow.

**Comment by bhaveshsunny** [comment]
@shubhamkmr47 Thanks.

**Comment by cannin** [comment]
Do not spend to much time debugging/fixing my prototype; Shiny should not be used for GSOC. It is better to showcase a familiarity with frontend development (slush-js) and its connection to OpenCPU even if for demonstration the sent from OpenCPU is hard-coded (mocked up).

**Comment by shubhamkmr47** [comment]
@cannin I have made demo application using that uses OpenCPU. It takes input a csv file and the data could be parsed to make plots. For know I have manipulated data to make scatter plot, bar plots, line plot. For now, to visualise them I used D3.js. Also, I made a dendogram for trial purpose.
I have attached the image of scatter plot.

Could you guide me further with my approach?

Also, I have exams this week so I wouldn't be able to spend much time on it.

![opencpu](https://cloud.githubusercontent.com/assets/11322721/23815484/7cf8655a-060e-11e7-9755-2a4a6f179c58.png)

**Comment by shubhamkmr47** [comment]
Hi @cannin 
I wish to share my draft proposal with you. It would contain my approach to the problem.
Where can I share it?
Thanks.

**Comment by cannin** [comment]
A link by email to a Google Doc

**Comment by kash1102** [comment]
Hello, I am Kashish Punjani 4th year B.tech Science and MS by Research in Computational Natural Sciences. I wanted to share my approach for this project. All the inputs would be appreciated.
Thanks
[https://docs.google.com/document/d/181EkWUaN-Za_y3O1myu9RYSnS5wjkWNQgQqzhyVOUtM/edit?usp=sharing](url)
