### ISSUE TITLE
Visualizing genomic alterations in cancer pathways in cBioPortal

### ISSUE THREAD

**Issue by ugurdogrusoz** [nrnb/GoogleSummerOfCode#9]
### Background
The [cBioPortal for Cancer Genomics](http://cbioportal.org/) provides intuitive visualization and analysis of complex cancer genomics data. The portal is accessed by over 1,500 researchers each day with many local instances of the software hosting private data sets all around the world. 

### Goal
The goal of this project is to improve the network visualization facilities provided by the portal. 

### Description
Current portal provides facilities for mapping genomic alteration data over a network of interest, driven from a gene set of interest, along with advanced filtering operations on the topology of this network. With this project, we will add a new network view for visualization of a set of curated pathways in [TCGA](http://cancergenome.nih.gov/) playing a critical role in cancer research. The new viewing facility will allow overlay of private alteration data on the network along with similar filtering mechanisms. Both the current network view and the newly planned one are based on [Cytoscape.js](http://js.cytoscape.org).

### Potential Mentors
[Ugur Dogrusoz](mailto:ugurdogrusoz@gmail.com), [JJ Gao](mailto:jianjiong.gao@gmail.com)

### Contact
[Ugur Dogrusoz](mailto:ugurdogrusoz@gmail.com), [JJ Gao](mailto:jianjiong.gao@gmail.com)

**Comment by pieterlukasse** [comment]
I'm interested in reviewing and testing :+1:

**Comment by khanspers** [comment]
Chosen as GSoC 2016 project.
