### ISSUE TITLE
Implement a python library for GraphSpace RESTful APIs

### ISSUE THREAD

**Issue by adbharadwaj** [nrnb/GoogleSummerOfCode#90]
## Background
GraphSpace is an easy-to-use web-based platform collaborating research groups can use for storing, interacting with, and sharing networks. A GraphSpace user can upload graphs through a REST API, import graphs created in [Cytoscape](http://www.cytoscape.org/), interact with graphs (view them, customize layouts, and save layouts), share graphs (create groups and add collaborators, share graphs among all members of a group or with the world), search graphs, and organize graphs using tags. GraphSpace has a comprehensive REST API that allows users to communicate programmatically with it.

## Goal

The overall goal of this project is to create a well-designed and extensible Python library for the GraphSpace REST APIs so that programmers can easily integrate GraphSpace into their Python-based applications. The library should simplify the process of authentication, constructing requests, and parsing responses from GraphSpace. Clear and complete documentation is an important component of the project. This project will also involve creating documentation for the REST APIs themselves.

## Technologies / Skills

This project will require knowledge of the following technologies:

- Python (essential)
- Django Framework (essential)
- RAML (nice to have)

## Potential mentors

[Aditya Bharadwaj](http://adityabharadwaj.in/)
[T. M. Murali](http://bioinformatics.cs.vt.edu/~murali/)

## Contact

[adb@vt.edu](adb@vt.edu)
[murali@cs.vt.edu](murali@cs.vt.edu)

**Comment by khanspers** [comment]
GSoC 2017 selected project
