### ISSUE TITLE
Template for new project ideas

### ISSUE THREAD

**Issue by khanspers** [nrnb/GoogleSummerOfCode#95]
**UPDATES FOR 2022: Size and length of project must now be defined and has been added to the template.**

### Background
Describe the current state of the project and the main problem or issue being addressed by the proposed idea. Details should include links and references. 

### Goal
Describe what the end result of the GSoC project should be.

### Difficulty Level X
Give a difficulty level (to replace X) from 1-3, with 1 easiest and 3 hardest. Make sure to tag the issue with this difficulty.
Describe with a sentence or two why the project is this difficulty level.

#### Size
Define the project as either: 

- **medium: 175 hours**
- **large: 350 hours**

#### Length
Specify if the project timeline is **flexible**, and define the project as either **12 weeks or 22 weeks**.

### Skills
List skills/technologies that the student should be familiar with. Also tag the issue with these.

Essential skills: Java, Cytoscape
Nice to have skills: GPU programming 

### Public Repository
Please link to a public, open-source repository for your project. _All code from accepted projects must be open source and public throughout the coding period and beyond._ 

### Potential Mentors
List the names and email contacts for potential mentors.

**Comment by AlexanderPico** [comment]
templates go here: https://github.com/nrnb/GoogleSummerOfCode/blob/master/.github/ISSUE_TEMPLATE/gsoc-project-idea.md

**Comment by AlexanderPico** [comment]
Just need one template: https://github.com/nrnb/GoogleSummerOfCode/blob/master/.github/ISSUE_TEMPLATE/gsoc-project-idea.md
