### ISSUE TITLE
Develop spatial simulation packages for systems biology

### ISSUE THREAD

**Issue by funasoul** [nrnb/GoogleSummerOfCode#98]
### Background
[SBML(Systems Biology Markup Language)](http://sbml.org) has several extension packages to extend its capability. One of its extension is called [Spatial Processes (spatial)](http://sbml.org/Documents/Specifications/SBML_Level_3/Packages/spatial) which supports for describing processes that involve a spatial component, and describing the geometries involved. SBML spatial extension enables users to build a spatial model and run a spatial simulation.

![example of spatial simulation](https://github.com/funasoul/docker-spatialsim/raw/master/images/sam2d_s1_cyt.gif "example of spatial simulation")

We have been working on a development of 2 software tools,

- [XitoSBML](https://github.com/spatialsimulator/XitoSBML): a spatial model builder which will generate spatial SBML model from microscopic images and
- [Spatial_Simulator](https://github.com/spatialsimulator/Spatial_Simulator): a spatial simulator which accepts spatial SBML as its input model format.

Although these two software tools perfectly works, it still have some space to extend / improve its feature.

- The specification of SBML spatial extension has been updated since our release. We have implemented our software tools to support [SBML spatial specification rel 0.91](https://sourceforge.net/p/sbml/code/HEAD/tree/trunk/specifications/sbml-level-3/version-1/spatial/specification/spatial-v1-sbml-l3v1-rel0.91.pdf). We should have to support the most updated specification, that is: [0.92](https://sourceforge.net/p/sbml/code/HEAD/tree/trunk/specifications/sbml-level-3/version-1/spatial/specification/spatial-v1-sbml-l3v1-rel0.92.pdf).
- Currently, there is no spatial SBML model builder which allows users to create a spatial model with localization of species (molecules) as it initial state (currently, our software tools only support uniformlly distributed molecular concentration for each compartment). This is the top most required feature of our software tools because most of the simulators for differential equations trys to solve an initial value problem of a set of differential equations.
- In spatial package, there are several ways (analytic geometry, sampled field geometry, parametric geometry, CS geometry, mixed geometry) to describe the spatial geometries in a model. Currently, most of the spatial simulator which supports SBML spatial package supports analytic geometry and sampled field geometry. While we just focus on developing a spatial simulator with FDM (Finite Difference Method) or FVM (Finite Volume Method) as a numerical integrator, supporting analytic geometry and sampled field geometry will be enough. But if we want to implement our spatial simulator with a more stable integrator such as FEM (Finite Element Method), then the model should be described with parametric geometry. Creating a spatial model with parametric geometry from scratch is quite tough, especially if we want to create a spatial model from microscopic image.

This summer, we would like to mentor a student in extending spatial model builder and simulator which will support most updated specification of SBML spatial extension, initial value assignment and parametric geometry.

### Goal
As described in the "Background", the project could be split down into following 4 tasks.

- Improve the spatial model builder (XitoSBML) and spatial simulator to support most updated specification of SBML spatial specification.
- Implement a code on XitoSBML which will import an initial state of molecule concentration from microscopic image and exchange the values to SBML related objects (ex. InitialAssignment).
- Implement a code on Spatial_Simulator which will recognize the above localization of molecular concentration stored in SBML and apply its value as an initial state of the simulation.
- Implement a code on XitoSBML which will convert a spatial model with sampled field geometry to parametric geometry

Following API / libraries will be used for this project.

- [ImageJ API](https://imagej.net/Developing_Plugins_for_ImageJ_1.x) ... for XitoSBML
- [JSBML](http://sbml.org/Software/JSBML) ... for XitoSBML
- [libSBML](http://sbml.org/Software/libSBML) ... for Spatial_Simulator

### Difficulty Level 2
Although this project seems to have many tasks to solve, each of the tasks will not require enormous lines / time to code, because there already exists convenient API and well-documented API docs. The most important part is to understand the specification of SBML spatial extension.

### Skills
Java and C++ programming skills and some basic knowledge on handling XML documents are required. Nice to have a knowledge / experience on SBML, GUI programming and mathematical background on numerical integration.

- (essential) Java, C++, XML
- (nice to have) SBML, GUI programing, mathematical background on numerical integration

### Public Repository
- [XitoSBML](https://github.com/spatialsimulator/XitoSBML)
- [Spatial_Simulator](https://github.com/spatialsimulator/Spatial_Simulator)
- [docker-spatialsim](https://github.com/funasoul/docker-spatialsim)
- [docker-spatialsim-build](https://github.com/funasoul/docker-spatialsim-build)

### References
- [SBML Spatial specification rel 0.92](https://sourceforge.net/p/sbml/code/HEAD/tree/trunk/specifications/sbml-level-3/version-1/spatial/specification/spatial-v1-sbml-l3v1-rel0.92.pdf)
- [SBML Spatial specification rel 0.91](https://sourceforge.net/p/sbml/code/HEAD/tree/trunk/specifications/sbml-level-3/version-1/spatial/specification/spatial-v1-sbml-l3v1-rel0.91.pdf)
- [JSBML Documentation](http://sbml.org/Software/JSBML/docs)
- [libSBML C++ API](http://sbml.org/Software/libSBML/5.16.0/docs//cpp-api/)
- [ImageJ API](https://imagej.net/Developing_Plugins_for_ImageJ_1.x)

### Potential Mentors
- [Akira Funahashi](https://github.com/funasoul) Keio University, Japan
- [Kaito Ii](https://github.com/kaitoii11) Hewlett-Packard Japan, Ltd. , Japan

### Contact
[Akira Funahashi](mailto:funasoul@gmail.com)

**Comment by SamuelSauce** [comment]
Hello! I have been in touch with Andreas Dräger in regards to browsing around for a project that I would like to submit a proposal for in regards to GSoC. After looking around I have decided that this project has peaked my interest, along with having a great fit for my skillset of already being experienced with Java/C++. Besides already being familiar with Java, C++, XML, GUI programming and  numerical integration, I would just need to become more familiar with the technologies that I would be writing code for. Additionally I would like to begin writing my proposal right away as it is due in the near future and would much appreciate if I could have some mentoring in regards to writing my proposal. Any information about how to get started with writing my proposal and who I could share a google doc of my proposal with would be great.

**Comment by draeger** [comment]
Dear @SamuelSauce, thanks for reaching out to us! It is probably best if you take the proposal template at https://tinyurl.com/nrnb-gsoc-application-template and prepare a Google document that you share with all potential mentors, @funasoul, @kaitoii11, and myself. We will be happy to provide you with detailed comments and suggestions.

**Comment by khanspers** [comment]
Active GSoC 2019 project.
